USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_SetEmployeeResignDates]
	@COSTCENTERID [int] = 0,
	@DOCID [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN

DECLARE @INVDOCDETAILSID INT,@STATUSID INT,@RESIGNSTATUS NVARCHAR(50), @RESIGNTYPE NVARCHAR(100), @TENTATIVEDATE NVARCHAR(100),@RESIGNDATE NVARCHAR(100), @REASON NVARCHAR(MAX), @REDATE NVARCHAR(100),@EMPNODE INT   ,@PREVDORELIEVE FLOAT 
DECLARE @STRQRY NVARCHAR(MAX)  
SET @STRQRY='' 

 SELECT @INVDOCDETAILSID=I.INVDOCDETAILSID,@STATUSID=I.STATUSID,@EMPNODE=CC.dcCCNID51,
 @RESIGNTYPE=T.dcAlpha1,@RESIGNDATE=T.dcAlpha2,@TENTATIVEDATE=T.dcAlpha3 ,@REDATE=T.dcAlpha4,@REASON=T.dcAlpha5
 FROM INV_DOCDETAILS I WITH(NOLOCK)
 JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON CC.InvDocDetailsID=I.InvDocDetailsID
 JOIN COM_DOCTEXTDATA T WITH(NOLOCK) ON T.InvDocDetailsID=I.InvDocDetailsID
 WHERE DOCID=@DOCID 
  
 IF (@COSTCENTERID=40069)--APPLY RESIGNATION  
 BEGIN  
  SELECT @RESIGNSTATUS=STATUS FROM COM_Status WITH(NOLOCK) WHERE STATUSID=@STATUSID  
  
  IF(@RESIGNTYPE<>'Rejected')  
  BEGIN  

  SELECT @PREVDORELIEVE=DORELIEVE FROM COM_CC50051 C51 WITH(NOLOCK) WHERE NodeID=@EMPNODE

   SET @STRQRY='UPDATE COM_CC50051 SET  RESIGNREMARKS=ISNULL('''+ ISNULL(@REASON,'') +''',''''),RESIGNTYPE=''' + @RESIGNTYPE +''',RESIGNSTATUS='''+ @RESIGNSTATUS +''' '  
  
   IF(isnull(@RESIGNDATE,'')<>'')  
    SET @STRQRY=@STRQRY +' ,DORESIGN=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@RESIGNDATE) +'''))'  
   IF(isnull(@TENTATIVEDATE,'')<>'')  
    SET @STRQRY=@STRQRY +', DOTENTRELIEVE=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@TENTATIVEDATE) +'''))'  
   IF(isnull(@REDATE,'')<>'' AND @RESIGNTYPE<>'Pending')  
   BEGIN  
    SET @STRQRY=@STRQRY +', DORELIEVE=CONVERT(FLOAT,CONVERT(DATETIME,'''+ CONVERT(NVARCHAR,@REDATE) +'''))'  
  
    -- UPDATING USER STATUS TO IN-ACTIVE W.E.F DateOfRelieving  
    DECLARE @EmpUserID INT  
    SELECT @EmpUserID=ISNULL(UserID,0) From ADM_Users WITH(NOLOCK) Where UserName=(Select Code FROM COM_CC50051 WITH(NOLOCK) WHERE NodeID=@EMPNODE)  
    IF(@EmpUserID IS NOT NULL AND @EmpUserID<>0)  
    BEGIN  
	IF(@PREVDORELIEVE IS NOT NULL AND @PREVDORELIEVE<>CONVERT(FLOAT,CONVERT(DATETIME,@REDATE)))
	  BEGIN
		IF EXISTS(SELECT CostCenterID FROM COM_CostCenterStatusMap WHERE NodeID=@EmpUserID AND FromDate=CONVERT(FLOAT,DATEADD(day,1,@PREVDORELIEVE)) AND ToDate IS NULL)
		BEGIN
			UPDATE COM_CostCenterStatusMap SET FromDate=CONVERT(int,DATEADD(day,1,@REDATE)) WHERE NodeID=@EmpUserID AND FromDate=CONVERT(FLOAT,DATEADD(day,1,@PREVDORELIEVE)) AND ToDate IS NULL
		END
	  END
	  ELSE
	  BEGIN
		 INSERT INTO [COM_CostCenterStatusMap] ([CostCenterID],[NodeID],[Status],FromDate,ToDate,[CreatedBy],[CreatedDate])  
		 SELECT 7,@EmpUserID,2,CONVERT(int,DATEADD(day,1,@REDATE)),NULL,'admin',convert(float,getdate())  
	  END  
  
   END  
      
  END  
  END  
  ELSE  
  BEGIN  
   SET @STRQRY=@STRQRY +' UPDATE COM_CC50051 SET DORESIGN=NULL,DOTENTRELIEVE=NULL,DORELIEVE=NULL,RESIGNREMARKS=NULL,RESIGNTYPE=NULL,RESIGNSTATUS=NULL '  
  END  
  
  SET @STRQRY=@STRQRY + ' WHERE NODEID='''+ CONVERT(NVARCHAR,@EMPNODE) +''''  
  --PRINT @STRQRY  

  EXEC sp_executesql @STRQRY  
 END 
 
END

----spPAY_SetEmployeeResignDates
--40069,
--2908,
--1,1
GO
