USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCRM_GetActivityAssignedList]
	@ActivityID [bigint] = 0,
	@UserID [bigint],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
CREATE TABLE #TBL(ID INT IDENTITY(1,1),ASSIGNEDTO NVARCHAR(300))
	CREATE TABLE #TBL1(ID INT IDENTITY(1,1),TEAM INT,IsGroup INT,IsRole INT,TEAMNODEID INT,USERID INT,[DATE] DATETIME,CreatedBy nvarchar(300))
 
	INSERT INTO #TBL1
	SELECT IsTeam,IsGroup, IsRole,TeamNodeID,USERID,CREATEDDATE,CreatedBy FROM CRM_AssignmentHistory WITH(NOLOCK) 
	WHERE IsFromActivity=@ActivityID
	
	DECLARE @COUNT INT,@I INT,@ISTEAM INT,@ISROLE INT,@ISGROUP INT,@STRUSERS NVARCHAR(MAX),@TOUSER NVARCHAR(300)
	,@DATE DATETIME
	SELECT @I=1,@COUNT=COUNT(*) FROM #TBL1
	WHILE @I<=@COUNT
	BEGIN
		SELECT @ISTEAM=TEAM,@ISROLE=IsRole,@ISGROUP=IsGroup FROM #TBL1 WHERE ID=@I
		IF @ISTEAM=0 AND @ISROLE=0 AND @ISGROUP=0
		BEGIN
				SELECT 	@TOUSER=UserName FROM ADM_Users WHERE UserID =(
				SELECT USERID FROM #TBL1 WHERE ID=@I)
				
				--SELECT @DATE=CONVERT(DATETIME,[DATE],102) FROM #TBL1 WHERE ID=@I
				
				INSERT INTO #TBL
					SELECT @TOUSER 
			 
		END
		ELSE IF @ISTEAM=1
		BEGIN
			
			 SELECT 	@TOUSER=TEAMNAME FROM CRM_TEAMS WHERE TeamID =(
				SELECT TEAMNODEID FROM #TBL1 WHERE ID=@I)
				
				--SELECT @DATE=CONVERT(DATETIME,[DATE],102) FROM #TBL1 WHERE ID=@I
				
				INSERT INTO #TBL
					SELECT @TOUSER
				
		END
		ELSE IF @ISGROUP=1
		BEGIN
			 
			 SELECT  @TOUSER=GROUPNAME FROM COM_Groups WHERE GROUPNAME<>'' and GID =(
				SELECT TEAMNODEID FROM #TBL1 WHERE ID=@I)
				
				--SELECT @DATE=CONVERT(DATETIME,[DATE],102) FROM #TBL1 WHERE ID=@I
			 
				INSERT INTO #TBL
					SELECT @TOUSER
		END
		ELSE IF @ISROLE=1
		BEGIN
	 
			 SELECT  @TOUSER=NAME FROM ADM_PROLES WHERE ROLEID =(
				SELECT TEAMNODEID FROM #TBL1 WHERE ID=@I)
				
				--SELECT @DATE=CONVERT(DATETIME,[DATE],102) FROM #TBL1 WHERE ID=@I
				
				INSERT INTO #TBL
					SELECT @TOUSER 
		END
		SET @I=@I+1
	END
	SELECT @STRUSERS = coalesce(@STRUSERS , '  ' , ' ')+ Convert(varchar(50), ASSIGNEDTO)+','    FROM #TBL
	SELECT  @STRUSERS
	drop table 	#TBL
	drop table 	#TBL1
  
RETURN 1
  
GO
