USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCOM_SetActivityLinking]
	@CostCenterID [bigint],
	@NodeID [bigint],
	@ActivityID [bigint]
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION     
SET NOCOUNT ON;    
    CREATE TABLE #TBL(ID INT IDENTITY(1,1),CostCenterColIDBase INT,CostCenterColIDLinked INT)
    INSERT INTO #TBL
    SELECT CostCenterColIDBase,CostCenterColIDLinked FROM COM_DocumentLinkDetails WHERE 
    DocumentLinkDeFID IN (SELECT DocumentLinkDeFID FROM [COM_DocumentLinkDef]   WHERE CostCenterIDLinked=@CostCenterID AND CostCenterIDBase=144)
    
    DECLARE @COUNT INT,@I INT,@SYSCOLSOURCE NVARCHAR(300),@SYSCOLDEST NVARCHAR(300),@isInventory bit,@UPDATEAQL NVARCHAR(MAX),@tempCode NVARCHAR(300),
    @SOURCEDATA NVARCHAR(300),@DESTDATA NVARCHAR(300),@TSQL NVARCHAR(MAX),@SYSTABLESOURCE NVARCHAR(300),@SYSTABLEDEST NVARCHAR(300)
    SELECT @COUNT=COUNT(*),@I=1 FROM #TBL
    SET @TSQL=''
    SET @UPDATEAQL=''
    SELECT @isInventory=ISINVENTORY FROM COM_DOCUMENTTYPES WHERE COSTCENTERID=@CostCenterID
    WHILE @I<=@COUNT
    BEGIN
		SELECT @SYSCOLDEST=SYSCOLUMNNAME,@SYSTABLEDEST=SYSTABLENAME FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERCOLID IN (
		SELECT CostCenterColIDBase FROM #TBL WHERE ID=@I) AND COSTCENTERID=144
		
		SELECT @SYSCOLSOURCE=SYSCOLUMNNAME,@SYSTABLESOURCE=SYSTABLENAME FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERCOLID IN (
		SELECT CostCenterColIDLinked FROM #TBL WHERE ID=@I) AND COSTCENTERID=@CostCenterID
		
		--SELECT @SYSTABLEDEST=SYSTABLENAME FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERCOLID IN (
		--SELECT CostCenterColIDLinked FROM #TBL WHERE ID=@I)
		
	 
		
		 IF(@CostCenterID>40000)
		 BEGIN
			
			 SET @tempCode='@SOURCEDATA NVARCHAR(300) OUTPUT'
			 
			 IF @SYSTABLESOURCE='INV_DocDetails' OR @SYSTABLESOURCE='ACC_DocDetails' 
				 SET @TSQL=' SET @SOURCEDATA=(SELECT TOP 1 '+@SYSCOLSOURCE+' FROM '+@SYSTABLESOURCE+' WHERE COSTCENTERID='+CONVERT(NVARCHAR(300),@CostCenterID)+'
				 AND DOCID IN ('+CONVERT(NVARCHAR(400),@NodeID) + ') )' 
			 ELSE  IF @SYSTABLESOURCE='COM_DocTextData' 
			 BEGIN
				 IF(@isInventory=1)				 
					 SET @TSQL=' SET @SOURCEDATA=(SELECT  '+@SYSCOLSOURCE+' FROM '+@SYSTABLESOURCE+' WHERE INVDOCDETAILSID IN(SELECT DOCID FROM  INV_DocDetails WITH(NOLOCK) WHERE COSTCENTERID='+CONVERT(NVARCHAR(300),@CostCenterID)+'
					 AND DOCID IN ('+CONVERT(NVARCHAR(400),@NodeID) + ')) )' 
			     ELSE
					 SET @TSQL=' SET @SOURCEDATA=(SELECT  '+@SYSCOLSOURCE+' FROM '+@SYSTABLESOURCE+' WHERE INVDOCDETAILSID IN(SELECT DOCID FROM  INV_DocDetails WITH(NOLOCK) WHERE COSTCENTERID='+CONVERT(NVARCHAR(300),@CostCenterID)+'
					 AND DOCID IN ('+CONVERT(NVARCHAR(400),@NodeID) + ')) )' 		 
			 END 	 
			 EXEC SP_EXECUTESQL @TSQL, @tempCode,@SOURCEDATA OUTPUT
			 
			  
			 IF @SYSCOLDEST='AccountId'
				SET @UPDATEAQL=@UPDATEAQL + @SYSCOLDEST +' = ' + @SOURCEDATA
			 ELSE
			    SET @UPDATEAQL=@UPDATEAQL + @SYSCOLDEST+' = ' + ''''+@SOURCEDATA+''''
			    
			 	 SET @UPDATEAQL=@UPDATEAQL + ',' 
			 	 PRINT @UPDATEAQL
		 END
		
    SET @I=@I+1
    END
    
    
COMMIT TRANSACTION    
--ROLLBACK TRANSACTION  
 SET NOCOUNT OFF;     
RETURN 1    
GO
