USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetTDSMonthNames1]
	@Flag [int],
	@Date [datetime],
	@EmpNode [int],
	@DocYear [int],
	@DocID [int],
	@USERID [int] = 1,
	@LANGID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @Year INT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME,@Grade INT,@PayrollDate DATETIME
DECLARE @STARTMONTH AS INT,@ENDMONTH INT,@REMAININGMONTH INT,@REMAININGMONTHCOUNT INT,@I INT
DECLARE @ALStartMonth INT,@ALStartDate DATETIME,@ALEndDate DATETIME 
DECLARE @SURCHARGE DECIMAL(9,2),@EDUCESS DECIMAL(9,2),@SECANDHIGHEDUCESS DECIMAL(9,2)
DECLARE @STRQRY VARCHAR(MAX),@NUMFILEDNAME VARCHAR(200),@MAXSNO INT,@CurDBName NVARCHAR(100),@CurDBIndex INT

DECLARE @TABTEMPMONTHQUARTER TABLE(TDSTYPE VARCHAR(10),MONTHNO int,NODEID VARCHAR(5),YEARNO INT,QUARTERNO INT)
DECLARE @TABMONTHQUARTER TABLE(ID INT IDENTITY(1,1),TDSTYPE VARCHAR(10),MONTHTEXT VARCHAR(15),NODEID VARCHAR(5),YEARNO INT,
							   QUARTERNO INT,PAYROLLDATE DATETIME,AMOUNT DECIMAL(9,2),TDS DECIMAL(9,2),SURCHARGE DECIMAL(9,2),
							   EDUCATIONCESS DECIMAL(9,2),SECANDHIGHEDUCESS DECIMAL(9,2))
DECLARE @TABTAXCALCULATION TABLE(ID INT IDENTITY(1,1),SNO INT,PAYROLLDATE DATETIME,COMPONENTID INT,TAXCOMPONENTID INT,TAXCOMPONENTNAME VARCHAR(50),
								 AMOUNT DECIMAL(9,2),TDS DECIMAL(9,2),SURCHARGE DECIMAL(9,2),EDUCATIONCESS DECIMAL(9,2),SECANDHIGHEDUCESS DECIMAL(9,2))
DECLARE @TABTAXCOMPONENTS TABLE(ID INT IDENTITY(1,1),SNO INT,PAYROLLDATE DATETIME,COMPONENTID INT,TAXCOMPONENTID INT,TAXCOMPONENTNAME VARCHAR(50))
CREATE TABLE #EMPPAY(EMPNODE INT,SNO INT,AMOUNT DECIMAL(9,2),PAYROLLDATE DATETIME)


SELECT @CurDBName=DB_NAME() 
SET @CurDBIndex=REPLACE(@CurDBName,'PACT2C','')
SELECT @ALStartMonth=AccountingFromMonth FROM PACT2C.dbo.ADM_Company WHERE DBIndex=@CurDBIndex

--READING START MONTH FROM GLOBAL PREFERENCES
--SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE NAME='LeaveYear'

--SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
SET @ALStartDate= CONVERT(VARCHAR,@DocYear)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
SET @ALStartDate=CONVERT(DATETIME,@ALStartDate)

--SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
SET @ALEndDate=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,DATEADD(M,11,@ALStartDate))+1,0))
SET @ALEndDate=CONVERT(DATETIME,@ALEndDate)

--SET TO FIRST DAY FOR THE GIVEN DATE
SET @PayrollDate=DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DATETIME,@ALEndDate)),0)
PRINT 'DATE'
PRINT @PayrollDate
--FOR Grade

IF((SELECT COUNT(*) FROM ADM_CostCenterDef WITH(NOLOCK) WHERE CostCenterID=50051 and SysColumnName ='CCNID53' and IsColumnInUse=1 and UserProbableValues='H')>0)
	SELECT @Grade=ISNULL(HistoryNodeID,0) FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID=@EmpNode AND CostCenterID=50051 AND HistoryCCID=50053 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,@PayrollDate)) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,@PayrollDate) OR ToDate IS NULL)
ELSE
	SELECT @Grade=ISNULL(CCNID53,0) FROM COM_CCCCDATA WITH(NOLOCK) WHERE COSTCENTERID=50051 AND NODEID=@EmpNode
	
----FOR START DATE AND END DATE OF LEAVEYEAR	
--EXEC [spPAY_EXTGetLeaveyearDates] @Date,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT
SET @Year= DATEPART(yyyy,@ALStartDate)
SET @ALEndMonthYear=@ALEndDate

--FOR FISCAL YEAR START MONTH OTHER THAN JAN MONTH
SET @REMAININGMONTHCOUNT=1
SET @STARTMONTH=DATEPART(mm,@ALStartDate)
SET @ENDMONTH=DATEPART(mm,@ALEndDate)
IF (@STARTMONTH<>1)
	SET @REMAININGMONTH=@STARTMONTH-1

--INSERTING MONTH NOS OF FISCAL YEAR 
WHILE(@STARTMONTH<=12)
BEGIN
	INSERT INTO @TABTEMPMONTHQUARTER VALUES('Monthly',@STARTMONTH,@STARTMONTH,@Year,0)
	IF (@REMAININGMONTH>0 AND @REMAININGMONTHCOUNT<=@REMAININGMONTH)
	BEGIN
		INSERT INTO @TABTEMPMONTHQUARTER VALUES('Monthly',@REMAININGMONTHCOUNT,@REMAININGMONTHCOUNT,DATEPART(yyyy,@ALEndMonthYear),0)
	SET @REMAININGMONTHCOUNT=@REMAININGMONTHCOUNT+1
	END
SET @STARTMONTH=@STARTMONTH+1
END

--INSERTING QUARTER NOS OF FISCAL YEAR
SET @STARTMONTH=1
WHILE(@STARTMONTH<=4)
BEGIN
	INSERT INTO @TABTEMPMONTHQUARTER VALUES('Quarterly',@STARTMONTH,@STARTMONTH,@Year,0)
SET @STARTMONTH=@STARTMONTH+1
END

--LOADING @TABTEMPMONTHQUARTER DATA INTO @TABMONTHQUARTER WITH SERIAL ID
INSERT INTO @TABMONTHQUARTER SELECT *,null,0,0,0,0,0 FROM @TABTEMPMONTHQUARTER  ORDER BY TDSTYPE,YEARNO ,MONTHNO

--UPDATING QUARTERNO FOR MONTHS OF FISCAL YEAR
UPDATE @TABMONTHQUARTER SET QUARTERNO=1 WHERE ID<=3
UPDATE @TABMONTHQUARTER SET QUARTERNO=2 WHERE ID>3 AND ID<=6
UPDATE @TABMONTHQUARTER SET QUARTERNO=3 WHERE ID>6 AND ID<=9
UPDATE @TABMONTHQUARTER SET QUARTERNO=4 WHERE ID>9 AND ID<=12
UPDATE @TABMONTHQUARTER SET MONTHTEXT=REPLACE(TDSTYPE,'ly','')+MONTHTEXT WHERE ID>12

--INSERTING PAYROLL MONTHS OF FISCAL YEAR IN @TABTAXCALCULATION TABLE AND UPDATING PAYROLL MONTHS TO @TABMONTHQUARTER BASED ON ID(MONTHNO)
SET @I=0
WHILE(@I<12)
BEGIN
	INSERT INTO @TABTAXCALCULATION VALUES(0,DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartDate)+@I,0))),0,0,'',0,0,0,0,0)
	UPDATE @TABMONTHQUARTER SET PAYROLLDATE=DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartDate)+@I,0))) WHERE ID=@I+1
SET @I=@I+1
END

--INSERTING TAX COMPONENT FILEDS FROM CUSTOMIZE PAYROLL(TAXMAP)
INSERT INTO @TABTAXCOMPONENTS 
	   SELECT SNO,CONVERT(DATETIME,PAYROLLDATE),COMPONENTID,TAXMAP ,0 FROM  COM_CC50054 WITH(NOLOCK) WHERE GRADEID=@Grade AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@PayrollDate) AND GRADEID=@Grade) AND ISNULL(TAXMAP,0)>0

	   
--UPDATING SNO AND COMPONENTID OF TAXMAP FILED
UPDATE TC SET TC.SNO=CP.SNO,TC.TAXCOMPONENTID=ISNULL(CP.TAXCOMPONENTID,0),TC.TAXCOMPONENTNAME=PC.NAME,TC.COMPONENTID=ISNULL(CP.COMPONENTID,0)
		  FROM @TABTAXCOMPONENTS CP	
		  INNER JOIN COM_CC50052 PC ON PC.NODEID=CP.TAXCOMPONENTID 
		  INNER JOIN @TABTAXCALCULATION TC ON CONVERT(DATETIME,CP.PAYROLLDATE)=CONVERT(DATETIME,TC.PAYROLLDATE) 

		  
--INSERTING DATA FROM MONTHLY PAYROLL TABLE OF TAXMAP FIELD AMOUNT AND PAYROLL DATE
SELECT @MAXSNO=max(SNO) FROM  COM_CC50054 WITH(NOLOCK) WHERE GRADEID=@Grade AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@PayrollDate) AND GRADEID=@Grade) 
SET @I=1
WHILE(@I<=@MAXSNO)
BEGIN
	SET @NUMFILEDNAME='dcCalcNum'+convert(varchar,@i)
	IF EXISTS(SELECT Name FROM Sys.Columns WHERE Name=@NUMFILEDNAME AND object_id=(Select object_id FROM Sys.tables Where Name='PAY_DOCNUMDATA'))
	BEGIN
		SET @STRQRY='INSERT INTO #EMPPAY 
							SELECT '+ CONVERT(VARCHAR,@EMPNODE) +' ,'+ CONVERT(VARCHAR,@I) +' ,'+ @NUMFILEDNAME +',ID.DueDate
							FROM INV_DOCDETAILS ID WITH(NOLOCK),PAY_DOCNUMDATA DN WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK) 
							WHERE ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND DN.INVDOCDETAILSID=CC.INVDOCDETAILSID  
							AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID 
							AND  COSTCENTERID=40054 AND VOUCHERTYPE=12 AND  CC.DCCCNID51='+CONVERT(VARCHAR,@EmpNode)
		PRINT (@STRQRY)
		EXEC sp_executesql @STRQRY
	END
SET @I=@I+1
END


--READING PERCENTAGE OF CHARGES FROM INCOME TAX DEFINITIONS FOR GIVEN YEAR
SELECT TOP 1 @SURCHARGE=CONVERT(DECIMAL,TD.DCALPHA3),@EDUCESS=CONVERT(DECIMAL,TD.DCALPHA4),@SECANDHIGHEDUCESS=CONVERT(DECIMAL,TD.DCALPHA5) FROM COM_DOCTEXTDATA TD ,INV_DOCDETAILS ID WHERE ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND  COSTCENTERID=40074 AND CONVERT(INT,TD.DCALPHA1)=@DocYear

UPDATE TC SET TC.TDS=((100 * ISNULL(ROUND(CP.AMOUNT,0),0)) / (100 + @SURCHARGE + @EDUCESS + @SECANDHIGHEDUCESS))
  		  FROM #EMPPAY CP INNER JOIN @TABTAXCALCULATION TC ON CONVERT(DATETIME,CP.PAYROLLDATE)=CONVERT(DATETIME,TC.PAYROLLDATE) --AND CP.SNO=TC.SNO

UPDATE TC SET TC.AMOUNT=ISNULL(CP.AMOUNT,0), TC.SURCHARGE=(ISNULL(TC.TDS,0)*@SURCHARGE)/100, TC.EDUCATIONCESS=(ISNULL(TC.TDS,0)*@EDUCESS)/100
			 ,TC.SECANDHIGHEDUCESS=(ISNULL(TC.TDS,0)*@SECANDHIGHEDUCESS)/100
  		  FROM #EMPPAY CP INNER JOIN @TABTAXCALCULATION TC ON CONVERT(DATETIME,CP.PAYROLLDATE)=CONVERT(DATETIME,TC.PAYROLLDATE) --AND CP.SNO=TC.SNO  		  
	
--UPDATING CHARGES IN @TABMONTHQUARTER TABLE FROM @TABTAXCALCULATION TABLE
UPDATE TC SET TC.AMOUNT=ISNULL(CP.AMOUNT,0), TC.SURCHARGE=ROUND(CP.SURCHARGE,0), 
			  TC.EDUCATIONCESS=ROUND(CP.EDUCATIONCESS,0),TC.SECANDHIGHEDUCESS=ROUND(CP.SECANDHIGHEDUCESS,0), TC.TDS=ROUND(CP.TDS,0)
		  FROM @TABTAXCALCULATION CP INNER JOIN @TABMONTHQUARTER TC ON CONVERT(DATETIME,CP.PAYROLLDATE)=CONVERT(DATETIME,TC.PAYROLLDATE)

--UPDATING QUARTERLY SUM AMOUNT IN QUEARTERLY TDSTYPE FIELD BASED ON QUARTERNO OF MONTHS
UPDATE TC SET TC.AMOUNT=ISNULL(ROUND(CP.AMOUNT,0),0) FROM @TABMONTHQUARTER TC 
			  INNER JOIN (SELECT QUARTERNO,SUM(AMOUNT) AMOUNT FROM @TABMONTHQUARTER CP GROUP BY QUARTERNO) AS CP
			  ON CP.QUARTERNO=TC.NODEID AND TC.TDSTYPE='Quarterly'

--SELECT * FROM @TABTAXCALCULATION
SELECT * FROM @TABMONTHQUARTER
DROP TABLE #EMPPAY
END
GO
