USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_RptLeaveDetails]
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @RC INT,@TRC INT,@CURRFISCALYEARSTART INT,@CURRFISCALYEAREND INT
	DECLARE @TABEMPINFO TABLE(ID INT IDENTITY(1,1),SNO INT,EMPNODE INT,DOJ DATETIME,LEAVETYPENODE INT,LEAVETYPENAME VARCHAR(100))
	DECLARE @TABEMPINFO1 TABLE(SNO INT,EMPNODE INT,LEAVETYPENODE INT,STARTDATE DATETIME,ENDDATE DATETIME,OPB DECIMAL(9,2))
	INSERT INTO @TABEMPINFO 
				SELECT 0,C51.NODEID,CONVERT(DATETIME,C51.DOJ),C52.NODEID,C52.NAME FROM COM_CC50051 C51
				CROSS JOIN COM_CC50052 C52 WITH(NOLOCK) 
				 WHERE C52.PARENTID=5 AND C52.ISGROUP=0 AND C51.ISGROUP=0 AND ISNULL(DOJ,'')<>'' ORDER BY DOJ
	
	DECLARE @TABLEAVES TABLE(ID INT IDENTITY(1,1),EMPNODE INT,EMPNAME VARCHAR(500),LEAVETYPENODE INT,LEAVETYPENAME VARCHAR(100),FROMDATE1 DATETIME,
							 TODATE1 DATETIME,OPENINGBALANCE DECIMAL(9,2),DAYSTAKEN DECIMAL(9,2))
    insert into @TABLEAVES 
    SELECT dc.dcccnid51 EmployeeCode,emp.Name EmpName,lt.nodeid,lt.name LEAVETYPENAME,convert(datetime,td.dcalpha4) FROMDATE,convert(datetime,td.dcalpha5) TODATE,
		0,td.dcalpha7 DAYSTAKEN
	FROM   COM_DocTextData td,COM_DocccData dc,inv_docdetails id ,COM_CC50052 lt,COM_CC50051 emp
	WHERE  id.invdocdetailsid=td.invdocdetailsid 
	   and id.invdocdetailsid=dc.invdocdetailsid
	   and td.invdocdetailsid=dc.invdocdetailsid
	   and emp.nodeid=dc.dcccnid51
	   and id.statusid not in (372,376)
	   and lt.nodeid=DC.dcccnid52
	   and id.COSTCENTERID=40062
    
    DECLARE @Year INT,@ALStartMonth INT,@ALStartMonthYear1 DATETIME,@ALEndMonthYear1 DATETIME
	
	SELECT @Year=YEAR(CONVERT(DATETIME,GETDATE()))
	--PRINT @Year
	--FOR READING START MONTH FROM GLOBAL PREFERENCES
	SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE (NAME='LeaveYear' OR RESOURCEID=94471)
	
	--SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
	SET @ALStartMonthYear1= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
	SET @ALStartMonthYear1=CONVERT(DATETIME,@ALStartMonthYear1)
	--PRINT @ALStartMonthYear
	
	--SET ENDMONTH FOR THE NEXT YEAR (1YEAR)
	SET @ALEndMonthYear1=DATEADD(M,11,@ALStartMonthYear1)
	
	--SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
	SET @ALEndMonthYear1=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALEndMonthYear1)+1,0))
	SET @ALEndMonthYear1=CONVERT(DATETIME,@ALEndMonthYear1)
	--PRINT @ALEndMonthYear
	DECLARE @YEARDIFF INT,@YC INT,@DOJ DATETIME	,@FDATE DATETIME,@TDATE DATETIME,@ENODE INT,@LTNODE INT,@STARTDATE DATETIME,@OPB DECIMAL(9,2)
  
	SET @YC=0
	
    SET @RC=1
    SELECT @TRC=COUNT(*) FROM @TABEMPINFO
    
    WHILE(@RC<=@TRC)
    BEGIN
			SET @YC=0
			SELECT @DOJ=DOJ ,@ENODE=EMPNODE,@LTNODE=LEAVETYPENODE FROM @TABEMPINFO WHERE ID=@RC
			SELECT @YEARDIFF=DATEDIFF(yyyy,@DOJ,@ALEndMonthYear1)
			WHILE(@YC<=@YEARDIFF)
			BEGIN
				SET @STARTDATE=DATEADD(YYYY,@YC,@DOJ)
				EXEC [spPAY_EXTGetLeaveyearDates] @STARTDATE,@FDATE OUTPUT,@TDATE OUTPUT
				--SET @FDATE=@DOJ
				SELECT @OPB=ISNULL(DN.DCNUM3,0)	FROM   INV_DOCDETAILS ID WITH(NOLOCK), COM_DocCCData DC WITH(NOLOCK),COM_DocNumData DN WITH(NOLOCK),COM_DocTextData TD WITH(NOLOCK)
				WHERE  ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND DC.INVDOCDETAILSID=DN.INVDOCDETAILSID AND
			   ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND ISDATE(TD.DCALPHA3)=1 AND ISDATE(TD.DCALPHA4)=1
  			   AND CONVERT(DATETIME,@FDATE) between CONVERT(DATETIME,TD.DCALPHA3) and CONVERT(DATETIME,TD.DCALPHA4)
			   AND ID.COSTCENTERID=40060 AND ID.STATUSID=369 AND DC.DCCCNID51=@ENODE AND DC.DCCCNID52=@LTNODE
			   AND (ISNULL(ID.LINENARRATION,'')='OPB' OR ISNULL(ID.LINENARRATION,'')='OP' OR ISNULL(ID.LINENARRATION,'')='OPENING BALANCE')
				
				INSERT INTO @TABEMPINFO1 SELECT @RC,@ENODE,@LTNODE,@FDATE, @TDATE,ISNULL(@OPB,0)
				SET @YC=@YC+1
			END
		
	SET @RC=@RC+1
    END
	--SELECT * FROM @TABEMPINFO 
	--select * from @TABLEAVES
	update t set openingbalance=t1.opb from @TABLEAVES t,@TABEMPINFO1 t1 where t.empnode=t1.empnode and t.leavetypenode=t1.leavetypenode 
		and convert(datetime,t.todate1) between convert(datetime,t1.startdate) and convert(datetime,t1.enddate)
	select * from @TABLEAVES
	--SELECT * FROM @TABEMPINFO1
SET NOCOUNT OFF;
END
GO
