USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetExtPayrollProcessedDetails]
	@COSTCENTERID [int] = 0,
	@DOCID [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @FROMDATE DATETIME,@DOCUMENTTYPE INT,@EMPNODE INT,@ALLOWLEAVESIFPAYROLLPROCESSED VARCHAR(5),@ALLOWDAILYPAYROLLFORPOSTEDMONTHS VARCHAR(5),@ALLOWVACATIONIFPAYROLLPROCESSED VARCHAR(5)
DECLARE @RC AS INT,@TRC AS INT,@EmployeeID INT

DECLARE @TAB TABLE(ID INT IDENTITY(1,1),EMPNODE INT,DOCUMENTTYPE INT)

IF (ISNULL(@DOCID,0)>0 AND @COSTCENTERID=0)
BEGIN
	INSERT INTO @TAB
		SELECT CC.DCCCNID51,ID.DOCUMENTTYPE FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID									
		WHERE  ID.DOCID=@DOCID
	
	SET @RC=1
	SELECT @TRC=COUNT(*) FROM @TAB
	WHILE (@RC<=@TRC)
	BEGIN	
		SELECT  @DOCUMENTTYPE=DOCUMENTTYPE,@EMPNODE=EMPNODE FROM @TAB WHERE ID=@RC
		IF (@DOCUMENTTYPE=67)
			SELECT @FROMDATE= MAX(CONVERT(DATETIME,DCALPHA1)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID	 WHERE ID.DOCID=@DOCID AND CC.DCCCNID51=@EMPNODE
		ELSE IF(@DOCUMENTTYPE=68)
			SELECT @FROMDATE= MAX(CONVERT(DATETIME,DCALPHA2)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID	 WHERE ID.DOCID=@DOCID AND CC.DCCCNID51=@EMPNODE
		ELSE IF(@DOCUMENTTYPE=72)
			SELECT @FROMDATE= MAX(CONVERT(VARCHAR,TD.DCALPHA2)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID WHERE ID.DOCID=@DOCID AND TD.DCALPHA17='No'
		ELSE IF(@DOCUMENTTYPE=97)
			SELECT @FROMDATE= MAX(CONVERT(DATETIME,DCALPHA33)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID	 WHERE ID.DOCID=@DOCID AND CC.DCCCNID51=@EMPNODE
		ELSE
			SELECT @FROMDATE= CASE ISNULL(@DOCUMENTTYPE,0) WHEN 58 THEN MAX(CONVERT(DATETIME,ID.DOCDATE)) ELSE MAX(CONVERT(VARCHAR,DCALPHA4)) END FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID WHERE ID.DOCID=@DOCID 
PRINT @FROMDATE
PRINT @EMPNODE
		IF ((SELECT COUNT(*)  FROM COM_DocTextData TD WITH(NOLOCK) JOIN INV_DOCDETAILS ID WITH(NOLOCK) ON ID.InvDocDetailsID=TD.InvDocDetailsID	JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.InvDocDetailsID=CC.InvDocDetailsID
			 WHERE  ID.CostCenterID=40054 AND ISDATE(DCALPHA17)=1 AND ISDATE(DCALPHA18)=1 AND CC.DCCCNID51=@EMPNODE	 AND ((CONVERT(DATETIME,@FROMDATE) between CONVERT(DATETIME,DCALPHA17) and CONVERT(DATETIME,DCALPHA18))))>0)
		BEGIN
			SELECT ErrorMessage as StatusMessage FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-562 AND LanguageID=@LangID
		END
	SET @RC=@RC+1
	END
END
ELSE IF (ISNULL(@DOCID,0)>0 AND @COSTCENTERID>0)--ONSAVE MODE
BEGIN
	SELECT @ALLOWLEAVESIFPAYROLLPROCESSED=ISNULL(VALUE,'') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='AllowLeavesifPayrollProcessedorLocked'
	SELECT @ALLOWDAILYPAYROLLFORPOSTEDMONTHS=ISNULL(VALUE,'') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='AllowDailyPayrollEntryforPostedMonths'
	SELECT @ALLOWVACATIONIFPAYROLLPROCESSED=ISNULL(VALUE,'') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='AllowVacationifPayrollProcessedorLocked'
	
	INSERT INTO @TAB
	SELECT CC.DCCCNID51,ID.DOCUMENTTYPE FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID									
	WHERE  ID.DOCID=@DOCID AND ID.COSTCENTERID=@COSTCENTERID
	
	SET @RC=1
	SELECT @TRC=COUNT(*) FROM @TAB
	WHILE (@RC<=@TRC)
	BEGIN	
		SELECT  @DOCUMENTTYPE=DOCUMENTTYPE,@EMPNODE=EMPNODE FROM @TAB WHERE ID=@RC
		
		IF (@DOCUMENTTYPE=67)
			SELECT @FROMDATE= MAX(CONVERT(DATETIME,DCALPHA1)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID	 WHERE ID.DOCID=@DOCID AND CC.DCCCNID51=@EMPNODE AND ID.COSTCENTERID=@COSTCENTERID
		ELSE IF(@DOCUMENTTYPE=72)
			SELECT @FROMDATE= MAX(CONVERT(VARCHAR,TD.DCALPHA2)) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID WHERE ID.DOCID=@DOCID AND ID.COSTCENTERID=@COSTCENTERID AND TD.DCALPHA17='No'
		ELSE
			SELECT @FROMDATE= CASE ISNULL(@DOCUMENTTYPE,0) WHEN 58 THEN MAX(CONVERT(DATETIME,ID.DOCDATE)) WHEN 72 THEN MAX(CONVERT(VARCHAR,TD.DCALPHA2)) WHEN 68 THEN MAX(CONVERT(VARCHAR,TD.DCALPHA2)) ELSE MAX(CONVERT(VARCHAR,DCALPHA4)) END FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID WHERE ID.DOCID=@DOCID AND ID.COSTCENTERID=@COSTCENTERID
			
		PRINT @FROMDATE
								
		IF ((SELECT COUNT(*)  FROM COM_DocTextData TD WITH(NOLOCK) JOIN INV_DOCDETAILS ID WITH(NOLOCK) ON ID.InvDocDetailsID=TD.InvDocDetailsID	JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.InvDocDetailsID=CC.InvDocDetailsID
			 WHERE  ID.CostCenterID=40054 AND ISDATE(DCALPHA17)=1 AND ISDATE(DCALPHA18)=1 AND CC.DCCCNID51=@EMPNODE AND ((CONVERT(DATETIME,@FROMDATE) between CONVERT(DATETIME,DCALPHA17) and CONVERT(DATETIME,DCALPHA18))))>0)
		BEGIN
			IF ((@DOCUMENTTYPE=62 OR @DOCUMENTTYPE=63) AND @ALLOWLEAVESIFPAYROLLPROCESSED='False')
				RAISERROR('-562',16,1) 
			ELSE IF (@DOCUMENTTYPE=67 AND @ALLOWDAILYPAYROLLFORPOSTEDMONTHS='False')
				RAISERROR('-561',16,1)
			ELSE IF (@DOCUMENTTYPE=72 AND @ALLOWVACATIONIFPAYROLLPROCESSED='False')
				RAISERROR('-562',16,1) 
			ELSE IF (@DOCUMENTTYPE<>62 and @DOCUMENTTYPE<>67 and @DOCUMENTTYPE<>63 and @DOCUMENTTYPE<>72)
				RAISERROR('-562',16,1) 
		END
	SET @RC=@RC+1
	END
END
SET NOCOUNT OFF;	
END
GO
