USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCOM_GetTableData]
	@FEATURE [int],
	@UserID [bigint],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION
SET NOCOUNT ON
BEGIN TRY
		DECLARE @SQL NVARCHAR(MAX)
		 
		--SP Required Parameters Check
		IF @FEATURE=0
		BEGIN
			RAISERROR('-100',16,1)
		END

		 IF @FEATURE = 3
		 BEGIN
			SELECT PRODUCTID,PRODUCTCODE+'_'+PRODUCTNAME [PRODUCT] FROM INV_PRODUCT with(nolock)
		 END
		 ELSE IF @FEATURE > 50000
		 BEGIN
			DECLARE @TABLENAME NVARCHAR(300)
			SELECT @TABLENAME=TABLENAME FROM ADM_FEATURES with(nolock) WHERE FEATUREID=@FEATURE		 
			SET @SQL='SELECT CODE,NAME,NODEID FROM '+@TABLENAME + ' with(nolock) WHERE Isgroup <> 1 ' 
		    EXEC(@SQL)
			
		 END 
		  
COMMIT TRANSACTION
SET NOCOUNT OFF;  
RETURN 1
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END
ROLLBACK TRANSACTION
SET NOCOUNT OFF  
RETURN -999   
END CATCH










GO
