USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_RptGetVacationLedger]
	@EmpWhere [nvarchar](max) = NULL,
	@FromDate [datetime],
	@ToDate [datetime],
	@CCWhere [nvarchar](max) = NULL
WITH ENCRYPTION, EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE @STARTDATE DATETIME
	,@ENDDATE DATETIME
	,@VFD DATETIME
	,@VTD DATETIME
	,@DOJ DATETIME
	,@LASON DATETIME
	,@MONT1 DATETIME
	,@MONT2 DATETIME
	,@DOJ1 DATETIME,
	@Calculatevacdayforvacationperiod Varchar(3),
	@ExcessDaysAsLOP Varchar(3),
	@FDate Datetime,@TDate Datetime,@BDays FLOAT,
	@VacTaken FLOAT,@EnDays FLOAT,@DonotshownegitiveOPvacationdays NVARCHAR(6),@ConsiderLOPwhilecalculatingcreditdays NVARCHAR(6),@DJ datetime
	DECLARE @LOPDAYS FLOAT, @CreditDaysCalculation Int,@FSEncashDays FLOAT,@DORELIEVE FLOAT,@DR DATETIME


	SET @VacTaken=0 SET @EnDays=0

DECLARE @EMPNAME NVARCHAR(MAX)
	,@EMPCODE NVARCHAR(MAX)
	,@STRFROMDATERANGE NVARCHAR(MAX)
	,@STRTODATERANGE NVARCHAR(MAX)
	,@FMONTH DATETIME
	,@TMONTH DATETIME
DECLARE @EncashDays FLOAT
	,@RC1 INT
	,@VDays FLOAT
	,@VacationMonthsDiff FLOAT
	,@OPB FLOAT
	,@GRADE INT
	,@I INT
	,@TRC INT
	,@OPENINGBAL FLOAT
	,@VACDAYSPERIOD NVARCHAR(10)
	,@VACDAYSPERMONTH FLOAT
DECLARE @J INT
	,@RC INT
	,@NODEID INT
	,@STRVACDAYS FLOAT,@VT FLOAT
	,@STRVACDAYS1 FLOAT
	,@K INT
	,@KK INT
	,@EID INT
	,@ACVDAYS FLOAT
DECLARE @TAB TABLE (
	ID INT IDENTITY(1, 1)
	,NODEID INT
	,EMPCODE NVARCHAR(MAX)
	,EMPNAME NVARCHAR(MAX)
	,DOJ DATETIME
	,GRADE INT
	,SERVICEDAYS FLOAT
	,MONTHDIFF FLOAT
	,OPENING FLOAT
	,OPENINGBAL FLOAT
	,LEAVEASONDATE DATETIME
	,DOJ1 DATETIME
	,VACDAYSPERIOD NVARCHAR(10)
	,VACDAYSPERMONTH FLOAT
	,DORELIEVE FLOAT
	)

CREATE TABLE #TABVAC (
	ID INT IDENTITY(1, 1)
	,FROMDATE DATETIME
	,TODATE DATETIME
	,VACDAYS FLOAT
	)

DECLARE @MonthDays TABLE (
	ID INT Identity(1, 1)
	,EMPNODE INT
	,EMPCODE NVARCHAR(MAX)
	,EMPNAME NVARCHAR(MAX)
	,DATEOFJ DATETIME
	,FDATE DATETIME
	,TDATE DATETIME
	,TOTALDAYS FLOAT
	,ACTUALDAYS FLOAT
	,Days FLOAT
	,DAYSASON FLOAT
	,VACDAYS FLOAT
	,VACSTARTDATE NVARCHAR(MAX)
	,VACENDDATE NVARCHAR(MAX)
	,BALANCE FLOAT
	,OPENINGBAL FLOAT
	,OPBDATE DATETIME
	)

CREATE TABLE #TVacLOP(ID INT IDENTITY(1,1),REJOIN DATETIME,FROMDATE DATETIME,TODATE DATETIME)
CREATE TABLE #TLeaveLOP(ID INT IDENTITY(1,1),LeaveID BIGINT,FROMDATE DATETIME,TODATE DATETIME)
CREATE TABLE #TVacExcessLOP(ID INT IDENTITY(1,1),REJOIN DATETIME,FROMDATE DATETIME,TODATE DATETIME,PaidDays FLOAT,ExcessDays FLOAT)

DECLARE @CNT INT,@CalcCreditFromDOJ NVARCHAR(10),@ConsiderExcessdaysasLOP NVARCHAR(10),@VacationLeaveType INT
DECLARE @LOPRD DATETIME,@LOPFD DATETIME,@LOPTD DATETIME,@TVacLOPCNT INT ,@I3 INT,@dttmp1 DATETIME,@dttmp DATETIME,@ids FLOAT, @ConsiderLOPBasedOn NVARCHAR(500)
DECLARE @TLeaveLOPCNT INT,@K3 INT,@LeaveID INT,@CurrYearLeavestaken DECIMAL(9,2),@NOOFHOLIDAYS1 INT,@WEEKLYOFFCOUNT1 INT,@EXSTAPPLIEDENCASHDAYS DECIMAL(9,2),@STR NVARCHAR(MAX)
DECLARE @LOPEXRD DATETIME,@LOPEXFD DATETIME,@LOPEXTD DATETIME,@TVacEXLOPCNT INT ,@L INT,@EXPAIDDAYS FLOAT,@EXEXCESSDAYS FLOAT,@CNT3 INT,@Y INT,@LDAYS FLOAT

SELECT @ConsiderLOPBasedOn=ISNULL(Value,'') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='ConsiderLOPBasedOn'

SET @STARTDATE = @FromDate
SET @ENDDATE = @ToDate

SELECT @DonotshownegitiveOPvacationdays=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='DonotshownegitiveOPvacationdays'

DECLARE @GrWiseVac BIT
SELECT @GrWiseVac=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='GradeWiseVacation'
--select @GrWiseVac

DECLARE @S1 NVARCHAR(MAX)
SET @S1=''

SET @S1='
SELECT C51.NODEID,C51.CODE,C51.NAME,CASE WHEN convert(DATETIME, OPLeavesAsOn) <> ''01 Jan 1900'' THEN convert(DATETIME, OPLeavesAsOn) ELSE CONVERT(DATETIME, C51.DOJ) END
	,CC.CCNID53
	,DATEDIFF(D, CONVERT(DATETIME, C51.DOJ), CONVERT(DATETIME, '''+CONVERT(NVARCHAR,@STARTDATE,106)+'''))
	,DATEDIFF(MONTH, CONVERT(DATETIME, CASE 
				WHEN convert(DATETIME, OPLeavesAsOn) <> ''01 Jan 1900''
					THEN convert(DATETIME, OPLeavesAsOn)
				ELSE CONVERT(DATETIME, C51.DOJ)
				END),CASE WHEN ISNULL(DORELIEVE,'''')<>'''' AND  CONVERT(DATETIME,DORELIEVE)< CONVERT(DATETIME, '''+CONVERT(NVARCHAR,@ENDDATE,106)+''') THEN CONVERT(DATETIME,DORELIEVE) ELSE CONVERT(DATETIME, '''+CONVERT(NVARCHAR,@ENDDATE,106)+''') END )
	,0 
	,ISNULL(C51.OpVacationDays, 0)
	,convert(DATETIME, OPLeavesAsOn)
	,CONVERT(DATETIME, C51.DOJ)
	,C51.VACDAYSPERIOD
	,C51.VACDAYSPERMONTH,C51.DORELIEVE
FROM COM_CC50051 C51 WITH (NOLOCK)
	,COM_CCCCDATA CC WITH (NOLOCK)
WHERE CC.NODEID = C51.NODEID
	AND CC.COSTCENTERID = 50051
	AND C51.IsGroup=0 AND C51.NODEID > 2 '

IF(LEN(@EmpWhere)>0)
SET @S1=@S1 +' AND C51.NodeID IN(' +@EmpWhere+') '

IF(LEN(@CCWhere)>0)
SET @S1=@S1 +@CCWhere

print @S1

INSERT INTO @TAB
EXEC sp_executesql @S1

--SELECT * FROM @TAB

 --AND C51.NODEID IN (10)
-- AND CC.CCNID2 IN (5)


SET @STRVACDAYS1 = 0
SET @I = 1

SELECT @TRC = COUNT(*)
FROM @TAB

--VMDD
	DECLARE @VacMgmtDocID INT, @IsDefineDaysExists BIT
	CREATE TABLE #VMDD(FromMonth INT,ToMonth INT,DaysPerMonth FLOAT,ApplyToPrevMonths NVARCHAR(50))
	CREATE TABLE #VacMonthWiseAllotedDays(ID INT Identity(1,1),VacMonth DateTime,AllotedDays FLOAT,Yearly FLOAT)
--VMDD

-- ALL EMPLOYEES VACATIAON DATA
SELECT a.InvDocDetailsID,a.DocSeqNo, b.dcCCNID51 as EmpSeqNo,
CASE WHEN d.dcAlpha1 IS NOT NULL AND ISDATE(d.dcAlpha1)=1   THEN CONVERT(DATETIME,d.dcAlpha1) ELSE NULL END as ReJoinDate,
CASE WHEN ISDATE(d.dcAlpha2) = 1 THEN CONVERT(DATETIME,d.dcAlpha2) ELSE NULL END as FromDate,
CASE WHEN ISDATE(d.dcAlpha3) = 1 THEN CONVERT(DATETIME,d.dcAlpha3) ELSE NULL END as ToDate,
CASE WHEN  d.dcAlpha4 iS NOT NULL AND ISNUMERIC( d.dcAlpha4)=1 THEN ISNULL(CONVERT(FLOAT, d.dcAlpha4), 0) ELSE 0 END as NoOfDays,
ISNULL(CONVERT(FLOAT, d.dcAlpha11), 0) as ExcessDays,ISNULL(CONVERT(FLOAT, d.dcAlpha14), 0) as EncashDays
INTO #ALLEMPVACDATA

	FROM INV_DocDetails a WITH (NOLOCK)
	JOIN COM_DocCCData b WITH (NOLOCK) ON b.INVDOCDETAILSID = a.INVDOCDETAILSID
	JOIN COM_DocTextData d WITH (NOLOCK) ON d.INVDOCDETAILSID = a.INVDOCDETAILSID
	WHERE d.tCostCenterID = 40072 AND a.StatusID = 369 AND DocSeqNo=1
		AND b.dcCCNID51 IN (SELECT NODEID FROM @TAB )
		AND LEN(d.dcAlpha2) = 11
		AND LEN(d.dcAlpha3) = 11
		AND ISDATE(d.dcAlpha2) = 1
		AND ISDATE(d.dcAlpha3) = 1
		AND ISNUMERIC(d.dcAlpha4) = 1
		AND ISNUMERIC(d.dcAlpha11) = 1
	ORDER BY CONVERT(DATETIME, d.dcAlpha2)
-- ALL VACATAION MANAGEMENT DATA
SELECT a.InvDocDetailsID,a.DocSeqNo,a.DocID, b.dcCCNID53 as GradeSeqNo,
ISNULL(d.DCALPHA3, '0') as dcAlpha3,ISNULL(d.DCALPHA4, '0') as dcAlpha4,
ISNULL(d.DCALPHA8,'NO') as dcAlpha8 ,ISNULL(d.DCALPHA9,'NO') as dcAlpha9 ,ISNULL(d.dcAlpha15,'NO') as dcAlpha15 ,ISNULL(d.DCALPHA18,'1') as dcAlpha18,C52.Name VacFieldName,ISNULL(d.dcAlpha23,'No') dcAlpha23 ,dcAlpha1
INTO #ALLVACMGTDATA

	FROM INV_DocDetails a WITH (NOLOCK)
	JOIN COM_DocCCData b WITH (NOLOCK) ON b.INVDOCDETAILSID = a.INVDOCDETAILSID
	JOIN COM_DocTextData d WITH (NOLOCK) ON d.INVDOCDETAILSID = a.INVDOCDETAILSID
	JOIN COM_CC50052 C52 WITH(NOLOCK) ON C52.NodeID=CONVERT(BIGINT,d.dcAlpha1)
	WHERE d.tCostCenterID=40061 AND DocSeqNo=1 AND A.StatusID=369
	

--ALL EMPS MONTHLY PAYROLL DATA
SELECT dcCCNID51 as EmpSeqNo,CONVERT(FLOAT,TD.DCALPHA9) DCALPHA9,CONVERT(DATETIME,ID.DUEDATE) DUEDATE
INTO #ALLEMPMONDATA
FROM INV_DOCDETAILS ID WITH (NOLOCK)
JOIN COM_DOCTEXTDATA TD WITH (NOLOCK) ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID 
Join com_DocccData cc WITH (NOLOCK) on cc.invDocdetailsid=ID.invDocdetailsid
Where TD.tCostcenterID=40054 and cc.dcCCNID51 IN (SELECT NODEID FROM @TAB) 
AND ISNUMERIC(TD.DCALPHA9)=1

--ALL EMPS FSENCASH DAYS
SELECT CC.dcCCNID51 as EmpSeqNo,ISNULL(CONVERT(FLOAT, t.dcAlpha15), 0) FSEncashDays,CONVERT(DATETIME,dcAlpha3) ResgDate 
INTO #ALLEMPFSENCASHDATA
FROM INV_DocDetails I WITH(NOLOCK)
JOIN COM_DocCCData CC WITH(NOLOCK) ON CC.InvDocDetailsID=I.InvDocDetailsID
JOIN COM_DocTextData T WITH(NOLOCK) ON T.InvDocDetailsID=I.InvDocDetailsID
JOIN COM_DocNumData N WITH(NOLOCK) ON N.InvDocDetailsID=I.InvDocDetailsID
JOIN COM_CC50052 C52 WITH(NOLOCK) ON C52.Name=dcAlpha12 AND C52.Name IN (SELECT TOP 1 VacFieldName FROM #ALLVACMGTDATA WITH(NOLOCK))
WHERE T.tCostCenterID=40095 AND dcAlpha1='2' AND dcAlpha10='Partial' AND ISDATE(dcAlpha3)=1 and cc.dcCCNID51 IN (SELECT NODEID FROM @TAB)




Declare @VCnt INT
SET @VCnt=0

WHILE (@I <= @TRC)
BEGIN
	SET @STRVACDAYS = 0
	SET @STRVACDAYS1 = 0
	SET @VT=0
	SET @VacationMonthsDiff = 0
	SET @VACDAYSPERIOD = ''
	SET @VACDAYSPERMONTH = 0

	SELECT @NODEID = NODEID
		,@EMPNAME = EMPNAME
		,@EMPCODE = EMPCODE
		,@GRADE = CASE WHEN @GrWiseVac=1 THEN GRADE ELSE 1 END
		,@VACDAYSPERIOD = VACDAYSPERIOD
		,@VACDAYSPERMONTH = VACDAYSPERMONTH
		,@VacationMonthsDiff = MONTHDIFF
		,@DOJ = DOJ
		,@DOJ1 = DOJ1
		,@OPENINGBAL = OPENINGBAL
		,@LASON = LEAVEASONDATE
		,@DORELIEVE=DORELIEVE
	FROM @TAB
	WHERE ID = @I

	--VMDD
	SET @VacMgmtDocID=0 

	TRUNCATE TABLE #VMDD
	TRUNCATE TABLE #VacMonthWiseAllotedDays
	--VMDD


	SELECT @ConsiderLOPwhilecalculatingcreditdays=DCALPHA8,@Calculatevacdayforvacationperiod=DCALPHA9,@ExcessDaysAsLOP=dcAlpha15,
	@VacMgmtDocID=DocID ,@CreditDaysCalculation=DCALPHA18,@CalcCreditFromDOJ=DCALPHA23,@VacationLeaveType=isnull(dcAlpha1,0)
	FROM #ALLVACMGTDATA  WITH (NOLOCK)
	WHERE GradeSeqNo = ( CASE WHEN @GrWiseVac=1 THEN  (SELECT GRADE FROM @TAB WHERE NODEID=@NODEID) ELSE 1 END )

---------------------------------------------------------------------------------
--VMDD
	SET @IsDefineDaysExists=0
	IF EXISTS (SELECT SeqNo FROM PAY_VacManageDefineDays WITH(NOLOCK) WHERE VMDocID=@VacMgmtDocID)
	BEGIN
		SET @IsDefineDaysExists=1
		INSERT INTO #VMDD
		SELECT FromMonth,ToMonth,DaysPerMonth,ApplyToPrevMonths 
		FROM PAY_VacManageDefineDays WITH(NOLOCK) WHERE VMDocID=@VacMgmtDocID

		declare @dtt1 datetime,@dtt2 datetime,@TotMon INT,@AllotedDays FLOAT,@MNo INT,@APM NVARCHAR(50),@YearlyVD FLOAT
		set @dtt1=dateadd(day,-datepart(day,@DOJ1)+1,@DOJ1)
		set @dtt2=dateadd(day,-datepart(day,@ENDDATE)+1,@ENDDATE)
		set @dtt2=DATEADD(year,1,@dtt2) -- adding extra 1 year to know the yearly vacation days
		SET @MNo=0
		WHILE(@dtt1<=@dtt2)
		BEGIN
			SET @MNo=@MNo+1
			
			SELECT @AllotedDays=DaysPerMonth,@APM=ApplyToPrevMonths FROM #VMDD WHERE @MNo BETWEEN FromMonth AND ToMonth
			INSERT INTO #VacMonthWiseAllotedDays
			SELECT @dtt1,@AllotedDays,-1

			IF(@APM='Yes')
				UPDATE #VacMonthWiseAllotedDays SET AllotedDays=@AllotedDays

			IF(@MNo%12)=0
			BEGIN
				SELECT @YearlyVD=SUM(AllotedDays) FROM #VacMonthWiseAllotedDays WHERE Yearly=-1
				
				IF(@APM='Yes')
					UPDATE #VacMonthWiseAllotedDays SET Yearly=@YearlyVD
				ELSE
					UPDATE #VacMonthWiseAllotedDays SET Yearly=@YearlyVD WHERE Yearly=-1

			END

		 SET @dtt1=DATEADD(month,1,@dtt1)
		END

	END
	--SELECT * FROM #VacMonthWiseAllotedDays
--VMDD
---------------------------------------------------------------------------------

	INSERT INTO @MonthDays
	VALUES (
		@NODEID
		,@EMPCODE
		,'Opening'
		,NULL
		,NULL
		,NULL
		,0
		,0
		,0
		,0
		,0
		,''
		,''
		,0
		,0
		,@LASON
		)



	SET @RC1 = 0

	WHILE (@RC1 <= @VacationMonthsDiff)
	BEGIN
		IF (@RC1 = 0)
		BEGIN
			SET @MONT1 = DATEADD(MONTH, @RC1, @DOJ)
			SET @MONT2 = DATEADD(D, 0, DATEADD(D, - 1, DATEADD(MM, DATEDIFF(M, 0, @DOJ) + 1, 0)))
		END
		ELSE IF (@RC1 = @VacationMonthsDiff)
		BEGIN
			SET @MONT1 = DATEADD(MONTH, @RC1, DATEADD(M, DATEDIFF(M, 0, @DOJ), 0))
			SET @MONT2 = DATEADD(D, - 1, DATEADD(MM, DATEDIFF(M, 0, @MONT1) + 1, 0))
		END
		ELSE
		BEGIN
			SET @MONT1 = DATEADD(MONTH, @RC1, DATEADD(M, DATEDIFF(M, 0, @DOJ), 0))
			SET @MONT2 = DATEADD(D, - 1, DATEADD(MM, DATEDIFF(M, 0, @MONT1) + 1, 0))
		END

		IF(ISNULL(@DORELIEVE,'')<>'')
		BEGIN
			IF(CONVERT(DATETIME,@DORELIEVE)<@MONT2)
				SET @MONT2=CONVERT(DATETIME,@DORELIEVE)

		END

		INSERT INTO @MonthDays
		VALUES (
			@NODEID
			,@EMPCODE
			,@EMPNAME
			,@DOJ1
			,@MONT1
			,@MONT2
			,DATEDIFF(D, DATEADD(MONTH, 0, DATEADD(M, DATEDIFF(M, 0, @MONT1), 0)), DATEADD(D, - 1, DATEADD(MM, DATEDIFF(M, 0, @MONT2) + 1, 0))) + 1
			,DATEDIFF(D, @MONT1, @MONT2) + 1
			,0
			,CASE 
				WHEN DATEADD(M, 6, CONVERT(DATETIME, @DOJ1)) > CONVERT(DATETIME, @ENDDATE)
					THEN ISNULL((
									SELECT DCALPHA3 FROM #ALLVACMGTDATA WHERE GradeSeqNo=@GRADE
								), 0)
				WHEN DATEADD(M, 12, CONVERT(DATETIME, @DOJ1)) > CONVERT(DATETIME, @ENDDATE)
					THEN ISNULL((
								SELECT DCALPHA4 FROM #ALLVACMGTDATA WHERE GradeSeqNo=@GRADE
								), '0')
				ELSE (
						CASE @VACDAYSPERIOD
							WHEN 'Yearly'
								THEN ROUND((CAST(@VACDAYSPERMONTH AS FLOAT) / CAST (12 AS FLOAT)),2,1)
							ELSE @VACDAYSPERMONTH
							END
						)
				END
			,0
			,''
			,''
			,0
			,0
			,NULL
			)

--VMDD
IF(@IsDefineDaysExists=1)
BEGIN
	Update @MonthDays
	SET DAYSASON=b.AllotedDays
	FROM @MonthDays a
	JOIN #VacMonthWiseAllotedDays b ON MONTH(b.VacMonth)=MONTH(a.FDATE) AND YEAR(b.VacMonth)=YEAR(a.FDATE)
	WHERE EMPNODE=@NODEID
END

--VMDD

SET @VacTaken=0 SET @EnDays=0
SET @VCnt=0

SELECT @VCnt=EmpSeqNo FRom #ALLEMPVACDATA WITH (NOLOCK)
WHERE EmpSeqNo=@NODEID AND ( (FromDate BETWEEN @MONT1 AND @MONT2) OR 
							(ToDate BETWEEN @MONT1 AND @MONT2) OR
							(@MONT1 BETWEEN FromDate AND ToDate) OR
							(@MONT2 BETWEEN FromDate AND ToDate) 
							)
			IF(@VCnt>0)
			BEGIN
				EXEC spPAY_GetVacationLeavesInfo @MONT1
							,@MONT2
							,@NODEID
							,1
							,1
							,1,@VacTaken OUTPUT,@EnDays OUTPUT
			END
			SET @VT=@VacTaken

			IF(ISNULL(@Calculatevacdayforvacationperiod,'NO')='NO' AND @VT IS NOT NULL AND @VT>0 )
				BEGIN
					--SELECT @VT,@MONT1,@MONT2
					UPDATE @MonthDays
					SET ACTUALDAYS= CASE WHEN SUBSTRING(CONVERT(VARCHAR(12), @DOJ, 106), 4, 8)<>SUBSTRING(CONVERT(VARCHAR(12), @MONT1, 106), 4, 8) THEN TOTALDAYS-@VT ELSE ACTUALDAYS-@VT END
					WHERE EMPNODE = @NODEID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @MONT1, 106), 4, 8)
				END

		UPDATE @MONTHDAYS
		SET OPENINGBAL = @OPENINGBAL
		WHERE @LASON <> 'Jan  1 1900 12:00AM'
			AND EMPNODE = @NODEID
			AND EMPNAME = 'OPENING'

		SET @RC1 = @RC1 + 1
	END

	IF(@CreditDaysCalculation=1)
	BEGIN
		UPDATE @MonthDays
		SET Days = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
		WHERE EMPNODE = @NODEID
		AND EMPNAME <> 'OPENING'
	END
	ELSE
	BEGIN
		UPDATE @MonthDays
		SET Days = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
		WHERE EMPNODE = @NODEID
		AND EMPNAME <> 'OPENING'
	END

	SET @I = @I + 1
END

--SELECT * FROM @MonthDays

SET @K = 1

SELECT @KK = COUNT(*)
FROM @MonthDays

DECLARE CUR1 CURSOR FAST_FORWARD FOR
SELECT ID,FDATE,TDATE,EMPNODE
FROM @MONTHDAYS
OPEN CUR1
FETCH NEXT FROM CUR1 INTO @K,@FMONTH,@TMONTH,@EID
WHILE @@FETCH_STATUS=0
BEGIN

--------------------

	SET @ACVDAYS = 0
	SET @STRVACDAYS = 0
	SET @VT=0
	SET @STRFROMDATERANGE = ''
	SET @STRTODATERANGE = ''
	

	SELECT @DJ=DOJ,@DR=CONVERT(DATETIME,DORELIEVE) FROM @TAB WHERE NODEID=@EID

	SELECT @ConsiderLOPwhilecalculatingcreditdays=DCALPHA8,@Calculatevacdayforvacationperiod=DCALPHA9,@ExcessDaysAsLOP=dcAlpha15,@CreditDaysCalculation=DCALPHA18
	FROM #ALLVACMGTDATA WITH (NOLOCK)
	WHERE GradeSeqNo = (CASE WHEN @GrWiseVac=1 THEN ( SELECT GRADE FROM @TAB WHERE NODEID=@EID) ELSE 1 END )

	SET @LOPDAYS=0

	IF(@ConsiderLOPwhilecalculatingcreditdays='Yes')
	BEGIN

		SET @CNT=0

		SELECT @CNT=COUNT(EmpSeqNo) 
		FROM #ALLEMPMONDATA WITH (NOLOCK)
		Where EmpSeqNo=@EID AND CONVERT(DATETIME,DUEDATE) BETWEEN 	@FMONTH AND @TMONTH

		IF(@CNT>0)-- CHECKING FROM MONTHLY PAYROLL
		BEGIN
			SELECT @LOPDAYS=CONVERT(FLOAT,DCALPHA9) 
			FROM #ALLEMPMONDATA WITH (NOLOCK)
			Where EmpSeqNo=@EID AND CONVERT(DATETIME,DUEDATE) BETWEEN 	@FMONTH AND @TMONTH
		END
		ELSE IF(@CalcCreditFromDOJ='Yes')--START-CHECKING FROM VACATION LATE REJOIN AND LOP LEAVE 
		BEGIN

			--START--VACATION LATE REJOIN LOP
			TRUNCATE TABLE #TVacLOP
			INSERT INTO #TVacLOP
			SELECT DISTINCT CONVERT(DATETIME,D.DCALPHA1),CONVERT(DATETIME,D.DCALPHA2),CONVERT(DATETIME,D.DCALPHA3)
			FROM INV_DocDetails a WITH(NOLOCK) 
			JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
			JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
			WHERE d.tCostCenterID=40072 and a.StatusID=369  AND b.dcCCNID51=@EID
			AND ISNULL(D.DCALPHA1,'')<>'' AND CONVERT(DATETIME,D.DCALPHA1)>DATEADD(D,1,CONVERT(DATETIME,D.dcAlpha3))
			AND ( @FMONTH BETWEEN CONVERT(DATETIME,d.dcAlpha2) AND CONVERT(DATETIME,d.dcAlpha3) OR 
					@TMONTH BETWEEN CONVERT(DATETIME,d.dcAlpha2) AND CONVERT(DATETIME,d.dcAlpha3) OR 
					CONVERT(DATETIME,d.dcAlpha2) BETWEEN  @FMONTH AND  @TMONTH OR 
					CONVERT(DATETIME,d.dcAlpha3) BETWEEN  @FMONTH AND  @TMONTH )
					
			 
			SELECT @TVacLOPCNT=COUNT(*) FROM #TVacLOP WITH (NOLOCK)
			SET @I3=1
			WHILE(@I3<=@TVacLOPCNT)
			BEGIN
				SELECT @LOPRD=REJOIN,@LOPFD=FROMDATE,@LOPTD=TODATE FROM #TVacLOP WITH (NOLOCK) WHERE ID=@I3
				SET @ids=0

				if (@LOPRD >= @FMONTH)
                BEGIN
                    if (@LOPTD >= @FMONTH AND @LOPTD <= @TMONTH)
                        SET @dttmp = DATEADD(D,1,@LOPTD)
                    else
                        SET @dttmp = @FMONTH;

                    if (@LOPRD >= @FMONTH AND @LOPRD <= @TMONTH)
                        SET @dttmp1 = @LOPRD;
                    else
                        SET @dttmp1 = DATEADD(D,1,@TMONTH)

                    if (@LOPTD < @dttmp1)
                    BEGIN
                        while (@dttmp < @dttmp1)
                        BEGIN
                            SET @ids=@ids+1
                            SET @dttmp = DATEADD(D,1,@dttmp)
                        END
                    END
                END
					
				SET @LOPDAYS=@LOPDAYS+@ids
				SET @I3=@I3+1
			END
			--END--VACATION LATE REJOIN LOP

			--START--LOP LEAVES 	
			IF(ISNULL(@ConsiderLOPBasedOn,'')<>'')
			BEGIN
				TRUNCATE TABLE #TLeaveLOP
					
				SET @STR='INSERT INTO #TLeaveLOP	
				SELECT b.dcCCNID52,CONVERT(DATETIME,d.dcAlpha4),CONVERT(DATETIME,d.dcAlpha5)
				FROM INV_DocDetails a WITH(NOLOCK) 
				JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
				JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
				WHERE d.tDocumentType=62 and a.StatusID=369  AND b.dcCCNID51='+CONVERT(Varchar,@EID)+' AND b.dcCCNID52 IN ('+@ConsiderLOPBasedOn+')
				AND ( '''+CONVERT(Varchar,@FMONTH)+''' BETWEEN CONVERT(DATETIME,d.dcAlpha4) AND CONVERT(DATETIME,d.dcAlpha5) OR 
						'''+CONVERT(Varchar,@TMONTH)+''' BETWEEN CONVERT(DATETIME,d.dcAlpha4) AND CONVERT(DATETIME,d.dcAlpha5) OR 
						CONVERT(DATETIME,d.dcAlpha4) BETWEEN  '''+CONVERT(Varchar,@FMONTH)+''' AND  '''+CONVERT(Varchar,@TMONTH)+''' OR 
						CONVERT(DATETIME,d.dcAlpha5) BETWEEN  '''+CONVERT(Varchar,@FMONTH)+''' AND  '''+CONVERT(Varchar,@TMONTH)+''' )'
				--PRINT @STR
				EXEC sp_executesql @STR

					
				SELECT @TLeaveLOPCNT=COUNT(*) FROM #TLeaveLOP WITH (NOLOCK)
				SET @K3=1
				WHILE(@K3<=@TLeaveLOPCNT)
				BEGIN
					SELECT @LeaveID=LeaveID FROM #TLeaveLOP WITH (NOLOCK) WHERE ID=@K3
					SET @CurrYearLeavestaken=0
					EXEC spPAY_GetCurrYearLeavesInfo @FMONTH,@TMONTH,@EID,@LeaveID,1,1,@MONT1,0,@CurrYearLeavestaken OUTPUT,@NOOFHOLIDAYS1 OUTPUT,@WEEKLYOFFCOUNT1 OUTPUT,@EXSTAPPLIEDENCASHDAYS OUTPUT

					
				SET @LOPDAYS=@LOPDAYS+@CurrYearLeavestaken
				SET @K3=@K3+1
				END
			END
			--END--LOP LEAVES

			--START--EXCESS DAYS AS LOP
			IF(@ExcessDaysAsLOP='Yes')
			BEGIN
				TRUNCATE TABLE #TVacExcessLOP
				INSERT INTO #TVacExcessLOP	
				SELECT DISTINCT CONVERT(DATETIME,D.DCALPHA1),CONVERT(DATETIME,D.DCALPHA2),CONVERT(DATETIME,D.DCALPHA3),CONVERT(FLOAT,d.dcAlpha10),CONVERT(FLOAT,d.dcAlpha11)
				FROM INV_DocDetails a WITH(NOLOCK) 
				JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
				JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
				WHERE d.tCostCenterID=40072 and a.StatusID=369  AND b.dcCCNID51=@EID AND CONVERT(FLOAT,ISNULL(d.dcAlpha11,0))>0
				AND ( @FMONTH BETWEEN CONVERT(DATETIME,d.dcAlpha2) AND CONVERT(DATETIME,d.dcAlpha3) OR 
						@TMONTH BETWEEN CONVERT(DATETIME,d.dcAlpha2) AND CONVERT(DATETIME,d.dcAlpha3) OR 
						CONVERT(DATETIME,d.dcAlpha2) BETWEEN  @FMONTH AND  @TMONTH OR 
						CONVERT(DATETIME,d.dcAlpha3) BETWEEN  @FMONTH AND  @TMONTH )

					
				
				SELECT @TVacEXLOPCNT=COUNT(*) FROM #TVacExcessLOP WITH (NOLOCK)
				SET @L=1

				WHILE(@L<=@TVacEXLOPCNT)
				BEGIN
					SELECT @LOPEXRD=REJOIN,@LOPEXFD=FROMDATE,@LOPEXTD=TODATE,@EXPAIDDAYS=PaidDays,@EXEXCESSDAYS=ExcessDays FROM #TVacExcessLOP WITH (NOLOCK) WHERE ID=@L	

					IF(@LOPEXFD>=@FMONTH AND @LOPEXTD<=@TMONTH)
					BEGIN
						SET @LOPDAYS=@LOPDAYS+@EXEXCESSDAYS
					END
					ELSE
					BEGIN
						
						
					DECLARE @VACDatesRange TABLE (SNO INT IDENTITY(1,1),ID INT ,DATE1 DATETIME,DAYNAME VARCHAR(50),WEEKNO INT,COUNT INT,NOOFDAYS Float,FLAG INT,IncExc varchar(5),ExcessDays INT)
					Declare @WEEKOFFCOUNT1 Table (ID INT ,WEEKDATE DateTime,DAYNAME Varchar(50),WEEKNO Int,COUNT Int,WEEKNOMANUAL Int)

				;WITH DATERANGE1 AS
				(
				SELECT @LOPEXFD AS DT,1 AS ID
				UNION ALL
				SELECT DATEADD(DD,1,DT),DATERANGE1.ID+1 FROM DATERANGE1 WHERE ID<=DATEDIFF("d",convert(varchar,@LOPEXFD,101),convert(varchar,@LOPEXTD,101))
				)
		
				INSERT INTO @VACDatesRange
				SELECT ROW_NUMBER() OVER (ORDER BY DT) AS ID,DT AS WEEKDATE,DATENAME(DW,DT) AS DAY,0,1,0,1,'',1 FROM DATERANGE1
			
				--START WEEKOFF AND HOLIDAY UPDATEING IN @VACDatesRange
				INSERT INTO @WEEKOFFCOUNT1
				EXEC spPAY_GetVacationWeekoff @LOPEXFD,@LOPEXTD,@EID,0,1,1

				--select * from @WEEKOFFCOUNT1
				UPDATE DATESCOUNT SET DATESCOUNT.count=3 FROM @WEEKOFFCOUNT1 WEEKOFFCOUNT inner join @VACDatesRange DATESCOUNT on CONVERT(DateTime,DATESCOUNT.date1)= CONVERT(DateTime,WEEKOFFCOUNT.weekdate) and WEEKOFFCOUNT.count=1
			
				--START-- HOLIDAY COUNT
					Declare @HOLIDAYCOUNT1 Table (ID int Identity(1,1),WEEKDATE Nvarchar(max),Remarks nvarchar(max))
					INSERT INTO @HOLIDAYCOUNT1
					EXEC spPAY_GetVacationWeekoff @LOPEXFD,@LOPEXTD,@EID,1,1,1
				--END -- HOLIDAY COUNT

				--START : UPDATING @DATESAPPLIEDCOUNT Table 'COUNT' COLUMN TO  '4- FOR HOLIDAY'
					UPDATE DATESCOUNT SET DATESCOUNT.count=4 FROM @VACDatesRange DATESCOUNT 
					inner join @HOLIDAYCOUNT1 TD on CONVERT(DATETIME,DATESCOUNT.DATE1)=CONVERT(DATETIME,TD.WEEKDATE)
				--END : UPDATING @DATESAPPLIEDCOUNT Table 'COUNT' COLUMN TO  '4- FOR HOLIDAY'
				--END WEEKOFF AND HOLIDAY UPDATEING IN @VACDatesRange
				Declare @IC  Int,@DTT  DateTime,@INCREXC VARCHAR(50)

				SELECT @INCREXC=ISNULL(INCLUDEREXCLUDE,'') FROM COM_CC50054 WITH(NOLOCK) WHERE GRADEID=@Grade AND COMPONENTID=@VacationLeaveType AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@FMONTH) AND GradeID=@Grade)

				SET @IC=1
				SELECT @TRC=COUNT(*) FROM @VACDatesRange
				WHILE(@IC<=@TRC)
				BEGIN

					SELECT @DTT=DATE1 FROM @VACDatesRange WHERE id=@IC

					IF ISNULL(@INCREXC,'')='IncludeHolidays' OR ISNULL(@INCREXC,'')='ExcludeWeeklyOffs'
						UPDATE @VACDatesRange SET FLAG=0,IncExc='EW',ExcessDays=0 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT)  AND COUNT=3
					ELSE IF ISNULL(@INCREXC,'')='IncludeWeeklyOffs' OR ISNULL(@INCREXC,'')='ExcludeHolidays'
						UPDATE @VACDatesRange SET FLAG=0,IncExc='EH',ExcessDays=0 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT)  AND COUNT=4
					ELSE IF ISNULL(@INCREXC,'')='IncludeBoth'
						UPDATE @VACDatesRange SET FLAG=1 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) 
					ELSE IF ISNULL(@INCREXC,'')='ExcludeBoth'
						UPDATE @VACDatesRange SET FLAG=0,IncExc='EB',ExcessDays=0 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) AND COUNT IN (3,4)

				SET @IC=@IC+1
				END
			
				SELECT @CNT3=COUNT(*) FROM @VACDatesRange
				SET @Y=1
				WHILE(@Y<=@CNT3)
				BEGIN
					IF(@EXPAIDDAYS>0 AND (SELECT COUNT(*) FROM @VACDatesRange WHERE id=@Y AND FLAG=1 AND count>=1 and isnull(IncExc,'')='' )>0)
					BEGIN
						UPDATE @VACDatesRange SET ExcessDays=0 WHERE id=@Y
						SET @EXPAIDDAYS=@EXPAIDDAYS-1
					END

				SET @Y=@Y+1
				END

				SET @LDAYS=0
				SELECT @LDAYS=COUNT(EXCESSDAYS) FROM @VACDatesRange WHERE EXCESSDAYS=1 AND DATE1 BETWEEN @FMONTH AND @TMONTH


				delete from  @VACDatesRange
				delete from @WEEKOFFCOUNT1

				SET @LOPDAYS=@LOPDAYS+@LDAYS
					END
						
				SET @L=@L+1
				END

			END

			--END--EXCESS DAYS AS LOP


		END--END-CHECKING FROM VACATION LATE REJOIN

			IF ((SUBSTRING(CONVERT(VARCHAR(12), @FMONTH, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @DJ, 106), 4, 8))
						AND
			(SUBSTRING(CONVERT(VARCHAR(12), @TMONTH, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @DR, 106), 4, 8)) )
		begin
			UPDATE @MonthDays
			SET ACTUALDAYS=ACTUALDAYS-ISNULL(@LOPDAYS,0)
			WHERE EMPNODE = @EID
			and fdate=@FMONTH and Tdate=@TMONTH
			AND ID = @K
			
			IF(@CreditDaysCalculation=1)
			BEGIN
				UPDATE @MonthDays
				SET Days = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
				--DAYSASON = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
				WHERE EMPNODE = @EID
				and fdate=@FMONTH and Tdate=@TMONTH
				AND ID = @K
			END
			ELSE
			BEGIN
				UPDATE @MonthDays
				SET Days = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
				--DAYSASON = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
				WHERE EMPNODE = @EID
				and fdate=@FMONTH and Tdate=@TMONTH
				AND ID = @K
			END
		end
		ELSE
		begin
		UPDATE @MonthDays
			SET ACTUALDAYS=ACTUALDAYS-ISNULL(@LOPDAYS,0)
			WHERE EMPNODE = @EID
			and fdate=@FMONTH and Tdate=@TMONTH
			AND ID = @K
			
			IF(@CreditDaysCalculation=1)
			BEGIN
				UPDATE @MonthDays
				SET Days = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
				--DAYSASON = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
				WHERE EMPNODE = @EID
				and fdate=@FMONTH and Tdate=@TMONTH
				AND ID = @K
			END
			ELSE
			BEGIN
				UPDATE @MonthDays
				SET Days = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
				--DAYSASON = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
				WHERE EMPNODE = @EID
				and fdate=@FMONTH and Tdate=@TMONTH
				AND ID = @K
			END
		end
	END

	SELECT @OPB = OPENINGBAL
	FROM @MonthDays
	WHERE EMPNODE = @EID
		AND ID = @K

	SELECT @ACVDAYS = BALANCE
	FROM @MonthDays
	WHERE ID = @K - 1
		AND EMPNODE = @EID

		--if(@k=16)
		--select * from @MonthDays
	--SELECT @ACVDAYS, DAYS,@OPB FROM @MonthDays
	--WHERE ID = @K 

	SELECT @ACVDAYS = ROUND((ISNULL(@ACVDAYS, 0) + DAYS + @OPB),2)
	FROM @MonthDays
	WHERE ID = @K
		AND EMPNODE = @EID

	UPDATE @MonthDays
	SET BALANCE = ROUND(@ACVDAYS, 2)
	WHERE ID = @K
	AND EMPNODE = @EID

	TRUNCATE TABLE #TABVAC

	INSERT INTO #TABVAC

	SELECT FromDate,
	CASE WHEN ISNULL(ReJoinDate,'')='' THEN ToDate WHEN ReJoinDate < ToDate THEN CONVERT(DateTime,DATEADD(D,-1,ReJoinDate)) ELSE ToDate END AS ToDate,
	CASE WHEN ISNULL(ReJoinDate,'')='' THEN NoOfDays WHEN ReJoinDate < ToDate then DATEDIFF(D,CONVERT(DATETIME, FromDate),CONVERT(DateTime,DATEADD(D,-1,ReJoinDate)))+1 else NoOfDays END AS NoOfDays
	FROM #ALLEMPVACDATA WITH (NOLOCK)
	WHERE EmpSeqNo=@EID
	AND (
			(
				FromDate BETWEEN CONVERT(DATETIME, CONVERT(NVARCHAR, @FMONTH))
					AND CONVERT(DATETIME, CONVERT(NVARCHAR, @TMONTH))
				)
			OR (
				ToDate BETWEEN CONVERT(DATETIME, CONVERT(NVARCHAR, @FMONTH))
					AND CONVERT(DATETIME, CONVERT(NVARCHAR, @TMONTH))	
				)
			OR (
				CONVERT(DATETIME, CONVERT(NVARCHAR, @FMONTH)) BETWEEN FromDate AND ToDate
				)
			OR (
				CONVERT(DATETIME, CONVERT(NVARCHAR, @TMONTH)) BETWEEN FromDate AND ToDate
				)
			)
	ORDER BY FromDate

	--select * from #TABVAC

	SELECT @RC = COUNT(*)
	FROM #TABVAC
	
	SET @J = 1

	
	DECLARE CUR2 CURSOR FAST_FORWARD FOR
	SELECT ID,FROMDATE,TODATE,vacdays
	FROM #TABVAC
	OPEN CUR2
	FETCH NEXT FROM CUR2 INTO @J,@VFD,@VTD,@VDays
	WHILE @@FETCH_STATUS=0
	BEGIN
		 
		IF (@VFD >= @FMONTH)
		BEGIN
			IF (@VTD <= @TMONTH)
			BEGIN
		
				IF (SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @VTD, 106), 4, 8))
				BEGIN
					SET @VacTaken=0 SET @EnDays=0

					EXEC spPAY_GetVacationLeavesInfo @VFD
						,@VTD
						,@EID
						,1
						,1
						,1,@VacTaken OUTPUT,@EnDays OUTPUT

						SET @STRVACDAYS=@VacTaken
				END
				ELSE
					SET @STRVACDAYS = @VDays
				
			
				IF(ISNULL(@Calculatevacdayforvacationperiod,'NO')='NO' )
				BEGIN
					SET @VT=@STRVACDAYS
					
					--UPDATE @MonthDays
					--SET ACTUALDAYS=TOTALDAYS-@VT-ISNULL(@LOPDAYS,0)
					--WHERE EMPNODE = @EID
					--AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
					--AND ID = @K

					IF(@CreditDaysCalculation=1)
					BEGIN
						UPDATE @MonthDays
						SET Days = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
						--DAYSASON = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
						WHERE EMPNODE = @EID
						AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
						AND ID = @K
					END
					ELSE
					BEGIN
						UPDATE @MonthDays
						SET Days = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
						--DAYSASON = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
						WHERE EMPNODE = @EID
						AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
						AND ID = @K
					END

					
				END

				SET @EncashDays = 0

				Select @EncashDays = SUM(EncashDays)
				From #ALLEMPVACDATA WITH (NOLOCK)
				WHERE EmpSeqNo= @EID 
				AND FromDate BETWEEN @VFD AND @VTD



				SET @STRVACDAYS = @STRVACDAYS + @EncashDays

				SELECT @STRFROMDATERANGE = ISNULL(@STRFROMDATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @VFD), 106)
					,@STRTODATERANGE = ISNULL(@STRTODATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @VTD), 106)
				FROM #TABVAC
				WHERE ID = @J

				SET @STRFROMDATERANGE = @STRFROMDATERANGE + CHAR(10)
				SET @STRTODATERANGE = @STRTODATERANGE + CHAR(10)

				UPDATE @MonthDays
				SET VACSTARTDATE = @STRFROMDATERANGE
					,VACENDDATE = @STRTODATERANGE
					,VACDAYS = isnull(VACDAYS, 0) + @STRVACDAYS
				WHERE EMPNODE = @EID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @FMONTH, 106), 4, 8)
					AND ID = @K
			END
			ELSE
			BEGIN
				IF (SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @VTD, 106), 4, 8))
				BEGIN
					SET @VacTaken=0 SET @EnDays=0
					EXEC spPAY_GetVacationLeavesInfo @VFD
						,@TMONTH
						,@EID
						,1
						,1
						,1,@VacTaken OUTPUT,@EnDays OUTPUT

						SET @STRVACDAYS=@VacTaken
				END
				ELSE
					SET @STRVACDAYS = @VDays

				SET @VT=@STRVACDAYS
				
				IF(ISNULL(@Calculatevacdayforvacationperiod,'NO')='NO')
				BEGIN
					SET @VT=@STRVACDAYS
					
					--UPDATE @MonthDays
					--SET ACTUALDAYS=TOTALDAYS-@VT-ISNULL(@LOPDAYS,0)
					--WHERE EMPNODE = @EID
					--AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
					--AND ID = @K

					IF(@CreditDaysCalculation=1)
					BEGIN
						UPDATE @MonthDays
						SET Days = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
						--DAYSASON = ROUND((( CAST(ACTUALDAYS AS FLOAT) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1)
						WHERE EMPNODE = @EID
						AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
						AND ID = @K
					END
					ELSE
					BEGIN
						UPDATE @MonthDays
						SET Days = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
						--DAYSASON = ROUND((( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ),2,1)
						WHERE EMPNODE = @EID
						AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
						AND ID = @K
					END

					
				END

				SET @EncashDays = 0

				Select @EncashDays = SUM(EncashDays)
				From #ALLEMPVACDATA WITH (NOLOCK)
				WHERE EmpSeqNo= @EID 
				AND FromDate BETWEEN @VFD AND @VTD


				SET @STRVACDAYS = @STRVACDAYS + @EncashDays


				SELECT @STRFROMDATERANGE = ISNULL(@STRFROMDATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @VFD), 106)
					,@STRTODATERANGE = ISNULL(@STRTODATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @TMONTH), 106)
				FROM #TABVAC
				WHERE ID = @J

				SET @STRFROMDATERANGE = @STRFROMDATERANGE + CHAR(10)
				SET @STRTODATERANGE = @STRTODATERANGE + CHAR(10)
				
				UPDATE @MonthDays
				SET VACSTARTDATE = @STRFROMDATERANGE
					,VACENDDATE = @STRTODATERANGE
					,VACDAYS = isnull(VACDAYS, 0) + @STRVACDAYS
				WHERE EMPNODE = @EID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8)
					AND ID = @K
			END
		END
		ELSE
		BEGIN
			IF (@VTD <= @TMONTH)
			BEGIN
				IF (SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @VTD, 106), 4, 8))
				BEGIN
					SET @VacTaken=0 SET @EnDays=0
					EXEC spPAY_GetVacationLeavesInfo @FMONTH
						,@VTD
						,@EID
						,1
						,1
						,1,@VacTaken OUTPUT,@EnDays OUTPUT

						SET @STRVACDAYS=@VacTaken
				END
				ELSE
					SET @STRVACDAYS = @VDays
				
				SET @VT=@STRVACDAYS

				SELECT @STRFROMDATERANGE = ISNULL(@STRFROMDATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @FMONTH), 106)
					,@STRTODATERANGE = ISNULL(@STRTODATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @VTD), 106)
				FROM #TABVAC
				WHERE ID = @J

				SET @STRFROMDATERANGE = @STRFROMDATERANGE + CHAR(10)
				SET @STRTODATERANGE = @STRTODATERANGE + CHAR(10)

				UPDATE @MonthDays
				SET VACSTARTDATE = @STRFROMDATERANGE
					,VACENDDATE = @STRTODATERANGE
					,VACDAYS = isnull(VACDAYS, 0) + @STRVACDAYS
				WHERE EMPNODE = @EID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @VTD, 106), 4, 8)
					AND ID = @K
			END
			ELSE
			BEGIN
			
				IF (SUBSTRING(CONVERT(VARCHAR(12), @VFD, 106), 4, 8) <> SUBSTRING(CONVERT(VARCHAR(12), @VTD, 106), 4, 8))
				BEGIN
					SET @VacTaken=0 SET @EnDays=0
					EXEC spPAY_GetVacationLeavesInfo @FMONTH
						,@TMONTH
						,@EID
						,1
						,1
						,1,@VacTaken OUTPUT,@EnDays OUTPUT

						SET @STRVACDAYS=@VacTaken
						
				END
				ELSE
					SET @STRVACDAYS = @VDays

				SET @VT=@STRVACDAYS

				SELECT @STRFROMDATERANGE = ISNULL(@STRFROMDATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @FMONTH), 106)
					,@STRTODATERANGE = ISNULL(@STRTODATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, @TMONTH), 106)
				FROM #TABVAC
				WHERE ID = @J

				SET @STRFROMDATERANGE = @STRFROMDATERANGE + CHAR(10)
				SET @STRTODATERANGE = @STRTODATERANGE + CHAR(10)

				UPDATE @MonthDays
				SET VACSTARTDATE = @STRFROMDATERANGE
					,VACENDDATE = @STRTODATERANGE
					,VACDAYS = isnull(VACDAYS, 0) + @STRVACDAYS
				WHERE EMPNODE = @EID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @FMONTH, 106), 4, 8)
					AND ID = @K
			END
		END
		
		FETCH NEXT FROM CUR2 INTO @J,@VFD,@VTD,@VDays
	END
	CLOSE CUR2
	DEALLOCATE CUR2
	
	--START-- FINAL SETTLEMENT ENCASH DAYS
		SET @FSENCASHDAYS=0
				SELECT @FSENCASHDAYS=ISNULL(SUM(FSEncashDays),0) 
				FROM #ALLEMPFSENCASHDATA WITH (NOLOCK)
				WHERE EmpSeqNo= @EID 
				AND ResgDate BETWEEN @FMONTH AND @TMONTH

				SELECT @STRFROMDATERANGE = ISNULL(@STRFROMDATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, ResgDate), 106)
					,@STRTODATERANGE = ISNULL(@STRTODATERANGE, '') + CONVERT(NVARCHAR, CONVERT(DATETIME, ResgDate), 106)
					FROM #ALLEMPFSENCASHDATA WITH (NOLOCK)
					WHERE EmpSeqNo= @EID 
					AND ResgDate BETWEEN @FMONTH AND @TMONTH

				SET @STRFROMDATERANGE = @STRFROMDATERANGE + CHAR(10)
				SET @STRTODATERANGE = @STRTODATERANGE + CHAR(10)
				

				UPDATE @MonthDays
				SET VACSTARTDATE = @STRFROMDATERANGE
					,VACENDDATE = @STRTODATERANGE 
					,VACDAYS = isnull(VACDAYS, 0) + @FSENCASHDAYS
					WHERE EMPNODE = @EID
					AND SUBSTRING(CONVERT(VARCHAR(12), FDATE, 106), 4, 8) = SUBSTRING(CONVERT(VARCHAR(12), @FMONTH, 106), 4, 8)
					AND ID = @K
	--END-- FINAL SETTLEMENT ENCASH DAYS


	--if(@k=44)
	--SELECT @ACVDAYS,VACDAYS FROM @MonthDays WHERE ID = @K

	select @FDate=FDate,@TDate=TDate,@BDays=(BALANCE - VACDAYS) FROM @MonthDays WHERE ID = @K AND EMPNODE = @EID
	

IF( @DonotshownegitiveOPvacationdays='True' AND EXISTS (
	Select ExcessDays FROM #ALLEMPVACDATA WITH (NOLOCK) WHERE EmpSeqNo=@EID AND ToDate BETWEEN @FDate AND @TDate AND ExcessDays>0 AND @BDays<0 ) )

	BEGIN
				declare @RDays FLOAT
		SET @RDays=0
		IF(@VTD<@TDate)
			SELECT @RDays= ROUND((( ((CAST(TOTALDAYS AS FLOAT)-CAST(DATEPART(d,@VTD) AS FLOAT))) * CAST(DAYSASON AS FLOAT) ) / CAST(TOTALDAYS AS FLOAT)),2,1) FROM @MonthDays  WHERE ID = @K
			AND VACENDDATE<>''

		UPDATE @MonthDays
		SET BALANCE = @RDays
		WHERE ID = @K
		AND EMPNODE = @EID
	END
	ELSE
	BEGIN
		UPDATE @MonthDays
		SET BALANCE = (BALANCE - VACDAYS)
		WHERE ID = @K
		AND EMPNODE = @EID
	END

	
-----------------

FETCH NEXT FROM CUR1 INTO @K,@FMONTH,@TMONTH,@EID
END
CLOSE CUR1
DEALLOCATE CUR1
	
UPDATE T
SET T.OPENINGBAL = T.OPENINGBAL + (T1.DAYS)
	,T.BALANCE = T.BALANCE + T1.DAYS
FROM @MonthDays T1
	,@MonthDays T
WHERE T.EMPNODE = T1.EMPNODE
	AND T1.FDATE = T.OPBDATE
	AND T1.FDATE < @STARTDATE


UPDATE T
SET T.DAYS = T.DAYS + (
		SELECT SUM(DAYS)
		FROM @MONTHDAYS T1
		WHERE T1.EMPNAME <> 'OPENING'
			AND T1.EMPNODE = T.EMPNODE
			AND T1.FDATE < @STARTDATE
			AND T1.FDATE <> isnull(T.OPBDATE,0)
		)
	,T.BALANCE = T.BALANCE + (
		SELECT SUM(DAYS)
		FROM @MONTHDAYS T1
		WHERE T1.EMPNAME <> 'OPENING'
			AND T1.EMPNODE = T.EMPNODE
			AND T1.FDATE < @STARTDATE
			AND T1.FDATE <> isnull(T.OPBDATE,0)
		)
FROM @MONTHDAYS T
WHERE T.EMPNAME = 'OPENING'


UPDATE T
SET T.DAYS = T.DAYS - (
		SELECT SUM(VACDAYS)
		FROM @MONTHDAYS T1
		WHERE T1.EMPNAME <> 'OPENING'
			AND T1.EMPNODE = T.EMPNODE
			AND T1.FDATE < @STARTDATE
			AND T1.FDATE <> isnull(T.OPBDATE,0)
		)
	,T.BALANCE = T.BALANCE - (
		SELECT SUM(VACDAYS)
		FROM @MONTHDAYS T1
		WHERE T1.EMPNAME <> 'OPENING'
			AND T1.EMPNODE = T.EMPNODE
			AND T1.FDATE < @STARTDATE
			AND T1.FDATE <> isnull(T.OPBDATE,0)
		)
FROM @MONTHDAYS T
WHERE T.EMPNAME = 'OPENING'



UPDATE @MonthDays
SET Days = isnull(Days, 0) + OPENINGBAL
	,Balance = isnull(Days, 0) + OPENINGBAL
FROM @MonthDays
WHERE EMPNAME = 'OPENING'

SELECT *
FROM @MonthDays
WHERE EMPNAME = 'OPENING'

UNION

SELECT *
FROM @MonthDays
WHERE EMPNAME <> 'OPENING'
	AND FDATE >= @STARTDATE

DROP TABLE #TABVAC

DROP TABLE #VMDD
DROP TABLE #VacMonthWiseAllotedDays

DROP TABLE #ALLEMPVACDATA
DROP TABLE #ALLVACMGTDATA
DROP TABLE #ALLEMPMONDATA
DROP TABLE #ALLEMPFSENCASHDATA


SET NOCOUNT OFF

----spPAY_RptGetVacationLedger 
-- '928'
-- ,'01 Apr 2000'
-- ,'30 Apr 2023'
-- ,''
GO
