USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetDimensionDetails]
	@EmpIDs [nvarchar](max),
	@CostCenterID [int],
	@PayrollMonth [datetime] = '01-sep-2017',
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @DaysDiff INT, @strQry NVARCHAR(max),@strColumns NVARCHAR(max),@strSelect NVARCHAR(max),@strSelectCols NVARCHAR(max),@strQry1 NVARCHAR(max)
DECLARE @R INT,@TR INT,@DIMNAME NVARCHAR(100),@DIMNAME1 NVARCHAR(100),@strSelect1 NVARCHAR(max),@strFilter NVARCHAR(max),@strWhere NVARCHAR(max)

DECLARE @TABEMPDIMENSIONS TABLE(ID INT IDENTITY(1,1),USERDIMENSIONNAME NVARCHAR(100),SYSDIMENSIONNAME NVARCHAR(100),COSTCENTERID INT,MAPSYSDIMENSIONNAME NVARCHAR(100),CONTROLTYPE NVARCHAR(5))

CREATE TABLE #TEMPEMP(EMPSEQNO INT,EMPCODE NVARCHAR(500),EMPNAME NVARCHAR(500),DOJ DATETIME,DORELIEVE DATETIME,LFT INT)

	--INSERTING EMPLOYEE DIMENSIONS AND OTHER DIMENSIONS IN TABLES
	INSERT INTO @TABEMPDIMENSIONS 
		   SELECT USERCOLUMNNAME,SYSCOLUMNNAME,50051,'dc'+SYSCOLUMNNAME,ISNULL(UserProbableValues,'') FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=50051 AND IsColumnInUse=1 AND SYSCOLUMNNAME LIKE 'CCNID%' AND USERCOLUMNNAME NOT LIKE 'CCNID%'    

	SET @strQry=''
	SET @strColumns=''
	SET @strSelectCols=''
	SET @strSelect=''
	SET @strSelect1=''
	SET @strQry1=''
	set @strFilter=''
	set @strWhere=''
	--CREATING TEMP TABLE FOR EMPLOYEE
	SET @R=1
  	SELECT @TR=COUNT(*) FROM  @TABEMPDIMENSIONS  
	WHILE (@R<=@TR)
	BEGIN	
		SELECT @DIMNAME=REPLACE(SYSDIMENSIONNAME,'','') FROM @TABEMPDIMENSIONS WHERE ID=@R
		PRINT @DIMNAME
	    SET @strSelect=@strSelect+','+convert(NVARCHAR,@DIMNAME)
	    
	    SET @DIMNAME1=@DIMNAME
	    SET @DIMNAME1='DC'+@DIMNAME1
        SET @strQry='ALTER TABLE #TEMPEMP ADD '+ @DIMNAME1 +' NVARCHAR(50)'
        PRINT (@strQry)
		EXEC sp_executesql @STRQRY
		SET @strSelect1=@strSelect1+',CC.'+convert(NVARCHAR,@DIMNAME1)
		
		IF(@R=1)
		BEGIN
			set @strFilter=' CC.'+ @DIMNAME1 +' =T1.' + @DIMNAME1
		END
		ELSE
		BEGIN
		   set @strFilter=@strFilter + ' AND '+ ' CC.'+ @DIMNAME1 +' =T1.' + @DIMNAME1
			
		END
	SET @R=@R+1
	END

	PRINT @strFilter			
	SET @strWhere='AND emp.EmpSeqNo in ('+ @EmpIDs +')'
	
	INSERT INTO #TEMPEMP
	EXEC spPAY_GetEmpMasterCCDetails @PayrollMonth,@strWhere,1,1
	
	--SELECT * FROM #TEMPEMP
	SET @strQry1='SELECT  c51.NodeID EMPNODE '+ CONVERT(NVARCHAR(max),@strSelect1)+',convert(datetime,id.modifieddate) ModDate,TD.*
				FROM INV_DOCDETAILS ID  WITH(NOLOCK) INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID 
				INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_CC50051 C51 WITH(NOLOCK) ON CC.DCCCNID51=C51.NODEID
				INNER JOIN #TEMPEMP T1 ON '+ CONVERT(NVARCHAR(max),@strFilter)+'
				WHERE ID.COSTCENTERID='+ CONVERT(NVARCHAR,@CostCenterID) +' AND ID.StatusID=369 
				AND LEN(TD.DCALPHA2)<25 AND LEN(TD.DCALPHA3)<25 AND ISDATE(TD.DCALPHA2)=1 AND ISDATE(TD.DCALPHA3)=1  
				'
				IF(@CostCenterID=40077)
				BEGIN
					SET @strQry1=@strQry1+' AND CONVERT(DATETIME,'''+ CONVERT(NVARCHAR, @PayrollMonth ) +''') BETWEEN CONVERT(DATETIME,CONVERT(NVARCHAR,TD.DCALPHA2)) AND CONVERT(DATETIME,CONVERT(NVARCHAR,TD.DCALPHA3)) and isnull(td.dcalpha5,'''')=''Locked'''
				END
				ELSE IF(@CostCenterID=40052)
				BEGIN
					SET @strQry1=@strQry1+' ORDER BY CONVERT(DATETIME,dcAlpha3) DESC'
				END
				
				
	print (@strQry1)
	EXEC sp_executesql @strQry1
	DROP TABLE #TEMPEMP
END

----spPAY_GetDimensionDetails
-- 439
-- ,40077
-- ,'8/15/2018 12:00:00 AM'
-- ,1
-- ,1
GO
