USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_UpdateCompensatoryLeavetoAssignLeaves]
	@DATE [datetime] = NULL,
	@EMPNODE [int] = 0,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
--START:FOR START AND END MONTH	
	DECLARE @Year INT,@ALStartMonth INT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME
	DECLARE @LEAVETYPEGP INT,@LEAVESTAKEN INT,@CURRYEARALDOCNO INT
	
	--SELECT @Year=YEAR(CONVERT(DATETIME,@DATE))
	----FOR READING START MONTH FROM GLOBAL PREFERENCES
	--SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE (NAME='LeaveYear' OR RESOURCEID=94471)
	
	----SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
	--SET @ALStartMonthYear= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
	--SET @ALStartMonthYear=CONVERT(DATETIME,@ALStartMonthYear)
	--PRINT @ALStartMonthYear
	
	----SET ENDMONTH FOR THE NEXT YEAR (1YEAR)
	--SET @ALEndMonthYear=DATEADD(M,11,@ALStartMonthYear)
	
	----SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
	--SET @ALEndMonthYear=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALEndMonthYear)+1,0))
	--SET @ALEndMonthYear=CONVERT(DATETIME,@ALEndMonthYear)
	--PRINT @ALEndMonthYear
	
	
	--if CONVERT(DATETIME,@DATE)<CONVERT(DATETIME,@ALStartMonthYear)
	--BEGIN
	--	SET @ALStartMonthYear=DATEADD(YEAR,-1,CONVERT(DATETIME,@ALStartMonthYear))
	--	SET @ALEndMonthYear=DATEADD(YEAR,-1,CONVERT(DATETIME,@ALEndMonthYear))
	--END
	EXEC [spPAY_EXTGetLeaveyearDates] @DATE,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT
	--START:FOR START AND END MONTH	
					SELECT @LEAVETYPEGP=ISNULL(VALUE,12) FROM ADM_GlobalPreferences WHERE (NAME='CompensatoryLeaveType' OR RESOURCEID=94472)

					
					--SET @CURRYEARALDOCNO=(SELECT DISTINCT TOP 1 DOCID FROM INV_DOCDETAILS WITH(NOLOCK)
 				--						  WHERE CONVERT(DATETIME,DOCDATE) between CONVERT(DATETIME,@ALStartMonthYear) and CONVERT(DATETIME,@ALEndMonthYear)
 				--						  AND COSTCENTERID=40060	ORDER BY DOCID DESC)

					DECLARE @UPDATEAL TABLE(InvDocID INT,dcCCNID51 INT,dcCCNID53 INT,dcCCNID52 INT,
										 PrevYearAlloted INT,PrevYearBalanceOB INT,CurrYearConsumed DECIMAL(9,2),
										 Balance DECIMAL(9,2),CurrYearAlloted INT,CompensatoryLeave INT)
					DELETE FROM @UPDATEAL										 
					INSERT INTO @UPDATEAL 
					SELECT ID.INVDOCDETAILSID,DC.dcCCNID51,DC.dcCCNID53,DC.dcCCNID52,0,0,0,0,ISNULL(DN.DCNUM3,0),0
					FROM   INV_DOCDETAILS ID WITH(NOLOCK),COM_DocCCData DC WITH(NOLOCK),COM_DocNumData DN WITH(NOLOCK)
					WHERE  ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND DC.INVDOCDETAILSID=DN.INVDOCDETAILSID
						   AND  CONVERT(DATETIME,ID.DOCDATE) between CONVERT(DATETIME,@ALStartMonthYear) and CONVERT(DATETIME,@ALEndMonthYear)
						   AND ID.COSTCENTERID=40060
						   --ID.DOCID=@CURRYEARALDOCNO
				
					UPDATE T SET T.CompensatoryLeave=ISNULL(LT.NOOFDAYSTAKEN,0),T.Balance=ISNULL(LT.NOOFDAYSTAKEN,0) FROM @UPDATEAL T 
					INNER JOIN
					(SELECT DC.dcCCNID51,DC.DCCCNID52,COUNT(TD.dcAlpha1) AS NOOFDAYSTAKEN
					 FROM COM_DocTextData TD,INV_DOCDETAILS ID,COM_DocCCData DC 
					 WHERE  TD.INVDOCDETAILSID=ID.INVDOCDETAILSID AND TD.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND
							ISDATE(TD.DCALPHA1)=1 AND
							CONVERT(VARCHAR(25),TD.DCALPHA1,106) between CONVERT(VARCHAR(25),@ALStartMonthYear,106) and  CONVERT(VARCHAR(25),@ALEndMonthYear,106)
							AND ID.COSTCENTERID=40059 AND DC.dcCCNID51=@EMPNODE GROUP BY DC.dcCCNID51,DC.DCCCNID52
					) LT  
					ON LT.DCCCNID51=T.DCCCNID51  AND LT.DCCCNID52=T.DCCCNID52 AND T.DCCCNID51=@EMPNODE
					
					
					UPDATE DN SET DN.DCNUM3= ISNULL(T.CompensatoryLeave,0), DN.DCNUM5= ISNULL(T.CompensatoryLeave,0) 
					FROM   COM_DocNumData DN 
						   INNER JOIN  @UPDATEAL T ON T.InvDocID=DN.INVDOCDETAILSID AND T.DCCCNID52=@LEAVETYPEGP AND T.DCCCNID51=@EMPNODE
SET NOCOUNT OFF;
END
GO
