USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCOM_ArabicResourcedataupdate]
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
		DECLARE @ROWCOUNT INT,@TRCOUNT INT,@ARESID BIGINT,@ARESDATA NVARCHAR(1000),@RESDATA NVARCHAR(1000)
		SET @ROWCOUNT=1
		
		DECLARE @TAB TABLE(ID BIGINT IDENTITY(1,1),RESOURCENAME VARCHAR(1000),LANGUAGEID INT,RESOURCEDATA NVARCHAR(1000),RESOURCEID BIGINT,ARESOURCEDATA NVARCHAR(1000))
		INSERT INTO @TAB
		SELECT DISTINCT Resourcename,Languageid,'',0,Resourcedata from COM_LanguageResources with(nolock) where  LanguageID=2 
			AND (RIGHT(Resourcedata,2)<>'-A' AND RIGHT(Resourcedata,3)<>'-AR' AND RIGHT(resourcedata,4)<>'- AR' AND RIGHT(Resourcedata,1)<>'?' AND Resourcedata NOT LIKE '[A-Z]%')
			and Resourcedata  not in (select Resourcedata from COM_LanguageResources with(nolock) where languageid=1 AND (RIGHT(Resourcedata,2)<>'-A' AND RIGHT(Resourcedata,3)<>'-AR' AND RIGHT(resourcedata,4)<>'- AR'  AND RIGHT(Resourcedata,1)<>'?' AND Resourcedata NOT LIKE '[A-Z]%')  )
			
		SELECT @TRCOUNT=COUNT(*) FROM @TAB
		WHILE(@ROWCOUNT<=@TRCOUNT)
		BEGIN
			SELECT @ARESDATA=ARESOURCEDATA FROM @TAB WHERE ID=@ROWCOUNT
			--PRINT @ARESDATA
			SELECT @ARESID=(SELECT TOP 1 RESOURCEID from COM_LanguageResources with(nolock) where languageid=2 AND RESOURCEDATA=CONVERT(NVARCHAR(MAX),@ARESDATA))
			--PRINT @ARESID
			SELECT @RESDATA=RESOURCEDATA FROM COM_LanguageResources with(nolock) where languageid=1 AND RESOURCEID=@ARESID
			UPDATE @TAB SET RESOURCEDATA=@RESDATA WHERE ARESOURCEDATA=@ARESDATA
			SET @ROWCOUNT=@ROWCOUNT+1
		END	
		--SELECT * FROM @TAB
		UPDATE LT SET LT.RESOURCEDATA=T.ARESOURCEDATA
				  FROM COM_LANGUAGERESOURCES LT INNER JOIN @TAB T ON T.RESOURCEDATA=LT.RESOURCEDATA AND LT.LANGUAGEID=2 AND CONVERT(NVARCHAR(MAX),T.ARESOURCEDATA)<>CONVERT(NVARCHAR(MAX),LT.RESOURCEDATA)
END
GO
