USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetIncomeTaxCalcDetails]
	@Year [int],
	@EmpSeqNo [int],
	@StartMonth [int] = 1,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRY    
	
SET NOCOUNT ON;
DECLARE @GRADE INT,@GRADEWISEVACATIONPREF VARCHAR(5),@Hasaccesss BIT,@RoleID INT
DECLARE @ALStartMonth INT,@ALStartDate DATETIME,@ALEndDate DATETIME
DECLARE @AccStartDate DATETIME,@AccEndDate DATETIME,@DORelieve DATETIME

--User access check for EMPLOYEE  
SELECT @RoleID=R.ROLEID FROM ADM_USERROLEMAP R WITH(NOLOCK),ADM_USERS U WITH(NOLOCK) WHERE R.USERID=U.USERID AND U.USERID=@UserID
SET @Hasaccesss=dbo.fnCOM_HasAccess(@RoleID,264,2)  
IF @Hasaccesss=0  
BEGIN  
	RAISERROR('-105',16,1)  
END

SELECT @DORelieve=CONVERT(DATETIME,DORelieve) FROM COM_CC50051 where NodeID=@EmpSeqNo
print @DORelieve
--READING START MONTH FROM GLOBAL PREFERENCES
--SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE NAME='LeaveYear'
SELECT @ALStartMonth=AccountingFromMonth FROM PACT2C.dbo.ADM_Company WITH(NOLOCK) WHERE DBIndex=CONVERT(INT,REPLACE(DB_NAME(),'PACT2C',''))

--SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
SET @ALStartDate= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
SET @ALStartDate=CONVERT(DATETIME,@ALStartDate)

--SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
SET @ALEndDate=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,DATEADD(M,11,@ALStartDate))+1,0))
SET @ALEndDate=CONVERT(DATETIME,@ALEndDate)

--SET ACCOUNTING DATES
--SET FIRST DATE TO GIVEN MONTH FROM PARAMETER
SET @AccStartDate= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@StartMonth,-1))+'-' +'01'
SET @AccStartDate=CONVERT(DATETIME,@AccStartDate)

--SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
SET @AccEndDate=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,DATEADD(M,11,@AccStartDate))+1,0))
SET @AccEndDate=CONVERT(DATETIME,@AccEndDate)

PRINT 'ACC'
PRINT @AccStartDate
PRINT @AccEndDate
	
--START:GRADE
SELECT @GRADEWISEVACATIONPREF=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='GradeWiseMonthlyPayroll'
IF (@GRADEWISEVACATIONPREF='True')
BEGIN
	IF((SELECT COUNT(*) FROM ADM_CostCenterDef WITH(NOLOCK) WHERE CostCenterID=50051 and SysColumnName ='CCNID53' and IsColumnInUse=1 and UserProbableValues='H')>0)
		SELECT @GRADE=HistoryNodeID FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID=@EmpSeqNo AND CostCenterID=50051 AND HistoryCCID=50053 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,@ALEndDate)) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,@ALEndDate) OR ToDate IS NULL)
	ELSE
		SELECT @GRADE=ISNULL(CCNID53,0) FROM COM_CCCCDATA WITH(NOLOCK) WHERE COSTCENTERID=50051 AND NODEID=@EmpSeqNo
END

IF ISNULL(@GRADE,0)=0
	SET @GRADE=1

print 'Grade'
print @Grade
--END:GRADE

--0.TOTAL SALARY FIELDS
DECLARE @TABTOTALSALARY TABLE(ID INT IDENTITY(1,1),SNo int,componentID INT,SalaryBreakup varchar(100),FieldName varchar(25),MapFieldName varchar(200))

INSERT INTO @TABTOTALSALARY				   
	SELECT c54.SNo,c54.ComponentID,c52.Name,'dcCalcNum'+convert(varchar,c54.SNo),(SELECT CP.Name from COM_CC50052 CP WITH(NOLOCK) WHERE CP.NodeID=C54.Taxmap) 
	from Com_CC50054 c54 WITH(NOLOCK),Com_CC50052 c52 WITH(NOLOCK) 
	WHERE c52.NodeID=c54.ComponentID AND Gradeid=@GRADE AND Type =1 
	AND PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)
	AND (c54.AddToNet='Tax' OR c54.AddToNet='NetAndTax') 

INSERT INTO @TABTOTALSALARY				   
	SELECT 0,-100,'TOTAL SALARY','',''
 
SELECT * FROM @TABTOTALSALARY
 
--1.MONTHLY PAYROLL
Select Left(DateName(month,td.dcAlpha17),3) month,ID.Costcenterid,ID.vouchertype,CC.dcccnid51,td.dcAlpha17,td.dcAlpha18,dn.* 
From INV_DOCDETAILS ID WITH(NOLOCK) 
JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID 
JOIN PAY_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
Where id.Costcenterid=40054 and cc.dcccnid51=@EmpSeqNo and id.vouchertype=11 and ID.StatusID=369 --and YEAR(CONVERT(DATETIME,ID.DueDate))=@Year 
AND CONVERT(DATETIME,DUEDATE) BETWEEN CONVERT(DATETIME,@AccStartDate) AND CONVERT(DATETIME,@AccEndDate)
order by td.dcalpha17
 
--2.POST PAST SALARY
DECLARE @TABPOSTSALARY TABLE(SNO INT,COMPONENTID INT,DCALPHA3 varchar(100),DCALPHA4 varchar(100),DCALPHA5 varchar(100),DCALPHA6 varchar(100),DCALPHA7 varchar(100),DCALPHA8 varchar(100),DCALPHA9 varchar(100),
 						     DCALPHA10 varchar(100),DCALPHA11 varchar(100),DCALPHA12 varchar(100),DCALPHA13 varchar(100),DCALPHA14 varchar(100),ComponentType int)
DECLARE @TABPOSTPASTSALARY TABLE(SNO INT,COMPONENTID INT,ComponentType int,FIELDNAME VARCHAR(50),AMOUNT FLOAT)

IF((SELECT COUNT(*) FROM INV_DOCDETAILS ID with(nolock),COM_DOCCCDATA CC with(nolock) WHERE ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND ID.COSTCENTERID=40071 AND CC.DCCCNID51=@EmpSeqNo)>0)
BEGIN 
INSERT INTO @TABPOSTSALARY
	Select c54.SNo,isnull(td.dcalpha2,0) Componentid,isnull(td.dcalpha3,0) as dcalpha3,isnull(td.dcalpha4,0) as dcalpha4,isnull(td.dcalpha5,0) as dcalpha5,isnull(td.dcalpha6,0) as dcalpha6,isnull(td.dcalpha7,0) as dcalpha7,
		   isnull(td.dcalpha8,0) as dcalpha8,isnull(td.dcalpha9,0) as dcalpha9,isnull(td.dcalpha10,0) as dcalpha10,isnull(td.dcalpha11,0) as dcalpha11,isnull(td.dcalpha12,0) as dcalpha12,isnull(td.dcalpha13,0) as dcalpha13,isnull(td.dcalpha14,0) as dcalpha14,C54.Type
	FROM   inv_docdetails id with(nolock),com_doctextdata td with(nolock),com_docccdata cc with(nolock),com_cc50054 c54 WITH(NOLOCK),com_cc50052 c52 WITH(NOLOCK)
	WHERE  id.invdocdetailsid=td.invdocdetailsid and id.invdocdetailsid=cc.invdocdetailsid and td.invdocdetailsid=cc.invdocdetailsid
		   AND c52.NodeID=c54.ComponentID and gradeid=@GRADE and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@AccEndDate) AND Gradeid=@GRADE)
		   AND c54.ComponentID=TD.dcalpha2  AND  c52.NODEID=TD.dcalpha2  
		   AND ID.StatusID=369 AND id.costcenterid=40071 and isdate(td.dcalpha1)=1 and YEAR(CONVERT(DATETIME,td.dcalpha1))=@Year and cc.dcccnid51=@EmpSeqNo
		   AND (c54.AddToNet='Tax' OR c54.AddToNet='NetAndTax') 
 
 INSERT INTO  @TABPOSTPASTSALARY
 SELECT SNO,COMPONENTID,ComponentType,CA.COLNAME,CA.COLVALUE FROM @TABPOSTSALARY
 CROSS APPLY(VALUES ('Jan',DCALPHA3),					('Feb',DCALPHA4),					('Mar',DCALPHA5),
					('Apr',DCALPHA6),					('May',DCALPHA7),					('Jun',DCALPHA8),
					('Jul',DCALPHA9),					('Aug',DCALPHA10),					('Sep',DCALPHA11),
					('Oct',DCALPHA12),					('Nov',DCALPHA13),					('Dec',DCALPHA14)
					
 ) AS CA(COLNAME,COLVALUE)
 END
SELECT * FROM @TABPOSTPASTSALARY
 
--3.EMP PAY
SELECT TOP 1 *,Left(DateName(month,CONVERT(DATETIME,EffectFrom)),3) month FROM Pay_EmpPay with(nolock) WHERE EmployeeID=@EmpSeqNo ORDER BY EffectFrom Desc,SeqNo Desc

--4.FORM 12BA
DECLARE @TABFORM12BA TABLE(FIELDTYPE VARCHAR(100),componentid VARCHAR(100),SalaryBreakup VARCHAR(100),AMOUNT FLOAT)

IF((SELECT  count(*) 	FROM    INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
	WHERE   id.costcenterid=40076 AND ID.StatusID=369 and td.dcalpha1=convert(varchar,@Year) and cc.dcccnid51=@EmpSeqNo and td.dcAlpha3 in ('-1','-2'))>0)
BEGIN
--select 1
INSERT INTO @TABFORM12BA
	SELECT  td.dcAlpha3,td.dcAlpha2,CASE WHEN td.dcAlpha3='-1' THEN 'Value of Perquisites U/s.17(2) (as per Form No.12BA)'
	 WHEN td.dcAlpha3='-2' THEN 'Profits in lieu of Salary U/s.17(3) (as per Form No.12BA)' END,isnull(dn.dcNum3,0)
	FROM    INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
	JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
	WHERE   id.costcenterid=40076 AND ID.StatusID=369 and td.dcalpha1=convert(varchar,@Year) and cc.dcccnid51=@EmpSeqNo and td.dcAlpha3 in ('-1','-2')
END
ELSE
BEGIN
INSERT INTO @TABFORM12BA
	SELECT -1,0,'Value of Perquisites U/s.17(2) (as per Form No.12BA)',0
INSERT INTO @TABFORM12BA
	SELECT -2,0,'Profits in lieu of Salary U/s.17(3) (as per Form No.12BA)',0	
END
	
SELECT * FROM @TABFORM12BA
 
 
--5.HRA AMOUNT 10% OFF BASIC
DECLARE @HRAAMOUNT FLOAT,@BASIC FLOAT,@HRATOTALAMOUNT FLOAT,@BASICPERCENTAGEAMOUNT FLOAT
SELECT @HRAAMOUNT=ISNULL(AMOUNT,0) FROM PAY_EmpTaxHRAInfo WITH(NOLOCK) WHERE YEAR=@Year AND EMPNODE=@EmpSeqNo
SELECT TOP 1 @BASIC=isnull(BasicMonthly,0) FROM Pay_EmpPay with(nolock) WHERE EmployeeID=@EmpSeqNo ORDER BY EffectFrom Desc,SeqNo Desc
SET @BASICPERCENTAGEAMOUNT=(@BASIC*10)/100
SET @HRATOTALAMOUNT=@HRAAMOUNT-ISNULL(@BASICPERCENTAGEAMOUNT,0)
PRINT 'HRA'
print @HRAAMOUNT
PRINT @HRATOTALAMOUNT
SELECT ISNULL(@HRATOTALAMOUNT,0) AS ActualRentPaid10Basic

--6.HRA ACTUAL RECEIVED
SELECT componentid FROM COM_CC50054 WITH(NOLOCK) WHERE TAXMAP=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE (CODE LIKE 'IT_HRA%' OR NAME LIKE 'IT_HRA%')) and gradeid=@GRADE and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)
 
--7.INCOME TAX DEFINITION FOR METRO/NONMETRO YEAR WISE
Select td.dcalpha1 as ITYear,td.dcalpha6 as MetroFormula,td.dcalpha7 as NonmetroFormula,td.dcalpha2 as TotalIncomeRoundoff,td.dcalpha3 as Surcharge,td.dcalpha4 as EducationCess,td.dcalpha5 as SecondaryandHighEduc,
	   td.dcalpha8 as Gender,dn.dcnum1 as Fromslab,dn.dcnum2 as Toslab,dcnum3 as Percentage,dcAlpha10 as RegimeType from INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
Where id.costcenterid=40074 and ID.StatusID=369 and isnumeric(td.dcalpha1)=1 and td.dcalpha1=@Year
 
--8.CUSTOMIZE PAYROLL STRUCTURE
SELECT C52.NAME AS ComponentName, c54.[NodeID], c54.[GradeID], convert(datetime,[PayrollDate]) [PayrollDate], [Type], c54.[SNo], [ComponentID], [Formula], [AddToNet], [FieldType], [Applicable],[Behaviour], [MaxOTHrs], [ROff], [TaxMap], [Expression], [DrAccount], [CrAccount], [Percentage], [MaxLeaves], [AtATime], [CarryForward], [IncludeRExclude],  [Message], [Action], [MaxCarryForwardDays], [MaxEncashDays],c52.Name Heading FROM com_cc50054 c54 WITH(NOLOCK) ,com_cc50052 c52 WITH(NOLOCK) 
WHERE c52.nodeid=c54.componentID and GradeID=@Grade AND PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE) Order By Type,Sno

--9.LOADING INCOMETAX COMPONENTS OF TYPE 'INCOME'

DECLARE @OtherEar TABLE(SNo int,componentID INT,ParentID INT,TaxMap INT,Name NVARCHAR(100),IsGroup INT,FieldType NVARCHAR(100))

---CONVEYANCE

IF((SELECT	COUNT(*) FROM COM_CC50052 c52 WITH(NOLOCK),com_cc50054 c54 WITH(NOLOCK)
	 WHERE  c52.NodeID=c54.ComponentID and GradeID=@Grade and taxmap>0  and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)
			and isnull(CCALPHA3,0)<=0 AND ISGROUP=0	AND taxmap=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE ((CODE LIKE 'IT_CONVEY%' OR NAME LIKE 'IT_CONVEY%'))))>0)
BEGIN
	INSERT INTO @OtherEar
	SELECT	 c54.SNo,c54.ComponentID,c52.ParentID,c54.Taxmap,REPLACE(c52.Name,'IT_','') Name,c52.IsGroup, c52.CCALPHA2 AS FieldType FROM COM_CC50052 c52 WITH(NOLOCK),com_cc50054 c54 WITH(NOLOCK)
	WHERE    c52.NodeID=c54.ComponentID and GradeID=@Grade and taxmap>0  and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE) 
					and isnull(CCALPHA3,0)<=0 AND ISGROUP=0	AND taxmap=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE 
					((CODE LIKE 'IT_CONVEY%' OR NAME LIKE 'IT_CONVEY%')))
END
ELSE
BEGIN
	INSERT INTO @OtherEar
	SELECT 0 SNo,0 ComponentID,0 ParentID,0 Taxmap,'' Name,0 IsGroup, '' FieldType	
END
---CHILDREN ALLOWANCE

IF((SELECT	COUNT(*) FROM COM_CC50052 c52 WITH(NOLOCK),com_cc50054 c54 WITH(NOLOCK)
	 WHERE  c52.NodeID=c54.ComponentID and GradeID=@Grade and taxmap>0  and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)
			and isnull(CCALPHA3,0)<=0 AND ISGROUP=0	AND taxmap=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE ((CODE LIKE 'IT_CHILDREN%' OR NAME LIKE 'IT_CHILDREN%'))))>0)
BEGIN
	INSERT INTO @OtherEar
	SELECT	 c54.SNo,c54.ComponentID,c52.ParentID,c54.Taxmap,REPLACE(c52.Name,'IT_','') Name,c52.IsGroup, c52.CCALPHA2 AS FieldType FROM COM_CC50052 c52 WITH(NOLOCK),com_cc50054 c54 WITH(NOLOCK)
	WHERE    c52.NodeID=c54.ComponentID and GradeID=@Grade and taxmap>0  and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE) 
					and isnull(CCALPHA3,0)<=0 AND ISGROUP=0	AND taxmap=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE 
					((CODE LIKE 'IT_CHILDREN%' OR NAME LIKE 'IT_CHILDREN%')))
END
ELSE
BEGIN
	INSERT INTO @OtherEar
	SELECT 0 SNo,0 ComponentID,0 ParentID,0 Taxmap,'' Name,0 IsGroup, '' FieldType	
END

SELECT * FROM @OtherEar

--10.CHILD COUNT
SELECT COUNT(FIELD5) AS CHILDCOUNT FROM  PAY_EMPDETAIL with(nolock) WHERE EMPLOYEEID=@EmpSeqNo AND ISNULL(FIELD5,'')<>''

--11.LOADING INCOMETAX COMPONENTS OF TYPE 'INCOME'					
SELECT	 PARENTID,NODEID,REPLACE(NAME,'IT_','') NAME,ISGROUP, CCALPHA2 AS FILEDTYPE,ccAlpha5 RegimeType FROM  COM_CC50052 WITH(NOLOCK) WHERE  isnull(CCALPHA3,0)<=0 AND ISGROUP=0
		 AND (NAME LIKE 'IT_MEDICAL%' OR NAME LIKE 'IT_LTA%' OR NAME LIKE 'IT_FOOD COU%' OR NAME LIKE 'IT_LEAVE ENCASH%'	OR NAME LIKE 'IT_GRATU%')
		 OR	 (CODE LIKE 'IT_MEDICAL%' OR CODE LIKE 'IT_LTA%' OR CODE LIKE 'IT_FOOD COU%' OR CODE LIKE 'IT_LEAVE ENCASH%'	OR CODE LIKE 'IT_GRATU%')
		 AND CCALPHA2='Income'	GROUP BY NODEID,NAME,PARENTID,ISGROUP,CCALPHA2,ccAlpha5

 
--12.PROFESSIONAL TAX
DECLARE @PROFTAXNODEID INT
SELECT @PROFTAXNODEID=NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE (CODE LIKE 'IT_PROFESSIONAL TAX%' OR NAME LIKE 'IT_PROFESSIONAL TAX%')
SELECT SNO,componentid FROM COM_CC50054 WITH(NOLOCK) WHERE TAXMAP=(SELECT NODEID FROM COM_CC50052 WITH(NOLOCK) WHERE (CODE LIKE 'IT_PROFESSIONAL TAX%' OR NAME LIKE 'IT_PROFESSIONAL TAX%')) and gradeid=@GRADE and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)
 
--13.HRA Metro /nonMetro
EXEC spPAY_EmployeeHRACalc @EmpSeqNo,@Year,@UserID,@LangID

--14.
DECLARE @TABHOUSEPROPERTY TABLE(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,NODEID INT,NAME VARCHAR(500),AMOUNT FLOAT,RegimeType NVARCHAR(50))
IF((SELECT	 count(*) FROM COM_CC50052 c52 WITH(NOLOCK),PAY_EmpTaxDeclaration ETD with(nolock) WHERE  ETD.componentid=c52.nodeid and ETD.empnode=@EmpSeqNo and ETD.year=@Year and isnull(CCALPHA3,0)>0 And ccAlpha4='House Property/Other Source')>0)
BEGIN
INSERT INTO @TABHOUSEPROPERTY
	SELECT	 CCALPHA3 ORDERNO,PARENTID,NODEID,NAME,ETD.Amount,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK),PAY_EmpTaxDeclaration ETD with(nolock) WHERE ETD.componentid=c52.nodeid and ETD.empnode=@EmpSeqNo and ETD.year=@Year and isnull(CCALPHA3,0)>0
	  		 And ccAlpha4='House Property/Other Source' Order By orderno
END	  		 
ELSE
BEGIN
INSERT INTO @TABHOUSEPROPERTY
	 SELECT	 CCALPHA3 ORDERNO,PARENTID,NODEID,NAME,0,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK) WHERE isnull(CCALPHA3,0)>0 And ccAlpha4='House Property/Other Source' Order By orderno
END
					
SELECT * FROM @TABHOUSEPROPERTY

--15
SELECT * FROM PAY_YearwiseTaxAmountLimit with(nolock) WHERE Year=@Year

--16.80C and 80CCC
DECLARE @TAB80SECTION TABLE(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,NODEID INT,NAME VARCHAR(500),AMOUNT FLOAT,RegimeType NVARCHAR(50))
IF((SELECT	 count(*) FROM COM_CC50052 c52 WITH(NOLOCK),PAY_EmpTaxDeclaration ETD with(nolock)  WHERE ETD.componentid=c52.nodeid and ETD.empnode=@EmpSeqNo and ETD.year=@Year And ccAlpha4='80C')>0)
BEGIN
INSERT INTO @TAB80SECTION
	   SELECT convert(int,CCALPHA3) ORDERNO,PARENTID,NODEID,NAME,etd.amount,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK),PAY_EmpTaxDeclaration ETD with(nolock)
	   WHERE ETD.componentid=c52.nodeid and ETD.empnode=@EmpSeqNo and ETD.year=@Year And ccAlpha4='80C' Order By ParentID,OrderNo
END
ELSE
BEGIN
INSERT INTO @TAB80SECTION
	SELECT convert(int,CCALPHA3) ORDERNO,PARENTID,NODEID,NAME,0,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK)   WHERE  ccAlpha4='80C' Order By ParentID,OrderNo
END

SELECT * FROM @TAB80SECTION

--17.OTHER THAN 80C SECTIONS
DECLARE @TABCHAPTERADETAILS table(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,NODEID INT,NAME VARCHAR(500),AMOUNT FLOAT,RegimeType NVARCHAR(50))				
INSERT INTO @TABCHAPTERADETAILS				
	   SELECT convert(int,CCALPHA3) ORDERNO,PARENTID,NODEID,NAME,0,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK) WHERE ccAlpha4='Otherthan80C' Order By NodeID ,OrderNo

UPDATE T SET T.AMOUNT =T1.AMOUNT FROM @TABCHAPTERADETAILS T INNER JOIN PAY_EmpTaxDeclaration T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@Year AND T1.EMPNODE=@EmpSeqNo		
SELECT * FROM @TABCHAPTERADETAILS ORDER BY NODEID

--18
SELECT E.*,convert(datetime,E.DOJ) CDOJ,convert(datetime,E.DOB) CDOB,convert(datetime,E.DOConfirmation) CDOC,convert(datetime,E.NextAppraisalDate) CNextAppraiselDue,R.Name RptManagerName,0.50 Gross,1.1 Basic,1.1 BasicWeekly,1.1 BasicHourly,1.1 BasicDaily,1.1 AnnualCTC, 
l.Name as GenderName
FROM com_cc50051 E WITH(NOLOCK) 
LEFT JOIN com_cc50051 R WITH(NOLOCK) ON R.NodeID=E.RptManager
Left Join COM_Lookup l on l.LookupType=123 AND l.NodeID=E.Gender
 WHERE E.NodeID=@EmpSeqNo


--19
DECLARE @TABDEDUCTIONSALARY TABLE(ID INT IDENTITY(1,1),SNo int,componentID INT,SalaryBreakup varchar(100),FieldName varchar(25),TaxMap Int,TaxmapName varchar(100))
INSERT INTO @TABDEDUCTIONSALARY
	   SELECT c54.SNo,c54.ComponentID,c52.Name,'dcCalcNum'+convert(varchar,c54.Sno),TAXMAP,REPLACE(C521.NAME,'IT_','') 
	   FROM com_cc50054 c54 WITH(NOLOCK)
	   LEFT JOIN com_cc50052 c52 WITH(NOLOCK) on c52.NodeID=c54.ComponentID
	   LEFT JOIN com_cc50052 c521 WITH(NOLOCK) on C521.NODEID= C54.TAXMAP 
	   WHERE gradeid=@GRADE 
	   and Type =2 
	   AND (c54.AddToNet='Tax' OR c54.AddToNet='NetAndTax') 
	   and PayrollDate=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@ALEndDate) AND Gradeid=@GRADE)

SELECT * FROM @TABDEDUCTIONSALARY

--20.MONTHLY PAYROLL DEDUCTIONS
SELECT	left(datename(month,td.dcalpha17),3) month,id.costcenterid,id.vouchertype,cc.dcccnid51,td.dcalpha17,td.dcalpha18,dn.* 
from INV_DOCDETAILS ID WITH(NOLOCK) 
JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID 
JOIN PAY_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
WHERE	id.costcenterid=40054 and cc.dcccnid51=@EmpSeqNo and id.StatusID=369 and id.vouchertype=12 --and YEAR(CONVERT(DATETIME,ID.DueDate)) =@Year 
		AND CONVERT(DATETIME,DUEDATE) BETWEEN CONVERT(DATETIME,@AccStartDate) AND CONVERT(DATETIME,@AccEndDate)
order by td.dcalpha17
 
 
--21.LOADING DATA FROM INCOMETAX COMPUTATION TABLE
 SELECT * FROM PAY_EmpTaxComputation WITH(NOLOCK) WHERE Year=@Year and EmpNode=@EmpSeqNo
 
--22.READING PAYROLL PROCESSED MONTH FOR GIVEN ACCOUNTING YEAR DATETIME 
SELECT Min(CONVERT(DATETIME,DUEDATE)) MinMonth,MAX(CONVERT(DATETIME,DUEDATE)) PAYROLLMONTH,Left(DateName(month,MAX(CONVERT(DATETIME,DUEDATE))),3) Month,Left(DateName(month,MAX(CONVERT(DATETIME,@DORelieve))),3) RelieveMonth,CONVERT(DATETIME,@DORelieve) as DORelieve 
FROM INV_DOCDETAILS ID WITH(NOLOCK)
JOIN COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID 
WHERE COSTCENTERID=40054
AND cc.dcccnid51=@EmpSeqNo and id.StatusID=369 
AND CONVERT(DATETIME,DUEDATE) BETWEEN CONVERT(DATETIME,@AccStartDate) AND CONVERT(DATETIME,@AccEndDate)
 
 --23
 Select * from PACT2C.dbo.ADM_Company WITH(NOLOCK)

 --24
 Select * from COM_Address WITH(NOLOCK) where FeatureID=50051 AND FeaturePK=@EmpSeqNo

 --25	Exemption U/S 10

DECLARE @ExemUS10 table(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,NODEID INT,NAME VARCHAR(500),AMOUNT FLOAT,RegimeType NVARCHAR(50))				
INSERT INTO @ExemUS10				
	   SELECT convert(int,CCALPHA3) ORDERNO,PARENTID,NODEID,NAME,0,c52.ccAlpha5 FROM COM_CC50052 c52 WITH(NOLOCK) WHERE ccAlpha4='Exemption U/S 10' Order By NodeID ,OrderNo

UPDATE T SET T.AMOUNT =T1.AMOUNT FROM @ExemUS10 T INNER JOIN PAY_EmpTaxDeclaration T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@Year AND T1.EMPNODE=@EmpSeqNo		
SELECT * FROM @ExemUS10 ORDER BY NODEID


SET NOCOUNT OFF;  
RETURN 1  
END TRY  
BEGIN CATCH    
  --Return exception info [Message,Number,ProcedureName,LineNumber]    
  IF ERROR_NUMBER()=50000  
  BEGIN  
   SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID  
  END  
  ELSE  
  BEGIN  
   SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine  
   FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=-999 AND LanguageID=@LangID  
  END   
SET NOCOUNT OFF    
RETURN -999     
END CATCH

GO
