USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCRM_CheckWarranty]
	@SVCCONTRACTID [int] = 0,
	@PRODUCTID [int] = 0,
	@SERIALNO [nvarchar](300) = 0,
	@CASEID [int] = 0,
	@UserID [int],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS

BEGIN TRY	
SET NOCOUNT ON
DECLARE @TOTALUSED FLOAT,@TOTALALLOTED FLOAT,@RETURNVALUE INT

IF ((SELECT COUNT(*) FROM CRM_ContractLines WITH(NOLOCK) WHERE SvcContractID=@SVCCONTRACTID 
	AND ProductID=@PRODUCTID AND SerialNumber=@SERIALNO)>0)
BEGIN

	SELECT @TOTALUSED=COUNT(*) FROM CRM_Cases WITH(NOLOCK) WHERE SvcContractID=@SVCCONTRACTID AND ProductID=@PRODUCTID AND
	SerialNumber=@SERIALNO  AND CaseID<>@CASEID AND BillingMethod IN (138)
   
 	SELECT @TOTALALLOTED=AllottedUnits FROM CRM_ContractLines WITH(NOLOCK) WHERE SvcContractID=@SVCCONTRACTID AND ProductID=@PRODUCTID AND
	SerialNumber=@SERIALNO 		
	
	IF @TOTALALLOTED>@TOTALUSED
	 SET @RETURNVALUE=-100
	ELSE
	 SET @RETURNVALUE=1 
END
ELSE
	SET @RETURNVALUE=-101

 SELECT @RETURNVALUE

SET NOCOUNT OFF;
RETURN @RETURNVALUE
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END

SET NOCOUNT OFF  
RETURN -999   
END CATCH
GO
