USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_DeleteApplyLeaves]
	@COSTCENTERID [int],
	@DOCID [int],
	@detID [nvarchar](max),
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRY
SET NOCOUNT ON;

DECLARE @FROMDATE DATETIME,@INVDOCID INT,@STATUSID INT,@EMPNODE INT,@LEAVETYPE INT
DECLARE @ICOUNT INT,@RCOUNT INT,@LinkedInvDocDetailsID INT,@DOCUMENTTYPE INT

DECLARE @TAB1 TABLE (ID INT IDENTITY(1,1),INVDOCDETAILSID INT,FROMDATE DATETIME,EMPNODE INT,LEAVETYPE INT)
SET @ICOUNT=1

	IF ISNULL(@DOCID,0)>0
	BEGIN
			IF ISNULL(@LinkedInvDocDetailsID,0)=0
			BEGIN
				SELECT @DOCUMENTTYPE=I.DocumentType FROM INV_DOCDETAILS I WITH(NOLOCK) WHERE I.DOCID=@DOCID
				IF(@DOCUMENTTYPE=95)
				BEGIN
					INSERT INTO @TAB1
					SELECT ID.INVDOCDETAILSID,CONVERT(DATETIME,TD.dcAlpha3),CC.DCCCNID51,C52.NodeID
					FROM   INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
					INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
					JOIN COM_CC50052 C52 WITH(NOLOCK) ON C52.Name=TD.dcAlpha12
					WHERE  ID.DOCID=@DOCID AND TD.dcAlpha1=2
				END
				ELSE
				BEGIN
						INSERT INTO @TAB1
						SELECT ID.INVDOCDETAILSID,CASE ID.DocumentType WHEN 62 THEN CONVERT(DATETIME,TD.dcAlpha4) WHEN 58 THEN CONVERT(DATETIME,ID.DOCDATE) WHEN 60 THEN CONVERT(DATETIME,TD.dcAlpha3) WHEN 81 THEN CONVERT(DATETIME,TD.dcAlpha3) END,CC.DCCCNID51,CC.DCCCNID52
						FROM   INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
							   INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
						WHERE  ID.DOCID=@DOCID
				END
			END
			ELSE
			BEGIN
				INSERT INTO @TAB1
				SELECT ID.INVDOCDETAILSID,CASE ID.DocumentType WHEN 62 THEN CONVERT(DATETIME,TD.dcAlpha4) WHEN 58 THEN CONVERT(DATETIME,ID.DOCDATE) WHEN 60 THEN CONVERT(DATETIME,TD.dcAlpha3) WHEN 81 THEN CONVERT(DATETIME,TD.dcAlpha3) END ,CC.DCCCNID51,CC.DCCCNID52
				FROM   INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
					   INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
				WHERE  ID.INVDOCDETAILSID=TD.INVDOCDETAILSID  AND ID.INVDOCDETAILSID=@LinkedInvDocDetailsID
			END
			
			SELECT @RCOUNT =COUNT(*) FROM @TAB1
			WHILE(@ICOUNT<=@RCOUNT)
			BEGIN
				SELECT @INVDOCID=INVDOCDETAILSID,@FROMDATE=CONVERT(DATETIME,FROMDATE),@EMPNODE=EMPNODE,@LEAVETYPE=LEAVETYPE FROM @TAB1 WHERE ID=@ICOUNT
				EXEC spPAY_UpdateAssignLeavesDatewise @FROMDATE,@INVDOCID,1,@EMPNODE,@LEAVETYPE
				SET @ICOUNT=@ICOUNT+1	
			END
	END
	
SET NOCOUNT OFF;  
--RETURN 1  
END TRY  
BEGIN CATCH    
  --Return exception info [Message,Number,ProcedureName,LineNumber]    
  IF ERROR_NUMBER()=50000  
  BEGIN  
   SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID  
  END  
  ELSE  
  BEGIN  
   SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine  
   FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=-999 AND LanguageID=@LangID  
  END   
SET NOCOUNT OFF    
RETURN -999     
END CATCH
GO
