USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_ExtCheckEmployeeLoans]
	@COSTCENTERID [int],
	@DOCID [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;

DECLARE @EmployeeID INT,@LoanTypeID INT,@TOTLOANAMOUNT FLOAT,@TOTPAIDAMOUNT FLOAT

SELECT @EmployeeID=CC.DCCCNID51,@LoanTypeID=CC.DCCCNID52  
	FROM INV_DOCDETAILS ID WITH(NOLOCK) 
	INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON CC.INVDOCDETAILSID=ID.INVDOCDETAILSID  
	WHERE ID.DOCID=@DOCID AND ID.StatusID NOT IN (372,376)

--SUM OF LOAN AMOUNT EXCEPT CURRENT DOCUMENT
SELECT @TOTLOANAMOUNT=SUM(TOTLOANAMOUNT) FROM (SELECT DISTINCT ID.DOCID,CONVERT(FLOAT,ISNULL(TD.dcAlpha2,0)) TOTLOANAMOUNT FROM INV_DOCDETAILS ID WITH(NOLOCK) 
		INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID
		INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON CC.INVDOCDETAILSID=ID.INVDOCDETAILSID  WHERE TD.tCostCenterID=40056 AND ID.STATUSID=369
		AND CC.DCCCNID51=@EmployeeID AND CC.DCCCNID52=@LoanTypeID AND ID.DOCID<>@DOCID) AS TOTALLOANAMOUNT	
			   
--SUM OF PAID LOAN AMOUNT
SELECT @TOTPAIDAMOUNT=ISNULL(SUM(LINKEDFIELDVALUE),0)  FROM INV_DOCDETAILS INV WITH(NOLOCK)
		INNER JOIN COM_DOCTEXTDATA TDD WITH(NOLOCK) ON TDD.INVDOCDETAILSID=INV.INVDOCDETAILSID
		INNER JOIN COM_DOCCCDATA CCC WITH(NOLOCK) ON CCC.INVDOCDETAILSID=INV.INVDOCDETAILSID  WHERE TDD.tCostCenterID=40057 AND INV.STATUSID=369
		AND CCC.DCCCNID51=@EmployeeID AND CCC.DCCCNID52=@LoanTypeID 

IF(@TOTLOANAMOUNT<>@TOTPAIDAMOUNT)
	RAISERROR('-572',16,1) 
	

SET NOCOUNT OFF;
END

----spPAY_ExtCheckEmployeeLoans 40056,24680,1,1
GO
