USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_EXTGetLeaveyearDates]
	@Date [datetime] = null,
	@FromDate [datetime] OUTPUT,
	@ToDate [datetime] OUTPUT,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
	
	DECLARE @Year INT,@ALStartMonth INT,@ALStartMonthYear1 DATETIME,@ALEndMonthYear1 DATETIME
	
	SELECT @Year=YEAR(CONVERT(DATETIME,@Date))
	
	--FOR READING START MONTH FROM GLOBAL PREFERENCES
	SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE NAME='LeaveYear'
	
	--SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
	SET @ALStartMonthYear1= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
	SET @ALStartMonthYear1=CONVERT(DATETIME,@ALStartMonthYear1)
	
	--SET ENDMONTH FOR THE NEXT YEAR (1YEAR)
	SET @ALEndMonthYear1=DATEADD(M,11,@ALStartMonthYear1)
	
	--SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
	SET @ALEndMonthYear1=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALEndMonthYear1)+1,0))
	SET @ALEndMonthYear1=CONVERT(DATETIME,@ALEndMonthYear1)
		
	IF CONVERT(DATETIME,@Date)<CONVERT(DATETIME,@ALStartMonthYear1)
	BEGIN
		SET @ALStartMonthYear1=DATEADD(YEAR,-1,CONVERT(DATETIME,@ALStartMonthYear1))
		SET @ALEndMonthYear1=DATEADD(YEAR,-1,CONVERT(DATETIME,@ALEndMonthYear1))
	END
	
	SELECT @FromDate=CONVERT(DATETIME,@ALStartMonthYear1),@ToDate=CONVERT(DATETIME,@ALEndMonthYear1)
	
	SET NOCOUNT OFF;		
END
GO
