USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_ExtGetDocumentValidations]
	@COSTCENTERID [int],
	@DOCID [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @GRADE INT,@LEAVES FLOAT,@LEAVETYPE FLOAT,@MaxLeaves float,@FROMDATE DATETIME,@TODATE DATETIME,@PayrollDate DATETIME
DECLARE @RC AS INT,@TRC AS INT,@EmployeeID INT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME
IF (@COSTCENTERID=40053)
BEGIN
	DECLARE @TAB1 TABLE(ID INT IDENTITY(1,1),EMPNODE INT,Week1WeekOff1 varchar(50),Week1WeekOff2 varchar(50),Week2WeekOff1 varchar(50),Week2WeekOff2 varchar(50),
						Week3WeekOff1 varchar(50),Week3WeekOff2 varchar(50),Week4WeekOff1 varchar(50),Week4WeekOff2 varchar(50),Week5WeekOff1 varchar(50),Week5WeekOff2 varchar(50))

	INSERT INTO @TAB1    
			SELECT DC.DCCCNID51,TD.DCALPHA2,TD.DCALPHA3,TD.DCALPHA4,TD.DCALPHA5,TD.DCALPHA6,TD.DCALPHA7,TD.DCALPHA8,TD.DCALPHA9,TD.DCALPHA10,TD.DCALPHA11 FROM COM_DOCTEXTDATA TD WITH(NOLOCK)
			 	   JOIN INV_DOCDETAILS ID WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
			WHERE  ID.DOCID=@DOCID AND ID.COSTCENTERID=@COSTCENTERID

			IF((SELECT COUNT(*) FROM @TAB1 WHERE  
				 (Week1WeekOff1 =Week1WeekOff2 and  ((Week1WeekOff1<>'None' and Week1WeekOff2<>'None') and (isnull(Week1WeekOff1,'')<>'' and isnull(Week1WeekOff2,'')<>'')))
				 or
				 (Week2WeekOff1 =Week2WeekOff2 and  ((Week2WeekOff1<>'None' and Week2WeekOff2<>'None') and (isnull(Week2WeekOff1,'')<>'' and isnull(Week2WeekOff2,'')<>'')))
				 or
				 (Week3WeekOff1 =Week3WeekOff2 and  ((Week3WeekOff1<>'None' and Week3WeekOff2<>'None') and (isnull(Week3WeekOff1,'')<>'' and isnull(Week3WeekOff2,'')<>'')))
				 or
				 (Week4WeekOff1 =Week4WeekOff2 and  ((Week4WeekOff1<>'None' and Week4WeekOff2<>'None') and (isnull(Week4WeekOff1,'')<>'' and isnull(Week4WeekOff2,'')<>'')))
				 or
				 (Week5WeekOff1=Week5WeekOff2 and  ((Week5WeekOff1<>'None' and Week5WeekOff2<>'None') and (isnull(Week5WeekOff1,'')<>'' and isnull(Week5WeekOff2,'')<>''))))>0)
			BEGIN
				RAISERROR('-564',16,1) 
			END
END
ELSE IF (@COSTCENTERID=40060)
BEGIN
	DECLARE @TAB2 TABLE(ID INT IDENTITY(1,1),EMPNODE INT,GRADE INT,LEAVETYPE INT,LEAVES FLOAT)

	SELECT @EmployeeID=DC.DCCCNID51,@LEAVETYPE=DC.DCCCNID52,@FROMDATE=CONVERT(DATETIME,TD.DCALPHA3),@TODATE=CONVERT(DATETIME,TD.DCALPHA4) FROM INV_DOCDETAILS ID WITH(NOLOCK) 
		   JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
	WHERE  ID.DOCID=@DOCID AND ID.COSTCENTERID=@COSTCENTERID
	--SET TO FIRST DAY FOR THE GIVEN DATE
	SET @PayrollDate=DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DATETIME,@FROMDATE)),0)

	----FOR START DATE AND END DATE OF LEAVE YEAR	
	EXEC [spPAY_EXTGetLeaveyearDates] @FROMDATE,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT			
	
	INSERT INTO @TAB2
			SELECT DC.DCCCNID51,DC.DCCCNID53,DC.DCCCNID52,ISNULL(SUM(DN.DCNUM3),0) FROM INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID 
				   JOIN COM_DOCCCDATA DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID	JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
			WHERE  ID.COSTCENTERID=@COSTCENTERID AND ISDATE(TD.DCALPHA3)=1 AND CONVERT(DATETIME,TD.DCALPHA3) BETWEEN CONVERT(DATETIME,@ALStartMonthYear) AND CONVERT(DATETIME,@ALEndMonthYear)
				   AND DC.DCCCNID51=@EmployeeID AND DC.DCCCNID52=@LEAVETYPE
			GROUP BY DC.DCCCNID51,DC.DCCCNID53,DC.DCCCNID52
	
	SET @RC=1
 	SELECT @TRC=COUNT(*) FROM @TAB2
	WHILE (@RC<=@TRC)
	BEGIN	
			SELECT @GRADE=GRADE,@LEAVES=LEAVES,@LEAVETYPE=LEAVETYPE FROM @TAB2 WHERE ID=@RC
			SELECT @MaxLeaves=isnull(MaxLeaves,0) FROM COM_CC50054 WITH(NOLOCK) WHERE GRADEID=@GRADE AND COMPONENTID=@LEAVETYPE	AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@PayrollDate) AND GradeID=@GRADE)
			IF(@MaxLeaves>0 and @LEAVES>@MaxLeaves)
			BEGIN
				RAISERROR('-565',16,1) 				
			END
	SET @RC=@RC+1
    END
END		
SET NOCOUNT OFF;
END
GO
