USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_ResetApplyLeaves]
	@DOCID [bigint],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;

DECLARE @FROMDATE DATETIME,@INVDOCID BIGINT,@EMPNODE INT,@STATUSID INT,@LEAVESTAKEN DECIMAL(9,2),@BALANCELEAVES DECIMAL(9,2)
DECLARE @TAB1 TABLE (ID BIGINT IDENTITY(1,1),INVDOCDETAILSID BIGINT,FROMDATE DATETIME,EMPNODE INT,LEAVESTAKEN DECIMAL(9,2),LEAVETYPE INT)
DECLARE @ICOUNT INT,@RCOUNT INT,@LinkedInvDocDetailsID INT

SET @ICOUNT=1

DECLARE @Year INT,@ALStartMonth INT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME,@LEAVETYPE INT,@CURRYEARALDOCNO BIGINT
DECLARE @UPDATEASSIGNLEAVES TABLE(InvDocID BIGINT,dcCCNID51 BIGINT,dcCCNID53 BIGINT,dcCCNID52 BIGINT,
										 PrevYearAlloted INT,PrevYearBalanceOB INT,CurrYearConsumed DECIMAL(9,2),
										 Balance DECIMAL(9,2),CurrYearAlloted BIGINT,CompensatoryLeave INT)
	IF ISNULL(@DOCID,0)>0
	BEGIN
		SELECT @STATUSID=ISNULL(STATUSID,0) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID
		IF @STATUSID=369 
		BEGIN
				INSERT INTO @TAB1
				SELECT ID.INVDOCDETAILSID,CONVERT(DATETIME,TD.dcAlpha4),ISNULL(CC.DCCCNID51,0),ISNULL(TD.dcAlpha7,0),ISNULL(CC.DCCCNID52,0)
				FROM   INV_DOCDETAILS ID WITH(NOLOCK),COM_DocTextData TD WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK)
				WHERE  ID.INVDOCDETAILSID=TD.INVDOCDETAILSID  AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND TD.INVDOCDETAILSID=CC.INVDOCDETAILSID
				AND ID.DOCID=@DOCID AND ID.STATUSID=369
			
					SELECT @RCOUNT =COUNT(*) FROM @TAB1
				  	WHILE(@ICOUNT<=@RCOUNT)
					BEGIN
					SET @LEAVESTAKEN=0
					SET @LEAVETYPE=0
								SELECT @INVDOCID=INVDOCDETAILSID,@FROMDATE=CONVERT(DATETIME,FROMDATE),@EMPNODE=EMPNODE, @LEAVETYPE=LEAVETYPE,
									   @LEAVESTAKEN=LEAVESTAKEN	FROM @TAB1 WHERE ID=@ICOUNT
								
								--START:FOR START DATE AND END DATE OF LEAVE YEAR	
								EXEC [spPAY_EXTGetLeaveyearDates] @FromDate,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT
								
								SET @CURRYEARALDOCNO=(SELECT DISTINCT TOP 1 DOCID FROM INV_DOCDETAILS WITH(NOLOCK)
 												  WHERE CONVERT(DATETIME,DOCDATE) between CONVERT(DATETIME,@ALStartMonthYear) and CONVERT(DATETIME,@ALEndMonthYear)
 												  AND COSTCENTERID=40060	ORDER BY DOCID DESC)

							DELETE FROM @UPDATEASSIGNLEAVES										 
							INSERT INTO @UPDATEASSIGNLEAVES 
							SELECT ID.INVDOCDETAILSID,DC.dcCCNID51,DC.dcCCNID53,DC.dcCCNID52,0,0,ISNULL(DN.DCNUM4,0),ISNULL(DN.DCNUM5,0),ISNULL(DN.DCNUM3,0),0
							FROM   INV_DOCDETAILS ID WITH(NOLOCK),COM_DocCCData DC WITH(NOLOCK),COM_DocNumData DN WITH(NOLOCK)
							WHERE  ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND DC.INVDOCDETAILSID=DN.INVDOCDETAILSID
								   AND ID.DOCID=@CURRYEARALDOCNO

							
							UPDATE DN SET  DN.DCNUM4=ISNULL(DN.DCNUM4,0) - ISNULL(@LEAVESTAKEN,0),DN.DCNUM5=ISNULL(DN.DCNUM5,0) + ISNULL(@LEAVESTAKEN,0)
								FROM @UPDATEASSIGNLEAVES T INNER JOIN COM_DocNumData DN ON T.InvDocID=DN.INVDOCDETAILSID
								INNER JOIN COM_DOCCCDATA CC ON T.dcCCNID51=CC.dcCCNID51 
								AND T.dcCCNID52=CC.dcCCNID52
								AND DN.INVDOCDETAILSID=CC.INVDOCDETAILSID
								AND T.dcCCNID51=@EMPNODE AND T.dcCCNID52=@LEAVETYPE
								--Set
						
				SET @ICOUNT=@ICOUNT+1	
				END
		END
	END
SET NOCOUNT OFF;	
END
GO
