USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_PostDailyAttendancetoPayroll]
	@EmpIDs [nvarchar](max),
	@PayrollStart [datetime],
	@PayrollEnd [datetime],
	@IncludeOTHours [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @strQry varchar(max),@strColumns varchar(max),@strSelect varchar(max),@strSelectCols varchar(max)
DECLARE @R INT,@TR INT,@DIMNAME VARCHAR(100)

CREATE TABLE #TABDATDIMENSIONS (USERDIMENSIONNAME VARCHAR(100),SYSDIMENSIONNAME VARCHAR(100),COSTCENTERID INT)
CREATE TABLE #TABATTDIMENSIONS (USERDIMENSIONNAME VARCHAR(100),SYSDIMENSIONNAME VARCHAR(100),COSTCENTERID INT)

			
SET @strQry=''
SET @strColumns=''
SET @strSelectCols=''
SET @strSelect=''

INSERT INTO #TABDATDIMENSIONS 
	SELECT USERCOLUMNNAME,SYSCOLUMNNAME,40067 FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=40067 AND SYSCOLUMNNAME LIKE 'dcCCNID%' AND USERCOLUMNNAME NOT LIKE 'dcCCNID%' AND SYSCOLUMNNAME <>'dcCCNID51' AND SectionID=3	        
	
INSERT INTO #TABATTDIMENSIONS 
	SELECT USERCOLUMNNAME,SYSCOLUMNNAME,40079 FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=40079 AND SYSCOLUMNNAME LIKE 'dcCCNID%' AND USERCOLUMNNAME NOT LIKE 'dcCCNID%' AND SYSCOLUMNNAME <>'dcCCNID51' AND SectionID=3	        

DELETE FROM #TABDATDIMENSIONS WHERE SYSDIMENSIONNAME NOT IN (SELECT SYSDIMENSIONNAME FROM #TABATTDIMENSIONS)

ALTER TABLE #TABDATDIMENSIONS ADD ID INT IDENTITY(1,1)
ALTER TABLE #TABATTDIMENSIONS ADD ID INT IDENTITY(1,1)

--LOADING DATA FROM DAILY ATTENDANCE WITH DIMENSIONS
	SET @strQry='DECLARE @TABATTENDANCEDIM1 TABLE(SNO INT IDENTITY(1,1),EMPNODE INT,EMPNAME VARCHAR(500),DAT DATETIME,WorkingHrs FLOAT,OT1 FLOAT,OT2 FLOAT,OT3 FLOAT,OT4 FLOAT,OT5 FLOAT,'
	SET @R=1
   	SELECT @TR=COUNT(*) FROM #TABDATDIMENSIONS  
	WHILE (@R<=@TR)
	BEGIN	
		SELECT @DIMNAME=REPLACE(SYSDIMENSIONNAME,'','') FROM #TABDATDIMENSIONS WHERE ID=@R	
		IF(@DIMNAME IS NOT NULL AND @DIMNAME<>'')
		BEGIN
		
			SET @strColumns=@strColumns+@DIMNAME+' INT'+','
			SET @strSelect=@strSelect+'CC.'+convert(varchar,@DIMNAME)+','
		END
	SET @R=@R+1
	END
	
	IF (ISNULL(@strSelect,'')<>'')
	begin
		SET @strSelectCols=REPLACE(LEFT(@strSelect,DATALENGTH(@strSelect)-1),'CC.','')
	end
	
	SET @strQry=@strQry+ @strColumns +'DAYSATTENDED FLOAT,ABSENTDAYS FLOAT,Leaves FLOAT,TOTALOTAMOUNT FLOAT)'
	
	SET @strQry=@strQry+'INSERT INTO @TABATTENDANCEDIM1
							SELECT   CC.DCCCNID51 EMP,C51.NAME,CONVERT(DATETIME,TD.DCALPHA1) AS DADATE,(DN.DCNUM2) AS WorkingHrs,
								     (DN.DCNUM5) AS OT1,(DN.DCNUM7) AS OT2,(DN.DCNUM9) AS OT3,(DN.DCNUM11) AS OT4,(DN.DCNUM13) AS OT5,' + @strselect +'0,0,0,DN.dcNum15-DN.dcNum3
							FROM     INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK),COM_CC50051 C51 WITH(NOLOCK)
							WHERE    ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
								     AND CC.DCCCNID51=C51.NODEID AND TD.tDocumentType=67 AND ID.StatusID=369 AND CC.DCCCNID51 in ('+ @EmpIDs+') 
								     AND ISDATE(TD.DCALPHA1)=1 AND CONVERT(DATETIME,TD.DCALPHA1) BETWEEN CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollStart)+''') AND CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollEnd)+''')
							ORDER BY CONVERT(DATETIME,TD.DCALPHA1) 
							
							INSERT INTO @TABATTENDANCEDIM1
							SELECT   CC.DCCCNID51 EMP,C51.NAME,'''' AS DADATE,0 AS WorkingHrs,
								     0 AS OT1,0 AS OT2,0 AS OT3,0 AS OT4,0 AS OT5,' + @strselect +'0,0,SUM(CONVERT(FLOAT,dcAlpha7)) as Leaves,0
							FROM     INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK),COM_CC50051 C51 WITH(NOLOCK)
							WHERE    TD.tCostCenterID=40062 AND ID.StatusID=369  
									AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
								     AND CC.DCCCNID51=C51.NODEID AND CC.DCCCNID51 in ('+ @EmpIDs+') 
								     AND ISNUMERIC(dcAlpha7)=1 AND ISDATE(TD.DCALPHA4)=1 AND ISDATE(TD.DCALPHA5)=1  
									 AND LEN(TD.DCALPHA4)<30  AND LEN(TD.DCALPHA5)<30
									 AND (
									 (CONVERT(DATETIME,TD.DCALPHA4) BETWEEN CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollStart)+''') AND CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollEnd)+''')) OR 
									 (CONVERT(DATETIME,TD.DCALPHA5) BETWEEN CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollStart)+''') AND CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollEnd)+'''))
									 )
									 GROUP BY CC.DCCCNID51,' + @strselect +' C51.NAME,TD.DCALPHA4,TD.DCALPHA5  
									 ORDER BY CONVERT(DATETIME,TD.DCALPHA4) 
							

							SELECT * FROM @TABATTENDANCEDIM1
							 
							'

	IF (@IncludeOTHours=1)
	BEGIN	
		IF (ISNULL(@strSelectCols,'')='')
			SET @strQry=@strQry+' SELECT EMPNODE,SUM(WorkingHrs) as WorkingHrs,sum(OT1) OT1,sum(OT2) OT2,sum(OT3) OT3,sum(OT4) OT4,sum(OT5) OT5,Count(Dat)  DAYSATTENDED ,0 as ABSENTDAYS,0 as Leaves,SUM(TOTALOTAMOUNT) TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves=0 GROUP BY EMPNODE'
		ELSE
			SET @strQry=@strQry+' SELECT EMPNODE,SUM(WorkingHrs) as WorkingHrs,'+ @strSelectCols +',sum(OT1) OT1,sum(OT2) OT2,sum(OT3) OT3,sum(OT4) OT4,sum(OT5) OT5,Count(Dat)  DAYSATTENDED , 0 as ABSENTDAYS,0 as Leaves,SUM(TOTALOTAMOUNT) TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves=0 GROUP BY EMPNODE,'+ @strSelectCols

		 IF (ISNULL(@strSelectCols,'')<>'')
		SET @strQry=@strQry+' UNION ALL SELECT EMPNODE,0 as WorkingHrs,'+ @strSelectCols +',0 OT1,0 OT2,0 OT3,0 OT4,0 OT5,0  DAYSATTENDED , 0 as ABSENTDAYS,SUM(Leaves) as Leaves,0 TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves<>0 GROUP BY EMPNODE,'+ @strSelectCols

	END
	ELSE
	BEGIN
		IF (ISNULL(@strSelectCols,'')='')
			SET @strQry=@strQry+' SELECT EMPNODE,SUM(WorkingHrs) as WorkingHrs,0 OT1,0 OT2,0 OT3,0 OT4,0 OT5,Count(Dat) DAYSATTENDED,0 as  ABSENTDAYS,0 as Leaves,SUM(TOTALOTAMOUNT) TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves=0 GROUP BY EMPNODE'
		ELSE
			SET @strQry=@strQry+' SELECT EMPNODE,SUM(WorkingHrs) as WorkingHrs,'+ @strSelectCols +',0 OT1,0 OT2,0 OT3,0 OT4,0 OT5,Count(Dat) DAYSATTENDED,0 as ABSENTDAYS,0 as Leaves,SUM(TOTALOTAMOUNT) TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves=0 GROUP BY EMPNODE,'+ @strSelectCols

			IF (ISNULL(@strSelectCols,'')='')
			SET @strQry=@strQry+' UNION ALL SELECT EMPNODE,0 as WorkingHrs,'+ @strSelectCols +',0 OT1,0 OT2,0 OT3,0 OT4,0 OT5,0 DAYSATTENDED,0 as ABSENTDAYS,SUM(Leaves) as Leaves,0 TOTALOTAMOUNT FROM @TABATTENDANCEDIM1 WHERE Leaves<>0 GROUP BY EMPNODE,'+ @strSelectCols
	END

	IF (ISNULL(@strSelectCols,'')='')
	BEGIN
		SET @strQry=@strQry+' SELECT EMPNODE,COUNT(DAT) as ABSENTDAYS,0 as Leaves FROM @TABATTENDANCEDIM1 
								WHERE Leaves=0 AND '
		IF(Select Value From ADM_GlobalPreferences WHERE Name='AddWeeklyOffs')='True'
			SET @strQry=@strQry+' WorkingHrs=0 '
		ELSE 
			SET @strQry=@strQry+' WorkingHrs<=0 '

		SET @strQry=@strQry+' GROUP BY EMPNODE'
	END
	ELSE
	BEGIN
		SET @strQry=@strQry+' SELECT EMPNODE,'+ @strSelectCols +',COUNT(DAT) as ABSENTDAYS,0 as Leaves FROM @TABATTENDANCEDIM1 
								WHERE Leaves=0  AND '
		IF(Select Value From ADM_GlobalPreferences WHERE Name='AddWeeklyOffs')='True'
			SET @strQry=@strQry+' WorkingHrs=0 '
		ELSE 
			SET @strQry=@strQry+' WorkingHrs<=0 '

		SET @strQry=@strQry+' GROUP BY EMPNODE,'+ @strSelectCols
	END

	print (@strQry)
	EXEC (@STRQRY)
	EXEC SPSplitString @strSelectCols,','

	IF (ISNULL(@strSelectCols,'')<>'')
	BEGIN
		SET @strQry='SELECT dcCCNID51 as EMPNODE,'+ @strSelectCols +', CONVERT(FLOAT,dcAlpha7) as Leaves,CONVERT(DATETIME,d.DCALPHA4) FromDate,CONVERT(DATETIME,d.DCALPHA5) ToDate,b.dcCCNID52 ComponentID
		FROM INV_DocDetails a WITH(NOLOCK) 
		JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
		JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
		WHERE d.tCostCenterID=40062 and a.StatusID=369 AND b.dcCCNID51 in ('+ @EmpIDs+') 
		AND ISNUMERIC(dcAlpha7)=1 AND ISDATE(d.DCALPHA4)=1 AND ISDATE(d.DCALPHA5)=1  
		AND (
		(CONVERT(DATETIME,d.DCALPHA4) BETWEEN CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollStart)+''') AND CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollEnd)+''')) OR 
		(CONVERT(DATETIME,d.DCALPHA5) BETWEEN CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollStart)+''') AND CONVERT(DATETIME,'''+ convert(VARCHAR,@PayrollEnd)+'''))
		)'
		

		print (@strQry)
		EXEC (@STRQRY)

	END
	ELSE
		SELECT 1 as NODATA


	DROP TABLE #TABDATDIMENSIONS
	DROP TABLE #TABATTDIMENSIONS
	

END

GO
