USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCOM_GetAssignedUserEmailAddress]
	@CostCenterID [int],
	@NODEID [int]
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRANSACTION
	if exists (select * from sys.tables with(nolock) where name='CRM_Assignment')
	BEGIN
  
		--ASSIGNED USERS 
		DECLARE @stract NVARCHAR(MAX),@SQL NVARCHAR(MAX)
	    CREATE TABLE #ASSIGNEDTABLE (ID INT IDENTITY(1,1),ASSIGNEDTO NVARCHAR(MAX))
	    
	     --ONLY FOR USERS
		SET @SQL='
	    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
	    SELECT UserID FROM CRM_Assignment WITH(NOLOCK) WHERE CCID='+CONVERT(NVARCHAR,@CostCenterID)+' and CCNODEID='+CONVERT(NVARCHAR,@NODEID)+'
	    AND TEAMNODEID=0 AND ISGROUP=0 AND ISROLE=0) AND Email1 NOT IN (
	    SELECT ASSIGNEDTO FROM #ASSIGNEDTABLE WITH(NOLOCK)) AND (Email1<>'''' AND   Email1 IS NOT NULL)'
		INSERT INTO #ASSIGNEDTABLE
		EXEC (@SQL)
 
		 --ONLY FOR ROLES
		SET @SQL='
	    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
	    SELECT UserID FROM ADM_USERROLEMAP WITH(NOLOCK) WHERE ROLEID IN (
	    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
	    WHERE CCID='+CONVERT(NVARCHAR,@CostCenterID)+' and CCNODEID='+CONVERT(NVARCHAR,@NODEID)+'
	    AND TEAMNODEID>0 AND ISGROUP=0 AND UserID=0 AND ISROLE=1)) AND Email1 NOT IN (
	    SELECT ASSIGNEDTO FROM #ASSIGNEDTABLE WITH(NOLOCK)) AND (Email1<>'''' AND   Email1 IS NOT NULL)'
	    INSERT INTO #ASSIGNEDTABLE
		EXEC(@SQL)
	   
	     --ONLY FOR GROUPS(ROLES)
		SET @SQL='
	    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN (
	    SELECT UserID FROM ADM_USERROLEMAP WITH(NOLOCK) WHERE ROLEID IN (
	    SELECT ROLEID FROM COM_Groups WITH(NOLOCK) WHERE UserID=0 AND GID IN (
	    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
	    WHERE CCID='+CONVERT(NVARCHAR,@CostCenterID)+' and CCNODEID='+CONVERT(NVARCHAR,@NODEID)+'
	    AND TEAMNODEID>0 AND ISGROUP=1 AND UserID=0 AND ISROLE=0))) AND Email1 NOT IN (
	    SELECT ASSIGNEDTO FROM #ASSIGNEDTABLE WITH(NOLOCK)) AND (Email1<>'''' AND   Email1 IS NOT NULL)'
		INSERT INTO #ASSIGNEDTABLE
		EXEC (@SQL)
	    
	     --ONLY FOR GROUPS(USERS)
		SET @SQL='
	    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN ( 
	    SELECT UserID FROM COM_Groups WITH(NOLOCK) WHERE ROLEID=0 AND GID IN (
	    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
	    WHERE CCID='+CONVERT(NVARCHAR,@CostCenterID)+' and CCNODEID='+CONVERT(NVARCHAR,@NODEID)+'
	    AND TEAMNODEID>0 AND ISGROUP=1 AND UserID=0 AND ISROLE=0)) AND Email1 NOT IN (
	    SELECT ASSIGNEDTO FROM #ASSIGNEDTABLE WITH(NOLOCK)) AND (Email1<>'''' AND   Email1 IS NOT NULL)'
		INSERT INTO #ASSIGNEDTABLE
		EXEC(@SQL)
	    
	     --ONLY FOR TEAM
		SET @SQL='
	    SELECT EMAIL1 FROM ADM_USERS WITH(NOLOCK) WHERE UserID IN ( 
	    SELECT UserID FROM crm_teams where    teamid     IN (
	    SELECT TEAMNODEID FROM CRM_Assignment WITH(NOLOCK)   
	    WHERE CCID='+CONVERT(NVARCHAR,@CostCenterID)+'and CCNODEID='+CONVERT(NVARCHAR,@NODEID)+'
	    AND TEAMNODEID>0 AND ISTEAM=1 AND ISGROUP=0 AND UserID=0 AND ISROLE=0)) AND Email1 NOT IN (
	    SELECT ASSIGNEDTO FROM #ASSIGNEDTABLE WITH(NOLOCK)) AND (Email1<>'''' AND   Email1 IS NOT NULL)'
		INSERT INTO #ASSIGNEDTABLE
		EXEC (@SQL)	    
			    
		select @stract =coalesce(@stract , '  ' , ' ')+ Convert(varchar(50), ASSIGNEDTO)+',' from #ASSIGNEDTABLE WITH(NOLOCK)
		if(len(@stract)>0)
			select @stract 'AssignedTo'
		else
			select null

		DROP TABLE #ASSIGNEDTABLE
	END
COMMIT TRANSACTION    
SET NOCOUNT OFF;     
RETURN 1
GO
