USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetLoanRepayAmountDetails]
	@DOCID [int],
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @CCID INT

	IF ISNULL(@DOCID,0)>0
	BEGIN
		SET @CCID=(SELECT TOP 1 COSTCENTERID FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID)
		IF(@CCID=40055)
		BEGIN
			SELECT ISNULL(SUM(LINKEDFIELDVALUE),0) TotalLoanPaidAmount  FROM INV_DOCDETAILS WITH(NOLOCK) WHERE STATUSID NOT IN (372,376) AND COSTCENTERID=40057
				   AND REFNODEID IN (SELECT INVDOCDETAILSID FROM INV_DOCDETAILS WHERE DOCID=@DOCID)
		END
		ELSE IF(@CCID=40056)
		BEGIN
			SELECT ISNULL(SUM(LINKEDFIELDVALUE),0) TotalLoanPaidAmount  FROM INV_DOCDETAILS WITH(NOLOCK) WHERE STATUSID NOT IN (372,376)
				   AND LINKEDINVDOCDETAILSID IN (SELECT INVDOCDETAILSID FROM INV_DOCDETAILS WHERE DOCID=@DOCID)
			SELECT DISTINCT ISNULL(LINKEDINVDOCDETAILSID,0) LINKEDINVDOCDETAILSID  FROM INV_DOCDETAILS WITH(NOLOCK) WHERE STATUSID NOT IN (372,376)
				   AND LINKEDINVDOCDETAILSID IN (SELECT INVDOCDETAILSID FROM INV_DOCDETAILS WHERE DOCID=@DOCID)
		END
		
		
	END
SET NOCOUNT OFF;	
END
GO
