USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetAllEmployeesList]
	@DailyAttendanceDate [datetime] = '14-MAR-2017',
	@DocID [int] = 0,
	@Dimension1 [int] = 0,
	@Dimension2 [int] = 0,
	@UserID [int] = 1,
	@LangID [int] = 1,
	@Flag [int] = 0,
	@EmpNode [int] = 0,
	@EmpList [nvarchar](max) = NULL
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @NRMLHRSOP FLOAT,@BREAKHRSOP FLOAT,@OT1OP FLOAT,@OT2OP FLOAT,@OT3OP FLOAT,@OT4OP FLOAT,@OT5OP FLOAT
DECLARE @NRMLHRSRATEOP FLOAT,@BREAKHRSRATEOP FLOAT,@OT1RATEOP FLOAT,@OT2RATEOP FLOAT,@OT3RATEOP FLOAT,@OT4RATEOP FLOAT,@OT5RATEOP FLOAT,@TOTALCOSTOP FLOAT
DECLARE @STARTTIME TIME,@ENDTIME TIME,@STARTDATETIME VARCHAR(30),@ENDDATETIME VARCHAR(30),@HOURS FLOAT
DECLARE @EXSTNRMLHRS FLOAT,@EXSTBREAKHRS FLOAT,@NORMALHRS FLOAT,@OT1HRS FLOAT,@OT2HRS FLOAT,@OT3HRS FLOAT,@OT4HRS FLOAT,@OT5HRS FLOAT
DECLARE @RC AS INT,@TRC AS INT,@EMPLOYEEID INT,@TOTALHOURS FLOAT
DECLARE @ISVALIDDAY INT,@strQuery NVARCHAR(MAX),@LEAVENODE NVARCHAR(MAX),@PrefValue BIT

DECLARE @GENERALTIMINGS TABLE(ID INT IDENTITY(1,1),STARTTIME TIME,ENDTIME TIME,LOCATION INT)
CREATE TABLE #TAB(ID INT IDENTITY(1,1),LFT INT,EMPNODE INT,EMPCODE VARCHAR(1000),EMPNAME VARCHAR(1000),DIM1 INT,DIM2 INT,STARTTIME VARCHAR(30),ENDTIME VARCHAR(30),
				   TOTALHOURS FLOAT,NRMLHRS FLOAT,BREAKHRS FLOAT,OT1 FLOAT,OT2 FLOAT,OT3 FLOAT,OT4 FLOAT,
				   OT5 FLOAT,NORMALRATE FLOAT,OT1RATE FLOAT,OT2RATE FLOAT,OT3RATE FLOAT,
				   OT4RATE FLOAT,OT5RATE FLOAT,TOTALCOST FLOAT)
DECLARE @TAB1 TABLE (EMPLOYEENODE INT,EMPLOYEENAME VARCHAR(500),NORMALHOURS FLOAT,EXSTNRMLHRS FLOAT,EXSTBREAKHRS FLOAT)
DECLARE @TAB2 TABLE (ISVALIDDAY INT,LEAVETYPENAME VARCHAR(50),LEAVETYPENODEID INT)
DECLARE @TAB3 TABLE(EMPNODE INT) 
	
	IF ISNULL(@Flag,0)=0
	BEGIN	
 
		SELECT @PrefValue=CONVERT(BIT,PrefValue) FROM com_documentpreferences WITH(NOLOCK) WHERE PrefName='DonotLoadEmployeeswhoareonLeave'
		IF @PrefValue=1
		BEGIN
			INSERT INTO @TAB3
			SELECT DISTINCT CC.dcCCNID51 From Inv_DocDetails ID with(nolock)
			Inner Join Com_DocTextData TD with(nolock) on ID.InvDocDetailsID=TD.InvDocDetailsID
			Inner Join Com_DocCCData CC with(nolock) on ID.InvDocDetailsID=CC.InvDocDetailsID
			Where   ID.DocumentType=62 And Isdate(TD.dcAlpha4)=1 And IsDate(TD.dcAlpha5)=1 AND ID.StatusID=369
			And Convert(DateTime,@DailyAttendanceDate) Between Convert(DateTime,TD.dcAlpha4) And Convert(DateTime,TD.dcAlpha5)
			UNION
			SELECT DISTINCT CC.dcCCNID51  FROM Inv_DocDetails ID with(nolock) 
			join Com_DocTextData TD with(nolock) on ID.InvDocDetailsID=TD.InvDocDetailsID
			JOIN Com_DocCCData CC WITH(NOLOCK) ON ID.InvDocDetailsID=CC.InvDocDetailsID
			WHERE ID.COSTCENTERID=40072 
			AND isnull(TD.DCALPHA16,'')='No' AND Isdate(TD.dcAlpha2)=1 And IsDate(TD.dcAlpha3)=1
			AND Convert(DateTime,@DailyAttendanceDate) Between Convert(DateTime,TD.dcAlpha2) And Convert(DateTime,TD.dcAlpha3)
			AND ID.StatusID=369
		END

		SELECT @LEAVENODE=STUFF((SELECT ','+ convert(nvarchar,EMPNODE) FROM @TAB3 FOR XML PATH('')),1,1,'') 

		IF(ISNULL(@EmpList,'')='')
		BEGIN

			IF(ISNULL(@LEAVENODE,'')='')
			BEGIN
				INSERT INTO #TAB
				SELECT C51.LFT,C51.NODEID,C51.CODE,C51.NAME,1,1,'','',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM COM_CC50051 C51 WITH(NOLOCK)
				WHERE C51.ISGROUP=0 AND C51.NODEID<>1 AND C51.StatusID=250
				AND ISNULL(CONVERT(DATETIME,C51.DORelieve),'01-Jan-9000')>= CONVERT(DATETIME,@DailyAttendanceDate)
				AND CONVERT(DATETIME,C51.DOJ)<=CONVERT(DATETIME,@DailyAttendanceDate)
			END
			ELSE
			BEGIN
				SET @strQuery=''
				SET @strQuery=@strQuery + 'INSERT INTO #TAB  
											SELECT a.LFT,a.NODEID,a.CODE,a.NAME,1,1,'''','''',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM COM_CC50051 a WITH(NOLOCK) 
											WHERE a.ISGROUP=0 AND a.NODEID<>1 AND a.StatusID=250
											AND ISNULL(CONVERT(DATETIME,a.DORelieve),''01-Jan-9000'')>= CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''')
											AND CONVERT(DATETIME,a.DOJ)<=CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''') 
											AND a.NodeId NOT IN ('+ CONVERT(NVARCHAR(MAX),@LEAVENODE) +')'
				PRINT (@strQuery)
				EXEC sp_executesql @STRQUERY
			END
		END
		ELSE
		BEGIN

			IF(ISNULL(@LEAVENODE,'')='')
			BEGIN
				SET @strQuery=''
				SET @strQuery=@strQuery + 'INSERT INTO #TAB  SELECT a.LFT,a.NODEID,a.CODE,a.NAME,1,1,'''','''',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM COM_CC50051 a WITH(NOLOCK) 
											WHERE a.ISGROUP=0 AND a.NODEID<>1 AND a.StatusID=250
											AND ISNULL(CONVERT(DATETIME,a.DORelieve),''01-Jan-9000'')>= CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''')
											AND CONVERT(DATETIME,a.DOJ)<=CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''') 
											AND '+ CONVERT(NVARCHAR(MAX),@EmpList) +''
				PRINT (@strQuery)
				EXEC sp_executesql @STRQUERY
			END
			ELSE
			BEGIN
				SET @strQuery=''
				SET @strQuery=@strQuery + 'INSERT INTO #TAB  SELECT a.LFT,a.NODEID,a.CODE,a.NAME,1,1,'''','''',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM COM_CC50051 a WITH(NOLOCK) 
											WHERE a.ISGROUP=0 AND a.NODEID<>1 AND a.StatusID=250
											AND ISNULL(CONVERT(DATETIME,a.DORelieve),''01-Jan-9000'')>= CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''')
											AND CONVERT(DATETIME,a.DOJ)<=CONVERT(DATETIME,'''+CONVERT(NVARCHAR,@DailyAttendanceDate)+''') 
											AND '+ CONVERT(NVARCHAR(MAX),@EmpList) + ' AND a.NodeId NOT IN ('+ CONVERT(NVARCHAR(MAX),@LEAVENODE) +')'
				PRINT (@strQuery)
				EXEC sp_executesql @STRQUERY
			END
		END
		SELECT * FROM #TAB
	END
	ELSE IF ISNULL(@Flag,0)=1
	BEGIN
	SET @EMPLOYEEID=@EmpNode
		--START LOADING DATA FROM HOURS CHART FOR SPECIFIED DIMENSIONS			        
		DECLARE @STRHDCDIMENSIONS VARCHAR(MAX),@P INT,@PTR INT,@ColumnJoin NVARCHAR(MAX),@DefColumnJoin NVARCHAR(MAX),@ControlType Varchar(2),@HISTORYCCID INT,@DIMNAME NVARCHAR(MAX)
		CREATE TABLE #HoursChart (ID INT IDENTITY(1,1),NORMALHRS FLOAT,OT1HRS FLOAT,OT2HRS FLOAT,OT3HRS FLOAT,OT4HRS FLOAT,OT5HRS FLOAT)
		CREATE TABLE #HoursChartTab (ID INT IDENTITY(1,1),USERDIMENSIONNAME VARCHAR(100),SYSDIMENSIONNAME VARCHAR(MAX),SEQUENCE INT,DIMENSIONVALUE INT
							 ,CONTROLTYPE VARCHAR(2),COSTCENTERID INT)
		INSERT INTO #HoursChartTab
				SELECT USERCOLUMNNAME,REPLACE(SYSCOLUMNNAME,'DC',''),SECTIONSEQNUMBER,0,'',PARENTCOSTCENTERID
					   FROM ADM_COSTCENTERDEF WHERE COSTCENTERID=40066 AND SYSCOLUMNNAME LIKE 'dcCCNID%' AND USERCOLUMNNAME NOT LIKE 'dcCCNID%' AND ISCOLUMNINUSE=1
				UPDATE H SET H.CONTROLTYPE=A.USERPROBABLEVALUES FROM #HoursChartTab H,ADM_COSTCENTERDEF A WHERE A.COSTCENTERID=50051 AND 
					   A.SYSCOLUMNNAME=H.SYSDIMENSIONNAME AND SYSCOLUMNNAME LIKE 'CCNID%' AND USERCOLUMNNAME NOT LIKE 'CCNID%' AND ISCOLUMNINUSE=1
		SET @STRHDCDIMENSIONS=''
		SET @ColumnJoin=''
		SET @DefColumnJoin=''
		SET @ControlType=''
		SET @P=1
		SELECT @PTR=COUNT(*) FROM #HoursChartTab 
		WHILE (@P<=@PTR)
		BEGIN	
			SELECT @DIMNAME=REPLACE(SYSDIMENSIONNAME,'dc',''),@ControlType=CONTROLTYPE,@HISTORYCCID=COSTCENTERID FROM #HoursChartTab WHERE ID=@P
			SET @STRHDCDIMENSIONS= @STRHDCDIMENSIONS +' AND DC.'+ @DIMNAME +'=C.'+ @DIMNAME
			SET @STRQUERY=''
			IF(@ControlType='H')
				SET @STRQUERY='DECLARE @VALUE INT SET @VALUE=(SELECT ISNULL(HistoryNodeID,0) FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID='+ CONVERT(VARCHAR,@EmployeeID)+' AND CostCenterID=50051 AND HistoryCCID='+ CONVERT(VARCHAR,@HISTORYCCID)+' AND (CONVERT(DATETIME,FromDate)<='''+ convert(VARCHAR,@DailyAttendanceDate,106)+''') AND (CONVERT(DATETIME,ToDate)>='''+ convert(VARCHAR,@DailyAttendanceDate,106)+''' OR ToDate IS NULL))  '
			ELSE
				SET @STRQUERY='DECLARE @VALUE INT SET @VALUE=(SELECT '+ @DIMNAME +' FROM COM_CCCCDATA  WHERE COSTCENTERID=50051 AND NODEID='+ CONVERT(VARCHAR,@EmployeeID)+')  '
			
			SET @STRQUERY=@STRQUERY+' UPDATE #HoursChartTab SET DIMENSIONVALUE=@VALUE WHERE REPLACE(SYSDIMENSIONNAME,''DC'','''')='''+ CONVERT(VARCHAR,@DIMNAME) +''''
			PRINT @STRQUERY
			EXEC sp_executesql @STRQUERY
			IF(@DIMNAME='CCNID51')
				SET @ColumnJoin=@ColumnJoin+ ' AND DC.DC' + @DIMNAME+'='+CONVERT(VARCHAR,@EmployeeID)
			ELSE
				SET @ColumnJoin=@ColumnJoin+ ' AND DC.DC' + @DIMNAME+'='+(SELECT CONVERT(VARCHAR,DIMENSIONVALUE) FROM #HoursChartTab WHERE ID=@P)
				
				SET @DefColumnJoin =@DefColumnJoin+ ' AND DC.DC' + @DIMNAME+'=1'
		SET @P=@P+1
		END
		--SELECT * FROM #HoursChartTab
		--END LOADING DATA FROM HOURS CHART FOR SPECIFIED DIMENSIONS	
		SET @STRQUERY=''
		--FOR DAILY ATTENDANCE
		--NORMAL WORKING HOURS FOR SPECIFIED EMPLOYEE
			SET @STRQUERY='INSERT INTO #HoursChart SELECT top 1 ISNULL(TD.dcAlpha1,0),ISNULL(TD.dcAlpha8,0),ISNULL(TD.dcAlpha9,0),ISNULL(TD.dcAlpha10,0),ISNULL(TD.dcAlpha11,0),ISNULL(TD.dcAlpha12,0) FROM INV_DOCDETAILS ID WITH(NOLOCK), COM_DocCCData DC WITH(NOLOCK),COM_DocTextData TD WITH(NOLOCK) WHERE ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND DC.INVDOCDETAILSID=TD.INVDOCDETAILSID 
				   '+ CONVERT(VARCHAR(MAX),@ColumnJoin) +' AND ID.COSTCENTERID=40066 AND ID.STATUSID =369 AND ISDATE(TD.dcAlpha6)=1  AND CONVERT(DATETIME,TD.dcAlpha6)<= '''+ convert(VARCHAR,@DailyAttendanceDate,106)+''' ORDER BY CONVERT(DATETIME,TD.dcAlpha6) DESC  '
			EXEC sp_executesql @STRQUERY   
		IF((SELECT COUNT(*) FROM #HoursChart)>0)
		BEGIN
			--IF NODATA FOUND THEN RETRIEVING NORMAL WORKING HOURS OF DEFAULT EMPLOYEE
			SET @STRQUERY='INSERT INTO #HoursChart SELECT top 1 ISNULL(TD.dcAlpha1,0),ISNULL(TD.dcAlpha8,0),ISNULL(TD.dcAlpha9,0),ISNULL(TD.dcAlpha10,0),ISNULL(TD.dcAlpha11,0),ISNULL(TD.dcAlpha12,0) FROM INV_DOCDETAILS ID WITH(NOLOCK), COM_DocCCData DC WITH(NOLOCK),COM_DocTextData TD WITH(NOLOCK) WHERE ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND DC.INVDOCDETAILSID=TD.INVDOCDETAILSID 
			   '+ CONVERT(VARCHAR(MAX),@DefColumnJoin) +' AND ID.COSTCENTERID=40066 AND ID.STATUSID =369 AND ISDATE(TD.dcAlpha6)=1  AND CONVERT(DATETIME,TD.dcAlpha6)<= '''+ convert(VARCHAR,@DailyAttendanceDate,106)+''' ORDER BY CONVERT(DATETIME,TD.dcAlpha6) DESC  '
			EXEC sp_executesql @STRQUERY
		END
		--SELECT * FROM #HoursChart
		SELECT @NORMALHRS=ISNULL(NORMALHRS,0),@OT1HRS=ISNULL(OT1HRS,0),@OT2HRS=ISNULL(OT2HRS,0),@OT3HRS=ISNULL(OT3HRS,0),@OT4HRS=ISNULL(OT4HRS,0),@OT5HRS=ISNULL(OT5HRS,0) FROM #HoursChart
		
		IF ISNULL(@EmpNode,0)>0
		BEGIN
			INSERT INTO @TAB1 
			SELECT DC.DCCCNID51,EMP.NAME,ISNULL(@NORMALHRS,0),ISNULL(SUM(DN.DCNUM2),0),isnull(SUM(DN.DCNUM4),0) FROM INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA DC WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_CC50051 EMP WITH(NOLOCK) WHERE ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
				   AND DC.DCCCNID51=EMP.NodeID AND ID.COSTCENTERID=40067 AND DC.DCCCNID51=@EmpNode AND ISDATE(TD.DCALPHA1)=1  AND CONVERT(DATETIME,TD.dcAlpha1)= CONVERT(DATETIME,@DailyAttendanceDate)
				   GROUP BY DC.DCCCNID51,EMP.NAME
		END  
		ELSE
		BEGIN
			INSERT INTO @TAB1 
			SELECT DC.DCCCNID51,EMP.NAME,ISNULL(@NORMALHRS,0),ISNULL(SUM(DN.DCNUM2),0),isnull(SUM(DN.DCNUM4),0) FROM INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA DC WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_CC50051 EMP WITH(NOLOCK) WHERE ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=DC.INVDOCDETAILSID AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
				   AND DC.DCCCNID51=EMP.NodeID AND ID.COSTCENTERID=40067 AND ISDATE(TD.DCALPHA1)=1 AND CONVERT(DATETIME,TD.dcAlpha1)= CONVERT(DATETIME,@DailyAttendanceDate)
				   GROUP BY DC.DCCCNID51,EMP.NAME
		END
		SELECT * FROM @TAB1	
		SELECT 0 EMPLOYEENODE,'' EMPLOYEENAME,ISNULL(@NORMALHRS,0) NORMALHOURS,0 as EXSTNRMLHRS,0 as EXSTBREAKHRS,@OT1HRS as OT1HRS,@OT2HRS as OT2HRS,@OT3HRS as OT3HRS,@OT4HRS as OT4HRS,@OT5HRS as OT5HRS
			
		--FOR POSTED MONTH DATA FROM MONTHLY PAYROLL
		IF((Select  COUNT(*)  From Inv_DocDetails ID with(nolock) join Com_DocTextData TD with(nolock) on ID.InvDocDetailsID=TD.InvDocDetailsID
				JOIN Com_DocCCData CC WITH(NOLOCK) ON ID.InvDocDetailsID=CC.InvDocDetailsID
				Where ID.CostCenterId=40054 And Isdate(TD.dcAlpha17)=1 And IsDate(TD.dcAlpha18)=1 AND CC.DCCCNID51=@EmpNode
			    And Convert(DateTime,@DailyAttendanceDate) Between Convert(DateTime,TD.dcAlpha17) And Convert(DateTime,TD.dcAlpha18))>0)
		BEGIN
			SELECT 'Cannot save the record, Payroll processed for the selected month' as PayrollProcessedMessage
		END
		ELSE
		BEGIN
			SELECT '' as PayrollProcessedMessage
		END
		--FOR VACATION DATA FROM APPLY VACATION / FOR LEAVES DATA FROM APPLIED LEAVES
		IF ((SELECT count(*)  FROM Inv_DocDetails ID with(nolock) join Com_DocTextData TD with(nolock) on ID.InvDocDetailsID=TD.InvDocDetailsID
				JOIN Com_DocCCData CC WITH(NOLOCK) ON ID.InvDocDetailsID=CC.InvDocDetailsID
		WHERE  CC.DCCCNID51=@EmpNode AND ID.COSTCENTERID=40072 
		AND isnull(TD.DCALPHA16,'')='No' AND Isdate(TD.dcAlpha2)=1 And IsDate(TD.dcAlpha3)=1
		AND Convert(DateTime,@DailyAttendanceDate) Between Convert(DateTime,TD.dcAlpha2) And Convert(DateTime,TD.dcAlpha3)
		AND ID.StatusID=369)>0)
		BEGIN
			SELECT 'Employee on vacation, Cannot save the record' as LeaveMessage
		END	
		ELSE IF ((Select  COUNT(ID.DocID) AppliedLeavesCnt From Inv_DocDetails ID with(nolock)
				Inner Join Com_DocTextData TD with(nolock) on ID.InvDocDetailsID=TD.InvDocDetailsID
				Inner Join Com_DocCCData CC with(nolock) on ID.InvDocDetailsID=CC.InvDocDetailsID
				Where   ID.DocumentType=62 And CC.dcCCnid51=@EmpNode And Isdate(TD.dcAlpha4)=1 And IsDate(TD.dcAlpha5)=1 AND ID.StatusID not in (372,376)
			    And Convert(DateTime,@DailyAttendanceDate) Between Convert(DateTime,TD.dcAlpha4) And Convert(DateTime,TD.dcAlpha5))>0)						    
		BEGIN
			SELECT 'Employee on leave, Cannot save the record' as LeaveMessage
		END		
		ELSE
		BEGIN
			SELECT '' as LeaveMessage
		END
		DROP TABLE #HoursChart			   
		DROP TABLE #HoursChartTab	
	END
DROP TABLE #TAB
SET NOCOUNT OFF;
END

----spPAY_GetAllEmployeesList 
-- '7/26/2018 11:43:41 AM'
-- ,0
-- ,0
-- ,0
-- ,1
-- ,1
-- ,1
-- ,433
-- ,''
GO
