USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_FillIncomeTaxComponents1]
	@FLAG [int] = 0,
	@YEAR [int] = 0,
	@EMPNODE [int] = 0,
	@USERID [int] = 1,
	@LANGID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	IF ISNULL(@FLAG,0)=0
	BEGIN
			DECLARE @TAB TABLE(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,
							   NODEID INT,NAME VARCHAR(200),ISGROUP INT,
							   CONTROLTYPE VARCHAR(50),FIELDTYPE VARCHAR(100),CONTROLTEXTDISPLAY VARCHAR(30),GROUPID INT,AMOUNTLIMIT VARCHAR(100),AMOUNT decimal(9,2),ISSELECTED INT)
			
			
			INSERT INTO @TAB
				SELECT CCALPHA3 ORDERNO,PARENTID,NODEID,NAME,ISGROUP,ISNULL(CCALPHA1,'LABEL') AS CONTROLTYPE,CCALPHA2 AS FILEDTYPE,'LABEL' AS CONTROLTEXTDISPLAY,'','',0,0 FROM COM_CC50052 WITH(NOLOCK) WHERE   LFT >=39 AND RGT<=126 AND CCALPHA3 IS NOT NULL  GROUP BY NODEID,NAME,PARENTID,ISGROUP,CCALPHA3,CCALPHA1,CCALPHA2-- ORDER BY CCALPHA3
				UPDATE @TAB SET AMOUNTLIMIT =1000 WHERE ISGROUP=0
			
			UPDATE @TAB SET NAME ='      '+ NAME WHERE ISGROUP=0
			UPDATE T SET T.NAME ='   '+ T.NAME FROM @TAB T1 INNER JOIN @TAB T ON T1.NODEID=T.PARENTID AND T1.ISGROUP=1 AND T.ISGROUP=1
			UPDATE @TAB SET CONTROLTYPE ='LABEL' WHERE (CONTROLTYPE='' OR CONTROLTYPE='None')
			
			UPDATE T SET T.GROUPID =T1.NODEID FROM @TAB T1 INNER JOIN @TAB T ON T1.NODEID=T.PARENTID
			
			
			update @tab set controltype='COMBOTEXTVALUE' where controltype='RadioButton'
			
			if ((select count(*) from PAY_EmpTaxDeclaration where year=@year and EMPNODE=@EMPNODE)>0)
			begin
				UPDATE T SET T.amount =T1.amount,T.ISSELECTED =t1.componentid FROM PAY_EmpTaxDeclaration T1 INNER JOIN @TAB T ON T1.componentid=T.nodeid and t1.year=@year and t1.EMPNODE=@EMPNODE		
			end
			
			update @tab set amountlimit='200' where nodeid=52
			
			SELECT * FROM @TAB
			select * from PAY_EmpTaxHRAInfo WITH(NOLOCK) where  year=@year and EMPNODE=@EMPNODE
	END
	ELSE IF ISNULL(@FLAG,0)=1
	BEGIN
			DECLARE @TAB1 TABLE(ID INT IDENTITY(1,1),ORDERNO INT,PARENTID INT,
							   NODEID INT,NAME VARCHAR(200),ISGROUP INT,
							   CONTROLTYPE VARCHAR(50),FIELDTYPE VARCHAR(100),CONTROLTEXTDISPLAY VARCHAR(30),GROUPID INT,AMOUNTLIMIT VARCHAR(100))
			
			
			INSERT INTO @TAB1
				SELECT CCALPHA3 ORDERNO,PARENTID,NODEID,NAME,ISGROUP,ISNULL(CCALPHA1,'LABEL') AS CONTROLTYPE,CCALPHA2 AS FILEDTYPE,'LABEL' AS CONTROLTEXTDISPLAY,'','0' FROM COM_CC50052 WITH(NOLOCK) WHERE   LFT >=39 AND RGT<=126 AND CCALPHA3 IS NOT NULL  GROUP BY NODEID,NAME,PARENTID,ISGROUP,CCALPHA3,CCALPHA1,CCALPHA2-- ORDER BY CCALPHA3
				
			
			UPDATE @TAB1 SET NAME ='      '+ NAME WHERE ISGROUP=0
			UPDATE T SET T.NAME ='   '+ T.NAME FROM @TAB1 T1 INNER JOIN @TAB1 T ON T1.NODEID=T.PARENTID AND T1.ISGROUP=1 AND T.ISGROUP=1
			UPDATE @TAB1 SET CONTROLTYPE ='LABEL' WHERE (CONTROLTYPE='' OR CONTROLTYPE='None')
			
			UPDATE T SET T.GROUPID =T1.NODEID FROM @TAB1 T1 INNER JOIN @TAB1 T ON T1.NODEID=T.PARENTID
			
			
			update @tab1 set controltype='TextBox' where controltype='RadioButton'
			if ((select count(*) from PAY_YearwiseTaxAmountLimit where year=@year)>0)
			begin
				UPDATE T SET T.amountlimit =T1.amountlimit FROM PAY_YearwiseTaxAmountLimit T1 INNER JOIN @TAB1 T ON T1.componentid=T.nodeid and t1.year=@year	
			end
			SELECT * FROM @TAB1

	END
END
GO
