USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCRM_GetUsersOnLeave]
	@ASONDATE [datetime],
	@UserID [int],
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS

BEGIN TRY	
SET NOCOUNT ON

CREATE TABLE #T1(ID INT IDENTITY(1,1),UserID int,UserName NVARCHAR(500),NodeID BIGINT,Onleave BIT)
DECLARE @TEmpSeqNo BIGINT,@I INT,@CNT INT
                    
INSERT INTO #T1
SELECT DISTINCT a.UserID,A.UserName,C.NodeID,'' FROM ADM_Users A WITH(NOLOCK)
JOIN COM_CC50051 C WITH(NOLOCK) ON C.LoginUserID=A.UserName

SET @I=1
SELECT @CNT=COUNT(*) FROM #T1 WITH(NOLOCK)

WHILE(@I<=@CNT)
BEGIN
SELECT @TEmpSeqNo=NODEID FROM #T1 WITH(NOLOCK) WHERE ID=@I

IF EXISTS(SELECT TOP 1 *
FROM INV_DocDetails a WITH(NOLOCK) 
JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
WHERE a.DocumentType=62 and a.StatusID=369 AND ISDATE(ISNULL(dcAlpha4,''))=1 AND ISDATE(ISNULL(dcAlpha5,''))=1 
AND b.dcCCNID51=@TEmpSeqNo AND @ASONDATE BETWEEN CONVERT(DATETIME,dcAlpha4) AND CONVERT(DATETIME,dcAlpha5))
BEGIN
	UPDATE #T1 SET Onleave=1 WHERE ID=@I AND NodeID=@TEmpSeqNo
END
SET @I=@I+1
END

SELECT * FROM #T1 WITH(NOLOCK) WHERE Onleave=1

DROP TABLE #T1


SET NOCOUNT OFF;
RETURN 1
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END

SET NOCOUNT OFF  
RETURN -999   
END CATCH
GO
