USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_PostLoanRepayment]
	@DocID [int] = null,
	@UserId [int] = 1,
	@LangId [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @REFDOCDETAILSD INT,@LINKSTATUSID INT,@INVDOCDETAILSID INT,@LINKEDINVDOCDETAILSID INT,@LINKEDFIELDNAME NVARCHAR(100),@LINKEDFIELDVALUE FLOAT,@REFNO NVARCHAR(100)
DECLARE @TOTLOANAMOUNT FLOAT,@OPBAMOUNT FLOAT,@INSTAMOUNT FLOAT,@DEDMONTH DATETIME,@EMPNODE INT,@LOANID INT,@DOCDATE DATETIME
DECLARE @R INT,@TRC INT,@I INT,@DOCUMENTID INT,@ActXml nvarchar(max),@sysinfo nvarchar(max),@AP varchar(10)
DECLARE @J INT,@RC INT
DECLARE @strQuery Nvarchar(max)
DECLARE @strResult VARCHAR(100),@dcAlpha1 VARCHAR(10),@dcAlpha2 VARCHAR(10),@dcAlpha3 VARCHAR(10),@dcAlpha4 DATETIME
DECLARE @dcAlpha5 DATETIME
DECLARE @PAIDAMOUNT FLOAT,@PAIDINS FLOAT,@PAIDINSTAMOUNT FLOAT,@PAIDBALAMOUNT FLOAT,@PayrollProduct INT,@CrACC INT,@DbAcc INT,@CCID INT
	
DECLARE @TAB TABLE(ID INT IDENTITY(1,1),EMPNODE INT,LOANID INT,INVDOCDETAILSID INT,TOTLOANAMOUNT FLOAT,OPBAMOUNT FLOAT,INSTAMOUNT FLOAT,DEDMONTH DATETIME,DOCDATE DATETIME)

IF((SELECT COUNT(DocID) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID AND STATUSID=369)>0)
BEGIN
	SELECT @PayrollProduct=ISNULL(VALUE,2) FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='payrollproduct'
	
	set @ActXml=''

	SELECT TOP 1 @CCID=COSTCENTERID, @sysinfo=D.SysInfo,@AP=I.AP
	FROM INV_DOCDETAILS i WITH(NOLOCK) 
	join COM_DocID d	WITH(NOLOCK) ON D.DocNo=I.VoucherNo
	WHERE DOCID=@DocID

	set @ActXml='<XML SysInfo="'+@sysinfo+'" AP="'+@AP+'" ></XML>'

	SELECT @CrACC=ISNULL(UserDefaultValue,2) FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=@CCID AND SYSCOLUMNNAME='CreditAccount'
	SELECT @DbAcc=ISNULL(UserDefaultValue,2) FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=@CCID AND SYSCOLUMNNAME='DebitAccount'
	
	--LOADING DATA FROM LOAN OPENING BALANCE
	INSERT INTO @TAB SELECT CC.DCCCNID51,CC.DCCCNID52,ID.INVDOCDETAILSID,DN.DCNUM1,DN.DCNUM2,DN.DCNUM3,CONVERT(DATETIME,TD.DCALPHA1),CONVERT(DATETIME,ID.DOCDATE)
					 FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON DN.INVDOCDETAILSID=ID.INVDOCDETAILSID INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON TD.INVDOCDETAILSID=ID.INVDOCDETAILSID
					 INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON CC.INVDOCDETAILSID=ID.INVDOCDETAILSID  WHERE ID.DOCID=@DocID			
	SET @R=1
	SELECT @TRC=COUNT(*) FROM @TAB
	WHILE(@R<=@TRC)
	BEGIN
		SELECT @EMPNODE=EMPNODE,@LOANID=LOANID,@DOCDATE=DOCDATE,@INVDOCDETAILSID=INVDOCDETAILSID,@TOTLOANAMOUNT=TOTLOANAMOUNT,@OPBAMOUNT=OPBAMOUNT,@INSTAMOUNT=INSTAMOUNT,@DEDMONTH=DEDMONTH FROM @TAB WHERE ID=@R
		--READING DOCDETAILSID OF APPLY LOAN  FROM REFNODEID OF LOAN OPENING BALANCE
		SELECT @REFDOCDETAILSD=INVDOCDETAILSID FROM INV_DOCDETAILS WITH(NOLOCK) WHERE REFNODEID=@INVDOCDETAILSID AND COSTCENTERID=40056
		--READING DOCID OF APPLY LOAN
		SET @DOCUMENTID=(SELECT TOP 1 DOCID FROM INV_DOCDETAILS WITH(NOLOCK) WHERE INVDOCDETAILSID=@REFDOCDETAILSD)

		IF(@TOTLOANAMOUNT<>@OPBAMOUNT)
		BEGIN
			SET @PAIDAMOUNT=@TOTLOANAMOUNT-@OPBAMOUNT
			SET @PAIDINS= ROUND(@PAIDAMOUNT/@INSTAMOUNT,0) 
			--SET @PAIDINS=@PAIDAMOUNT/@INSTAMOUNT

			
			--UPDATING THE INSTALLMENT AMOUNT TO ZERO OF APPLY LOAN PREVIOUS RECORDS BASED ON AMOUNT PAID AND INSTALLMENTS FROM LOAN OPENING BALANCE
			UPDATE DN SET DN.DCNUM2=@INSTAMOUNT FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocCCData CC WITH(NOLOCK) ON CC.INVDOCDETAILSID=ID.INVDOCDETAILSID INNER JOIN COM_DocNumData DN WITH(NOLOCK) ON DN.INVDOCDETAILSID=ID.INVDOCDETAILSID
					  WHERE ID.COSTCENTERID=40056 AND DN.DCNUM1<=@PAIDINS  AND CC.DCCCNID51=@EMPNODE AND CC.DCCCNID52=@LOANID AND ID.DOCID=@DOCUMENTID
					  
			SET @J=1
			SET @PAIDBALAMOUNT=0
			set @strQuery=''
			WHILE(@J<=@PAIDINS)
			BEGIN
				--POSTING THE RECORD TO LOAN REPAYMENT DOCUMENT
				SELECT @LINKEDINVDOCDETAILSID=ID.INVDOCDETAILSID,@LINKEDFIELDNAME='dcNum3',@LINKEDFIELDVALUE=@INSTAMOUNT,@REFNO=ID.VOUCHERNO,@DEDMONTH=CONVERT(DATETIME,TD.DCALPHA6)
				FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DOCNUMDATA DN WITH(NOLOCK) ON DN.INVDOCDETAILSID=ID.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON CC.INVDOCDETAILSID=ID.INVDOCDETAILSID INNER JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID  WHERE TD.tCostCenterID=40056
					 AND DN.DCNUM1=@J AND ID.DOCID=@DOCUMENTID AND CC.DCCCNID51=@EMPNODE AND CC.DCCCNID52=@LOANID
													
				SET @dcAlpha1=''
				SET @dcAlpha2=''
				SET @dcAlpha3=''
				SET @dcAlpha4=''
				SET @dcAlpha5=''
				
				SET @dcAlpha1=@TOTLOANAMOUNT
				SET @dcAlpha3=@PAIDAMOUNT
				SET @dcAlpha4=DATEADD(MONTH,0,@DEDMONTH)
				SET @dcAlpha5=DATEADD(MONTH,0,@DEDMONTH)
				
				IF (@J=1)
				BEGIN
					SET @dcAlpha2=@TOTLOANAMOUNT--@OPBAMOUNT
					SET @PAIDBALAMOUNT=@TOTLOANAMOUNT-@INSTAMOUNT
				END
				ELSE
				BEGIN
					SET @dcAlpha2=@PAIDBALAMOUNT--@OPBAMOUNT
					SET @PAIDBALAMOUNT=@PAIDBALAMOUNT-@INSTAMOUNT
				END				
				
				set @strQuery=@strQuery+'<Row>'
				set @strQuery=@strQuery+'<AccountsXML></AccountsXML>'					
				set @strQuery=@strQuery+'<Transactions DocSeqNo="'+ CONVERT(VARCHAR,@J)  +'"  DocDetailsID="0" '
				set @strQuery=@strQuery+'LinkedInvDocDetailsID="'+ CONVERT(VARCHAR,@LINKEDINVDOCDETAILSID) +'"' 
				set @strQuery=@strQuery+' LinkedFieldName="'+ CONVERT(VARCHAR,@LINKEDFIELDNAME) +'" '
				set	@strQuery=@strQuery+' ProductID="'+ CONVERT(VARCHAR,@PayrollProduct) +'" '
				set @strQuery=@strQuery+' IsScheme="" Quantity="1" Unit="1" UOMConversion="1" UOMConvertedQty="1" Rate="0" Gross="0" '
				set @strQuery=@strQuery+'RefNO="'+ CONVERT(VARCHAR,@REFNO) +'" '
				set @strQuery=@strQuery+'LineNarration="" '
				set @strQuery=@strQuery+'LinkedFieldValue="'+ CONVERT(VARCHAR,@LINKEDFIELDVALUE) +'" '
				set @strQuery=@strQuery+'IsQtyIgnored="1" AverageRate="0" StockValue="0" StockValueFC="0" CurrencyID="1" ExchangeRate="1"  '
				set @strQuery=@strQuery+' DebitAccount="'+ CONVERT(VARCHAR,@DbAcc) +'" '
				set @strQuery=@strQuery+' CreditAccount="'+ CONVERT(VARCHAR,@CrACC) +'" '
				set @strQuery=@strQuery+' ></Transactions>'
			
				set @strQuery=@strQuery+'<Numeric Query="dcNum1=N'''+ CONVERT(VARCHAR,@J)  +''','
				set @strQuery=@strQuery+' dcCalcNum1=N'''+ CONVERT(VARCHAR,@J)  +''','
				set @strQuery=@strQuery+' dcNum2=N'''+ CONVERT(VARCHAR,@INSTAMOUNT) +''','
				set @strQuery=@strQuery+' dcCalcNum2=N'''+ CONVERT(VARCHAR,@INSTAMOUNT)  +''','
				set @strQuery=@strQuery+' dcNum3=N'''+ CONVERT(VARCHAR,@INSTAMOUNT) +''','
				set @strQuery=@strQuery+' dcCalcNum3=N'''+ CONVERT(VARCHAR,@INSTAMOUNT)  +''''
				set @strQuery=@strQuery+' , "></Numeric>'
				
				set @strQuery=@strQuery+'<Alpha Query="dcAlpha1=N'''+ CONVERT(VARCHAR,@dcAlpha1)  +''','
				set @strQuery=@strQuery+' dcAlpha2=N'''+ CONVERT(VARCHAR,@dcAlpha2)  +''','
				set @strQuery=@strQuery+' dcAlpha3=N'''+ CONVERT(VARCHAR,@dcAlpha3) +''','
				set @strQuery=@strQuery+' dcAlpha4=N'''+ CONVERT(VARCHAR,@dcAlpha4) +''','
				set @strQuery=@strQuery+' dcAlpha5=N'''+ CONVERT(VARCHAR,@dcAlpha5) +''''
				set @strQuery=@strQuery+' , "></Alpha>'
				
				set @strQuery=@strQuery+'<CostCenters Query="dcCCNID52='+ CONVERT(VARCHAR,@LOANID) +','
				set @strQuery=@strQuery+' dcCCNID51='+ CONVERT(VARCHAR,@EMPNODE) +', " ></CostCenters>'									
				set @strQuery=@strQuery+'<EXTRAXML></EXTRAXML></Row>'									
			SET @J=@J+1					
			END
			print 'fd'
				PRINT (@strQuery)
				set @strResult=''
				EXEC @strResult=spDOC_SetTempInvDoc 40057,0,'','',@DOCDATE,'','',@strQuery ,'','','',@ActXml,'false',0,0,0,1,'',0,0,'admin','admin',1,1,False
				IF(ISNULL(@strResult,'')<>'')
				BEGIN
					UPDATE INV_DOCDETAILS SET STATUSID=369,REFCCID=300,REFNODEID=@INVDOCDETAILSID,LINKSTATUSID=369 WHERE DOCID=CONVERT(INT,@strResult) AND COSTCENTERID=40057
				END
		END
	SET @R=@R+1	
	END
END
SET NOCOUNT OFF;	
END

GO
