USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_ExtGetAppliedEncashLeaves]
	@EmployeeID [int],
	@LeaveType [int],
	@AvailableDays [decimal](9, 2),
	@MaxEncashDays [int],
	@AppliedEncashDays [decimal](9, 2),
	@Date [datetime],
	@DocID [int] = 0,
	@Userid [int] = 1,
	@Langid [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
		DECLARE @ExstAppliedEncashdays DECIMAL(9,2),@TotalEncashDays DECIMAL(9,2),@RETURNVALUE INT,@DocDays float
		DECLARE @ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME
		SET @RETURNVALUE=0
		
		----FOR START DATE AND END DATE OF LEAVEYEAR	
		EXEC [spPAY_EXTGetLeaveyearDates] @Date,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT
		print @ALStartMonthYear
		print @ALEndMonthYear
		
		SELECT @ExstAppliedEncashdays=sum(CONVERT(decimal(9,2),TD.DCALPHA3))
		FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID JOIN COM_DocNumData DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
			   JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
		WHERE  ISNUMERIC(TD.DCALPHA3)=1 AND CONVERT(DATETIME,@Date) between CONVERT(DATETIME,@ALStartMonthYear) and CONVERT(DATETIME,@ALEndMonthYear)
			   AND ID.COSTCENTERID=40058 AND ID.STATUSID NOT IN (372,376) AND DC.DCCCNID51=@EmployeeID AND DC.DCCCNID52=@LeaveType
		SET @TotalEncashDays=ISNULL(@ExstAppliedEncashdays,0)+ISNULL(@AppliedEncashDays,0)
		IF(@DocID>0)
		BEGIN
			SELECT @DocDays=sum(CONVERT(decimal(9,2),TD.DCALPHA3))
			FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
			       JOIN COM_DocNumData DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID
			       JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
			WHERE  ISNUMERIC(TD.DCALPHA3)=1 AND ID.COSTCENTERID=40058 AND ID.STATUSID NOT IN (372,376) AND DC.DCCCNID51=@EmployeeID AND DC.DCCCNID52=@LeaveType AND ID.DOCID=@DocID
			SET @TotalEncashDays=ISNULL(@TotalEncashDays,0)-ISNULL(@DocDays,0)
		END
		
		IF (ISNULL(@TotalEncashDays,0)>0)
		BEGIN
				IF (@AppliedEncashDays>@AvailableDays)
						SET @RETURNVALUE=-1
				
				IF (@TotalEncashDays>@MaxEncashDays)
						SET @RETURNVALUE=-2
		END
		
		SELECT @RETURNVALUE AS	IsValidDays
SET NOCOUNT OFF;
END
GO
