USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_GetVacationAmount]
	@FromDate [datetime],
	@ToDate [datetime],
	@EmpNode [int],
	@DocID [int] = 0,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	Declare @Grade Int,@GradewiseVacationPref Varchar(5)
	Declare @TabVacationMgmet Table (ID Int IDENTITY(1,1),SNO Int,SNAME Varchar(20),EMPNODE Int,TYPEID Int,TYPENAME Varchar(100),COMPONENTID Int,COMPONENTNAME Varchar(200),PERCENTAGE Float,AMOUNT Float,ENCASH Float,EXCESSDAYSSALARY Float,FORMULA Varchar(100),ACTUALAMOUNT Float,PERCACTUALAMOUNT Float)

	--START:LOADING PREFERENCES BASED ON GRADE
	SELECT @GradewiseVacationPref=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='GradeWiseVacation'
	IF (@GradewiseVacationPref='False')
	BEGIN
			SELECT @Grade=ISNULL(CCNID53,0) FROM COM_CCCCDATA WITH(NOLOCK) WHERE COSTCENTERID=50051 AND NODEID=@EmpNode
	END
	ELSE
	BEGIN
			SELECT @Grade=1--ISNULL(NODEID,0) FROM COM_CC50053 WITH(NOLOCK) WHERE CODE LIKE '%ALL%'
	END
	--END:LOADING PREFERENCES BASED ON GRADE
	
	--START: LOADING VACATION MANAGEMENT EARNING COMPONENTS AND DEDUCTION & LOAN COMPONENTS FROM CUSTOMIZE PAYROLL
		--LOADING EARNING COMPONENTS FROM VACATION MANAGEMENT JOIN WITH CUSTOMIZE PAYROLL
		INSERT INTO @TabVacationMgmet 
				SELECT	 C54.SNO,'',@EmpNode,C52.PARENTID,'',TD.dcAlpha17,C52.NAME,DN.dcNum1,0,0,0,TD.dcAlpha16,0,0
				FROM     INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK),COM_CC50052 C52 WITH(NOLOCK),COM_CC50054 C54 WITH(NOLOCK)
				WHERE    ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND DN.INVDOCDETAILSID=CC.INVDOCDETAILSID  AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
					     AND C52.NODEID=TD.dcAlpha17 AND C54.GRADEID=CC.DCCCNID53 AND TD.dcAlpha17=C54.COMPONENTID  AND C54.FIELDTYPE<>'OverTime'
					     AND CC.DCCCNID53=@Grade AND ID.COSTCENTERID=40061  and PayrollDate=(Select Max(PayrollDate) From COM_CC50054  WITH(NOLOCK))
		
		--LOADING DEDUCTION COMPONENTS FROM PAYROLL COMPONENTS JOIN WITH CUSTOMIZE PAYROLL		    
		INSERT INTO @TabVacationMgmet 
				SELECT   A.SNO,'',@EMPNODE,B.PARENTID,'',A.COMPONENTID,B.NAME,0,0,0,0,0,0,0
				FROM     COM_CC50054 A WITH(NOLOCK) LEFT JOIN COM_CC50052 B WITH(NOLOCK) ON B.NODEID=A.COMPONENTID
				WHERE    A.GRADEID=@Grade AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK)) AND A.TYPE<>4 AND B.PARENTID IN (3,4)
				ORDER BY A.TYPE,A.SNO 
		
		--INSERTING NEW COMPONENT
		INSERT INTO @TabVacationMgmet 
				SELECT   0,'',@EmpNode,2 ,'' ,0,'EMPLOYEE_BASIC',100,0,0,0,0,0,0 
	
	UPDATE T SET T.SNAME='Earning'+CONVERT(Varchar,T.SNO) FROM @TabVacationMgmet T,COM_CC50054 C54  WHERE  T.SNO=C54.SNO AND T.COMPONENTNAME <>'EMPLOYEE_BASIC' AND TYPEID=2
	UPDATE T SET T.TYPENAME=C52.NAME FROM @TabVacationMgmet T,COM_CC50052 C52 WHERE  T.TYPEID=C52.NODEID
	UPDATE T SET T.ACTUALAMOUNT=EP.BASICMONTHLY FROM @TabVacationMgmet T,PAY_EMPPAY EP WHERE  T.EMPNODE=EP.EMPLOYEEID AND T.COMPONENTNAME ='EMPLOYEE_BASIC'
	UPDATE @TabVacationMgmet SET FORMULA=(SELECT TOP 1 FORMULA FROM @TabVacationMgmet) WHERE COMPONENTNAME ='EMPLOYEE_BASIC'
	UPDATE @TabVacationMgmet SET formula=replace(formula,'Field',COMPONENTNAME)
	--END: LOADING VACATION MANAGEMENT EARNING COMPONENTS AND DEDUCTION & LOAN COMPONENTS FROM CUSTOMIZE PAYROLL		
	
	--START: LOADING EARNING COMPONENTS AND AMOUNT FROM EMPPAY Table AND UPDATE THE AMOUNT IN @TabVacationMgmet
	Declare @TRC Int,@STRQRY Varchar(MAX),@FIELDTYPE Float,@NUMFILEDNAME Varchar(200),@NUMFILEDNAME2 Varchar(200)
	Create Table #CalcAmountTab (FIELDTYPE Float,CALCNUMAMOUNT Float)
	Create Table #EmpPay(EMPNODE Int,SNO Int,AMOUNT Float,CALCFILEDNAME Varchar(30),CALCNUMAMOUNT Float)
	Declare @EmpPayAllow Table(ID Int IDENTITY(1,1),EMPNODE Int,SNO Int,AMOUNT Float,CALCFILEDNAME Varchar(30),CALCNUMAMOUNT Float)
		--START:LOADING EMPPAY Table DETAILS
			Declare @I Int,@STR Varchar(MAX)
			SET @I=1
			WHILE(@I<=20)
			BEGIN
				SET @NUMFILEDNAME='Earning'+convert(Varchar,@i)
				SET @STR='INSERT INTO #EmpPay 
								SELECT '+ CONVERT(Varchar,@EMPNODE) +' ,'+ CONVERT(Varchar,@I) +' ,'+ @NUMFILEDNAME +','''',0 FROM PAY_EMPPAY WITH(NOLOCK) WHERE EMPLOYEEID='+CONVERT(Varchar,@EmpNode)
				EXEC sp_executesql @STR
			SET @I=@I+1
			END
		UPDATE EP SET EP.AMOUNT=T.PERCENTAGE FROM #EmpPay EP,@TabVacationMgmet T WHERE  EP.SNO=T.SNO  and T.TYPEID=2 AND T.COMPONENTNAME <>'EMPLOYEE_BASIC' AND T.PERCENTAGE<0
		UPDATE #EmpPay SET CALCFILEDNAME='DCCALCNUM'+CONVERT(Varchar,SNO)
		
		--END:LOADING EMPPAY Table DETAILS
		
		--START:LOADING CALCULATE FIELD NAME ROWS ONLY FROM #EmpPay Table DETAILS OF AMOUNT (-1,-2,-3)
			INSERT INTO @EmpPayAllow SELECT * FROM #EmpPay WHERE AMOUNT<0
			
			SELECT @TRC=COUNT(*) FROM @EmpPayAllow
			SET @I=1
			WHILE(@I<=@TRC)
			BEGIN
				SELECT @FIELDTYPE=AMOUNT,@NUMFILEDNAME2=CALCFILEDNAME FROM @EmpPayAllow WHERE ID=@I 
				SET @STRQRY='INSERT INTO #CalcAmountTab 
								SELECT  '+ CONVERT(Varchar,@FIELDTYPE) +',SUM('+ @NUMFILEDNAME2 +')  FROM INV_DOCDETAILS ID WITH(NOLOCK),PAY_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK)
								WHERE   ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND DN.INVDOCDETAILSID=CC.INVDOCDETAILSID AND CC.DCCCNID51='+ CONVERT(Varchar,@EmpNode) +'
							    		AND ID.COSTCENTERID=40054 AND ID.STATUSID=369'
			--PRINT (@STRQRY)
			EXEC sp_executesql @STRQRY
			SET @I=@I+1
			END
		--UPDATINGD CALCNUMAMOUNT TO #EmpPay CACLNUMAMOUNT FIELD FOR -1,-2,-3 FIELD TYPES	
		UPDATE EP SET EP.CALCNUMAMOUNT= CA.CALCNUMAMOUNT FROM #EmpPay EP,  #CalcAmountTab CA WHERE EP.AMOUNT=CA.FIELDTYPE
		--END:LOADING CALCULATE FIELD NAME ROWS ONLY FROM #EmpPay Table DETAILS	
		
	UPDATE T SET T.ACTUALAMOUNT=ep.amount  FROM @TabVacationMgmet T,#EmpPay EP WHERE  T.SNO=EP.SNO  AND T.TYPEID=2 AND T.COMPONENTNAME <>'EMPLOYEE_BASIC'
	UPDATE @TabVacationMgmet SET PERCACTUALAMOUNT=(ACTUALAMOUNT*PERCENTAGE)/100 WHERE ACTUALAMOUNT>0 AND PERCENTAGE>0	
	--END: LOADING EARNING COMPONENTS AND AMOUNT FROM EMPPAY Table AND UPDATE THE AMOUNT IN @TabVacationMgmet
	
	--START: LOADING ALLOWANCES1 '-1' DETAILS FROM APPLY VACATION
	Declare @ALLOWANCES1 Float
		SELECT @ALLOWANCES1=ISNULL(SUM(DN.DCNUM1),0) FROM INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK)
		WHERE  ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND CC.INVDOCDETAILSID=DN.INVDOCDETAILSID AND TD.INVDOCDETAILSID=DN.INVDOCDETAILSID AND TD.INVDOCDETAILSID=CC.INVDOCDETAILSID 	AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
			   AND TD.DCALPHA23=-1 AND ID.COSTCENTERID=40072 AND CC.DCCCNID51=@EmpNode

		--UPDATING ALLOWANCES -1 
		UPDATE T SET T.ACTUALAMOUNT=ISNULL(EP.CALCNUMAMOUNT,0)-ISNULL(@ALLOWANCES1,0) FROM @TabVacationMgmet T,#EmpPay EP WHERE  T.SNO=EP.SNO AND T.TYPEID=2 AND T.COMPONENTNAME <>'EMPLOYEE_BASIC' AND T.PERCENTAGE=-1
		--UPDATING ALLOWANCES OTHER THAN -1 
		UPDATE T SET T.ACTUALAMOUNT=ISNULL(EP.CALCNUMAMOUNT,0) FROM @TabVacationMgmet T,#EmpPay EP WHERE  T.SNO=EP.SNO AND T.TYPEID=2 AND T.COMPONENTNAME <>'EMPLOYEE_BASIC' AND T.PERCENTAGE=-3
	--END: LOADING ALLOWANCES1 '-1' DETAILS FROM APPLY VACATION
	
	--START: LOADING LOAN DETAILS
	Declare @TabLoanDetails Table(SNO Int IDENTITY(1,1),LOANTYPEID Int,LOANAMOUNT Float)
	Declare @SDATE DateTime
	SET @SDATE=DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DateTime,@FromDate)),0)
		INSERT INTO @TabLoanDetails
				SELECT CC.dcCCNID52,CONVERT(DECIMAL,DN.dcNum2)
			    FROM   INV_DOCDETAILS ID WITH(NOLOCK),COM_DOCNUMDATA DN WITH(NOLOCK),COM_DOCTEXTDATA TD WITH(NOLOCK),COM_DOCCCDATA CC WITH(NOLOCK)
			    WHERE  ID.INVDOCDETAILSID=DN.INVDOCDETAILSID AND ID.INVDOCDETAILSID=CC.INVDOCDETAILSID AND DN.INVDOCDETAILSID=CC.INVDOCDETAILSID  AND ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
					   AND CC.DCCCNID51=@EmpNode AND ID.STATUSID=369 AND ID.COSTCENTERID=40056 AND ISDATE(TD.DCALPHA6)=1 AND CONVERT(DateTime,TD.DCALPHA6) BETWEEN CONVERT(DateTime,@SDATE) AND CONVERT(DateTime,@ToDate)
		
	           
		UPDATE CP SET CP.AMOUNT =TLD.LOANAMOUNT,CP.ACTUALAMOUNT=TLD.LOANAMOUNT FROM @TabVacationMgmet CP,@TabLoanDetails TLD WHERE CP.COMPONENTID=TLD.LOANTYPEID
	--END: LOADING LOAN DETAILS
	
	SELECT * FROM @TabVacationMgmet ORDER BY TYPEID,SNO 
	
	DROP Table #EmpPay
	DROP Table #CalcAmountTab
SET NOCOUNT OFF;
END
GO
