USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_RptVacationDays]
	@Date [datetime],
	@EmpWhere [nvarchar](max),
	@Flag [int] = 0,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
Begin
SET NOCOUNT ON;

--START-- Variable Declaration
DECLARE @I INT,@CNT INT,@EmpNode INT,@Grade Int,@AssingedDimVacDays Int,@AssingedLeaveType INT,@COMPONENTIDSNO Int,@TMONTHS Int,@CreditDaysCalculation Int,@TMP INT,@RC1 Int
Declare @DimVacDays float,@BelowSixMonthsDays float,@BelowOneYearDays float,@TotalDays float,@OPVACATIONDAYS FLOAT,@OPVACATIONSALARY FLOAT,@VacationMonthsDiff float,@VACDAYSPERMONTH float,@MonthlyNoofDays float,@LEAVESTAKEN FLOAT,@LeavesTakenEncash FLOAT,@LeavesTakenEncashSUM FLOAT,@LOPDAYS FLOAT

DECLARE @sQ NVARCHAR(MAX),@CalculateVacDayforVacationPeriod Varchar(3),@ConsiderLOPwhilecalculatingCreditdays Varchar(3),@ConsiderExcessdaysasLOP Varchar(3),@Perdaysalarycalculations Varchar(50),@GradewiseVacationPref Varchar(5),@CalcVacdaysuptoLastMonth Varchar(5),@DCNUMFILED Varchar(10),@SYCOLNAME Varchar(15),@STRQRY Varchar(MAX),@AccrueVacationDaysPref nvarchar(5),@VACDAYSPERIOD Varchar(20)

DECLARE @OPLeavesAsOn DateTime,@PayrollDate DATETIME,@ActDOJ DateTime ,@DocMonth DateTime,@DOJ DateTime,@VACATIONSTARTMONTH DateTime,@MONT1 DateTime,@MONT2 DateTime,@ActualVacDate DateTime
--END-- Variable Declaration

--START-- TEMP TABLES
DECLARE @EMPDETAILS TABLE(ID INT IDENTITY,NodeID INT,Code NVARCHAR(MAX),Name NVARCHAR(MAX),OPLeavesAsOn DATETIME,OPVacationDays FLOAT,DOJ DATETIME,VacationPeriod VARCHAR(20),VacDaysPerMonth FLOAT,VacDaysPeriod VARCHAR(20),Grade INT)
Declare @GetAvlblLeaves TABLE(Id Int Identity(1,1),AssignedLeaves INT,AvailableLeaves DECIMAL(9,2),FDate DateTime,TDate DateTime,MaxEncashLeaves Float,MaxLeaves Float,ActualAvailableLeaves float)
Declare @MonthDays TABLE(ID INT Identity(1,1),EMPNODE INT,FDATE DateTime,TDATE DateTime,TOTALDAYS FLOAT,ACTUALDAYS FLOAT,DAYS float,LEAVESTAKEN FLOAT,LOPDAYS FLOAT,EncashDays FLOAT)
DECLARE @VACTABLE TABLE(ID INT IDENTITY,EmployeeID INT,OpeningDays FLOAT,CreditedDays FLOAT,LeavesTaken FLOAT,EncashDays FLOAT,Balance Float)
--END-- TEMP TABLES
--VMDD
DECLARE @VacMgmtDocID INT, @IsDefineDaysExists BIT
CREATE TABLE #VMDD(FromMonth INT,ToMonth INT,DaysPerMonth FLOAT,ApplyToPrevMonths NVARCHAR(50))
CREATE TABLE #VacMonthWiseAllotedDays(ID INT Identity(1,1),VacMonth DateTime,AllotedDays FLOAT,Yearly FLOAT)
--VMDD

--SET TO FIRST DAY FOR THE GIVEN DATE
SET @PayrollDate=DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DATETIME,@Date)),0)

--START:LOADING PREFERENCES
SELECT @GradewiseVacationPref=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE NAME='GradeWiseVacation'
SELECT @CalcVacDaysuptoLastMonth=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='CalcVacDaysuptolastmonth'
SELECT @AccrueVacationDaysPref=ISNULL(VALUE,'False') FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='AccrueVacationDays'

IF(@Flag=1 OR @Flag=2)
	SET @CalcVacDaysuptoLastMonth='False'
-- END:LOADING PREFERENCES

--START-- DOCUMENTS DATA
SELECT a.InvDocDetailsID,d.dcAlpha1,d.dcAlpha2,d.dcAlpha3,b.dcCCNID51 INTO #TBL3
FROM INV_DocDetails a WITH(NOLOCK) 
JOIN COM_DocCCData b WITH(NOLOCK) ON b.InvDocDetailsID=a.InvDocDetailsID
JOIN COM_DocTextData d WITH(NOLOCK) ON d.InvDocDetailsID=a.InvDocDetailsID
WHERE  d.tCostCenterID=40072 and a.StatusID=369

SELECT CC.DCCCNID53,ISNULL(TD.DCALPHA3,'0') DCALPHA3, ISNULL(TD.DCALPHA4,'0') DCALPHA4,ISNULL(TD.DCALPHA9,'NO') DCALPHA9, ISNULL(TD.DCALPHA8,'NO') DCALPHA8,ISNULL(TD.DCALPHA15,'NO') DCALPHA15,ISNULL(TD.DCALPHA16,'(FIELD/30)') DCALPHA16,ISNULL(dcAlpha5,0) dcAlpha5,ISNULL(dcAlpha1,0) dcAlpha1,ISNULL(TD.DCALPHA18,'1') DCALPHA18,ID.DocID INTO #TVM
FROM INV_DOCDETAILS ID WITH(NOLOCK) 
JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
WHERE TD.tCOSTCENTERID=40061

--END-- DOCUMENTS DATA

IF((SELECT COUNT(*) FROM ADM_CostCenterDef WITH(NOLOCK) WHERE CostCenterID=50051 and SysColumnName ='CCNID53' and IsColumnInUse=1 and UserProbableValues='H')>0)
BEGIN
	SET @sQ='SELECT C51.NodeID,C51.Code,C51.Name,CONVERT(DateTime,OPLeavesAsOn) OPLeavesAsOn,isnull(OpVacationDays,0) OpVacationDays,CONVERT(DateTime,DOJ) DOJ,VACATIONPERIOD,ISNULL(VACDAYSPERMONTH,0) VACDAYSPERMONTH,VACDAYSPERIOD,ISNULL(H.HistoryNodeID,0)  FROM COM_CC50051 C51 WITH(NOLOCK)
	LEFT JOIN COM_HistoryDetails H WITH(NOLOCK) ON H.NodeID=C51.NodeID AND CostCenterID=50051 AND HistoryCCID=50053 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,'''+ CONVERT(VARCHAR,@PayrollDate) +''')) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,'''+ CONVERT(VARCHAR,@PayrollDate) +''') OR ToDate IS NULL)
	WHERE C51.IsGroup=0 AND C51.NODEID>1 AND C51.NODEID IN ('+@EmpWhere+')'
END
ELSE
BEGIN
	SET @sQ='SELECT NodeID,Code,Name,CONVERT(DateTime,OPLeavesAsOn) OPLeavesAsOn,isnull(OpVacationDays,0) OpVacationDays,CONVERT(DateTime,DOJ) DOJ,VACATIONPERIOD,ISNULL			(VACDAYSPERMONTH,0) VACDAYSPERMONTH,VACDAYSPERIOD,ISNULL(CC.CCNID53,0)  FROM COM_CC50051 C51 WITH(NOLOCK)
	JOIN COM_CCCCDATA CC WITH(NOLOCK) ON CC.NodeID=C51.NodeID AND CostCenterID=50051
	WHERE C51.IsGroup=0 AND C51.NODEID>1 AND C51.NODEID IN ('+@EmpWhere+')'
END
print @sQ
INSERT INTO @EMPDETAILS
EXEC sp_executesql @sQ

SELECT @CNT=COUNT(*) FROM @EMPDETAILS
SET @I=1
WHILE(@I<=@CNT)--START--EMPLOYEE LOOP
BEGIN

BEGIN
SET @GRADE=0 SET @DimVacDays=0 SET @LeavesTakenEncashSUM=0.0 SET @LEAVESTAKEN=0 SET @LeavesTakenEncash=0
Create Table #VACDAYTAB (VACDAYS float)

TRUNCATE TABLE #VMDD
TRUNCATE TABLE #VacMonthWiseAllotedDays
END  

SELECT @EmpNode=NODEID FROM @EMPDETAILS WHERE ID=@I

IF (@GRADEWISEVACATIONPREF='True')
BEGIN
SELECT @Grade=GRADE FROM @EMPDETAILS WHERE ID=@I
END

IF ISNULL(@GRADE,0)=0
	SET @GRADE=1
	
SELECT @BelowSixMonthsDays=ISNULL(DCALPHA3,'0'), @BelowOneYearDays=ISNULL(DCALPHA4,'0'), @CalculateVacDayforVacationPeriod=ISNULL(DCALPHA9,'NO'), 
	   @ConsiderLOPwhilecalculatingCreditdays=ISNULL(DCALPHA8,'NO'),@ConsiderExcessdaysasLOP=ISNULL(DCALPHA15,'NO'),@PERDAYSALARYCALCULATIONS=ISNULL(DCALPHA16,'(FIELD/30)') ,@AssingedDimVacDays=ISNULL(dcAlpha5,0),@AssingedLeaveType=ISNULL(dcAlpha1,0),
	   @CreditDaysCalculation=ISNULL(DCALPHA18,'1'),
	   @VacMgmtDocID=DocID
FROM   #TVM WHERE  DCCCNID53=@Grade	

--START :GET DOJ,VACATIONPERIOD AND VACATION DAYS,OPLeavesAsOn,OpVacationDays FROM EMPLOYEE
SELECT @OPLeavesAsOn=CONVERT(DateTime,OPLeavesAsOn),@OPVACATIONDAYS=isnull(OpVacationDays,0),@DOJ=CONVERT(DateTime,DOJ),@VACDAYSPERMONTH=ISNULL(VACDAYSPERMONTH,0),@VACDAYSPERIOD=VACDAYSPERIOD FROM @EMPDETAILS WHERE NODEID=@EmpNode
SET @ActDOJ=@Doj
IF(CONVERT(DateTime,@OPLeavesAsOn)<>'Jan  1 1900 12:00AM')
	SET @DOJ=@OPLeavesAsOn
--END :GET DOJ,VACATIONPERIOD AND VACATION DAYS,OPLeavesAsOn,OpVacationDays FROM EMPLOYEE

--VMDD
SET @IsDefineDaysExists=0
IF EXISTS (SELECT SeqNo FROM PAY_VacManageDefineDays WITH(NOLOCK) WHERE VMDocID=@VacMgmtDocID)
BEGIN
	SET @IsDefineDaysExists=1
	INSERT INTO #VMDD
	SELECT FromMonth,ToMonth,DaysPerMonth,ApplyToPrevMonths 
	FROM PAY_VacManageDefineDays WITH(NOLOCK) WHERE VMDocID=@VacMgmtDocID

	declare @dtt1 datetime,@dtt2 datetime,@TotMon INT,@AllotedDays FLOAT,@MNo INT,@APM NVARCHAR(50),@YearlyVD FLOAT
	set @dtt1=dateadd(day,-datepart(day,@ActDOJ)+1,@ActDOJ)
	set @dtt2=dateadd(day,-datepart(day,@Date)+1,@Date)
	set @dtt2=DATEADD(year,1,@dtt2) -- adding extra 1 year to know the yearly vacation days
	SET @MNo=0
	WHILE(@dtt1<=@dtt2)
	BEGIN
		SET @MNo=@MNo+1
			
		SELECT @AllotedDays=DaysPerMonth,@APM=ApplyToPrevMonths FROM #VMDD WHERE @MNo BETWEEN FromMonth AND ToMonth
		INSERT INTO #VacMonthWiseAllotedDays
		SELECT @dtt1,@AllotedDays,-1

		IF(@APM='Yes')
			UPDATE #VacMonthWiseAllotedDays SET AllotedDays=@AllotedDays

		IF(@MNo%12)=0
		BEGIN
			SELECT @YearlyVD=SUM(AllotedDays) FROM #VacMonthWiseAllotedDays WHERE Yearly=-1
				
			IF(@APM='Yes')
				UPDATE #VacMonthWiseAllotedDays SET Yearly=@YearlyVD
			ELSE
				UPDATE #VacMonthWiseAllotedDays SET Yearly=@YearlyVD WHERE Yearly=-1

		END

		SET @dtt1=DATEADD(month,1,@dtt1)
	END

END
--SELECT * FROM #VacMonthWiseAllotedDays
--VMDD

SET @TMP=0
--START : CHECKING THE PREVIOUS VACATION DETAILS OF EMPLOYEE IF NO RECORD FOUND THEN SELECT DOJ
IF ((SELECT count(*)  FROM #TBL3
	 WHERE  DCCCNID51=@EmpNode AND ISNULL(DCALPHA2,'')<>'' AND ISNULL(DCALPHA3,'')<>'' AND ISNULL(DCALPHA1,'')<>'')>0)
BEGIN
	--DATE OF REJOING
	
	SET   @VACATIONSTARTMONTH=@DOJ
	SET @TMP=1
	
	IF (@CalcVacDaysuptoLastMonth='False')
		SET @VacationStartMonth=CONVERT(DATETIME,@VacationStartMonth)
	ELSE
		SET @VacationStartMonth=CONVERT(DATETIME,DATEADD(MONTH,DATEDIFF(MONTH,-1,CONVERT(DATETIME,@VacationStartMonth))-2,0))	
	
	--VACATION MONTHS DIFFERENCE
	SET @VacationMonthsDiff=DATEDIFF(MONTH,@VACATIONSTARTMONTH,DATEADD(DAY,0,@DATE))		
	--select @VacationMonthsDiff
	--GET VACDAYS COMPONENT FROM MONTHLY PAYROLL
	select @COMPONENTIDSNO=SNO from COM_CC50054 WITH(NOLOCK) WHERE COMPONENTID=@AssingedDimVacDays AND GRADEID=@Grade 
	SET @DCNUMFILED='dcNum'+convert(Varchar,@COMPONENTIDSNO)
	
	SELECT @SYCOLNAME=SYSCOLUMNNAME FROM  adm_costcenterdef where costcenterid=40054 AND USERCOLUMNNAME =@DCNUMFILED
	SET @SYCOLNAME=REPLACE(@SYCOLNAME,'dcNum','dcCalcNum')
	
	IF(ISNULL(@SYCOLNAME,'')<>'' AND ISNULL(@VACATIONSTARTMONTH,'')<>'' AND ISNULL(@DATE,'')<>'')
	BEGIN
		SET @STRQRY='INSERT INTO #VACDAYTAB 
		SELECT  SUM('+ @SYCOLNAME +')  FROM INV_DOCDETAILS ID WITH(NOLOCK) JOIN PAY_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID JOIN							COM_DOCCCDATA CC  WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
		WHERE   CC.DCCCNID51='+ CONVERT(Varchar,@EmpNode) +' AND ID.COSTCENTERID=40054 AND CONVERT(DateTime,ID.DOCDATE) BETWEEN '''+ convert											(Varchar,@VACATIONSTARTMONTH) +''' and '''+ convert(Varchar,@DATE)+''''
		--	PRINT (@STRQRY)
		EXEC (@STRQRY)
	END
	
	SELECT @DimVacDays=ISNULL(VACDAYS,0) FROM #VACDAYTAB
	DROP TABLE #VACDAYTAB

	declare @VMD FLOAT,@VSM DATETIME
	SET @VSM=@ActDOJ
	--VACATION MONTHS DIFFERENCE
	SET @VMD=DATEDIFF(MONTH,@VSM,DATEADD(DAY,0,@DATE))

	IF ISNULL(@DimVacDays,0)>0
	BEGIN
		SET @MonthlyNoofDays= ROUND((CAST(@DimVacDays AS FLOAT)/ CAST(12 AS FLOAT)),2,1)
	END
	ELSE IF ISNULL(@DimVacDays,0)=0 AND @VMD<=6
	BEGIN
		SET @MonthlyNoofDays=@BelowSixmonthsDays
	END
	ELSE IF ISNULL(@DimVacDays,0)=0 AND @VMD>6 And @VMD<=12 
	BEGIN
		SET @MonthlyNoofDays=@BelowOneyearDays
	END
	ELSE
	BEGIN
		IF @VACDAYSPERIOD='Yearly'
		BEGIN
			SET @TMONTHS=12
		END
		ELSE
		BEGIN
			SET @TMONTHS=1
		END
		SET @MonthlyNoofDays= ROUND((CAST(@VACDAYSPERMONTH AS FLOAT)/CAST(@TMONTHS AS FLOAT)),2,1)
	END							
END
ELSE
BEGIN
	--DATE OF JOINING
	
	print 'DOJ'
	SET   @VACATIONSTARTMONTH=@ActDOJ
	SET @TMP=0
	--VACATION MONTHS DIFFERENCE
	SET @VacationMonthsDiff=DATEDIFF(MONTH,@VACATIONSTARTMONTH,DATEADD(DAY,0,@DATE))
	
	--GET VACDAYS FROM MONTHLY PAYROLL
	select @COMPONENTIDSNO=SNO from COM_CC50054 WHERE COMPONENTID=@AssingedDimVacDays AND GRADEID=@Grade 
	SET @DCNUMFILED='dcNum'+convert(Varchar,@COMPONENTIDSNO)

	SELECT @SYCOLNAME=SYSCOLUMNNAME FROM  adm_costcenterdef where costcenterid=40054 AND USERCOLUMNNAME =@DCNUMFILED
	SET @SYCOLNAME=REPLACE(@SYCOLNAME,'dcNum','dcCalcNum')

	IF(ISNULL(@SYCOLNAME,'')<>'' AND ISNULL(@VACATIONSTARTMONTH,'')<>'' AND ISNULL(@DATE,'')<>'')
	BEGIN
		SET @STRQRY='INSERT INTO #VACDAYTAB 
		SELECT  SUM('+ @SYCOLNAME +')  FROM INV_DOCDETAILS ID WITH(NOLOCK) JOIN PAY_DOCNUMDATA DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID JOIN COM_DOCCCDATA CC  WITH		(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
		WHERE   CC.DCCCNID51='+ CONVERT(Varchar,@EmpNode) +' AND ID.COSTCENTERID=40054 AND CONVERT(DateTime,ID.DOCDATE) BETWEEN '''+ convert(Varchar,@VACATIONSTARTMONTH) +''' and		'''+ convert(Varchar,@DATE)+''''
		PRINT (@STRQRY)
		EXEC (@STRQRY)
	END
	SELECT @DimVacDays=ISNULL(VACDAYS,0) FROM #VACDAYTAB
	DROP TABLE #VACDAYTAB

	--PICKING THE PERMONTH VACDAYS FROM PREFERENCES
	IF @DimVacDays>0
	BEGIN
		SET @MonthlyNoofDays= ROUND((CAST(@DimVacDays AS FLOAT)/CAST(12 AS FLOAT)),2,1)
	END
	ELSE IF @VacationMonthsDiff<=6
	BEGIN
		SET @MonthlyNoofDays=@BelowSixMonthsDays
	END
	ELSE IF @VacationMonthsDiff>6 And @VacationMonthsDiff<=12 
	BEGIN
		SET @MonthlyNoofDays=@BelowOneYearDays
	END
	ELSE
	BEGIN
		IF @VACDAYSPERIOD='Yearly'
		BEGIN
			SET @TMONTHS=12
		END
		ELSE
		BEGIN
			SET @TMONTHS=1
		END
		SET @MonthlyNoofDays=@VACDAYSPERMONTH/@TMONTHS
	END
END							
--END : CHECKING THE PREVIOUS VACATION DETAILS OF EMPLOYEE IF NO RECORD FOUND THEN SELECT DOJ

	IF(CONVERT(DateTime,@OPLeavesAsOn)<>'Jan  1 1900 12:00AM' AND @TMP=0 )
		SET @VacationStartMonth=@DOJ

	SET @VacationMonthsDiff=DATEDIFF(MONTH,@VACATIONSTARTMONTH,DATEADD(DAY,0,@DATE))

IF (ISNULL(@ActualVacDate,'')='')
	SET @ActualVacDate=DATEADD(D,-1,@DATE)--CONVERT(DATETIME,@DATE)


PRINT 'AD'
PRINT @ActualVacDate
PRINT @VACATIONSTARTMONTH
PRINT @VacationMonthsDiff
SET @LOPDAYS =0
SET @RC1=0
WHILE(@RC1<=@VacationMonthsDiff)
BEGIN
	IF (@RC1=0)
	BEGIN
		SET @MONT1=DATEADD(MONTH,@RC1,@VACATIONSTARTMONTH)
		IF (@AccrueVacationDaysPref='False')
		BEGIN
			IF (@VacationMonthsDiff=0)
			BEGIN
				SET @MONT2=DATEADD(D,-1,@VACATIONSTARTMONTH)
				IF(@MONT2<@MONT1)
					SET @MONT2=DATEADD(D,0,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@VacationStartMonth)+1,0)))
			END
			ELSE
				SET @MONT2=DATEADD(D,0,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@VacationStartMonth)+1,0)))
		END					
		ELSE
		BEGIN
			SET @MONT2=DATEADD(D,0,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@MONT1)+1,0)))
		END

		--select @VACATIONSTARTMONTH,@MONT1,@MONT2

	END
	ELSE IF (@RC1=@VacationMonthsDiff)
	BEGIN
		SET @MONT1=DATEADD(MONTH,@RC1,DATEADD(M,DATEDIFF(M,0,@VACATIONSTARTMONTH),0))
		IF (@AccrueVacationDaysPref='False')
		BEGIN
			IF(CONVERT(DATETIME,@ActualVacDate)<CONVERT(DATETIME,@DATE))
			BEGIN
				IF(@Flag=1 OR @Flag=2)
				SET @MONT2=@DATE
				ELSE
				SET @MONT2=DATEADD(D,-1,@DATE)
			END
			ELSE
			BEGIN
			SET @MONT2=DATEADD(D,-1,@ActualVacDate)
			END
		END
		ELSE
		BEGIN
			SET @MONT2=DATEADD(D,0,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ActualVacDate)+1,0)))

		END
	END
	ELSE
	BEGIN

		SET @MONT1=DATEADD(MONTH,@RC1,DATEADD(M,DATEDIFF(M,0,@VACATIONSTARTMONTH),0))
		IF (@AccrueVacationDaysPref='False')
			SET @MONT2=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@MONT1)+1,0))
		ELSE
			SET @MONT2=DATEADD(D,0,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@MONT1)+1,0)))
			

	END

	
---------------------------------------------------

	IF EXISTS ( 
				SELECT InvDocDetailsID
				FROM #TBL3
				WHERE  dcCCNID51=@Empnode 
				AND ( @MONT1 BETWEEN CONVERT(DATETIME,dcAlpha2) AND CONVERT(DATETIME,dcAlpha3) OR 
						@MONT2 BETWEEN CONVERT(DATETIME,dcAlpha2) AND CONVERT(DATETIME,dcAlpha3) OR 
						CONVERT(DATETIME,dcAlpha2) BETWEEN  @MONT1 AND  @MONT2 OR 
						CONVERT(DATETIME,dcAlpha3) BETWEEN  @MONT1 AND  @MONT2 
					)
				)
				BEGIN
					EXEC spPAY_GetVacationLeavesInfoNew @MONT1,@MONT2,@Empnode,1,1,0,@LEAVESTAKEN OUTPUT,@LeavesTakenEncash OUTPUT
				END
				ELSE
				BEGIN
					SET @LEAVESTAKEN=0 SET @LeavesTakenEncash=0
				END
				
				SET @LeavesTakenEncashSUM=@LeavesTakenEncashSUM+@LeavesTakenEncash
				
---------------------------------------------------
	SET @LOPDAYS=0
	IF(@ConsiderLOPwhilecalculatingCreditdays='Yes')
	BEGIN
		SELECT @LOPDAYS=ISNULL(TD.DCALPHA9,'0')  FROM INV_DOCDETAILS ID WITH(NOLOCK) 
		JOIN COM_DOCTEXTDATA TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
			JOIN COM_DOCCCDATA CC ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
			WHERE TD.tCOSTCENTERID=40054 AND ID.VOUCHERTYPE=11 AND CC.DCCCNID51=@Empnode AND ISDATE(DCALPHA17)=1 AND CONVERT(DATETIME,DCALPHA17)=CONVERT(DATETIME,@MONT1) AND ISDATE(DCALPHA18)=1 AND CONVERT(DATETIME,DCALPHA18)=CONVERT(DATETIME,@MONT2) 
	END
 
	IF(@CalculateVacDayforVacationPeriod='Yes')
		INSERT INTO @MonthDays VALUES(@Empnode,@MONT1,@MONT2,DATEDIFF(D,DATEADD(MONTH,0,DATEADD(M,DATEDIFF(M,0,@MONT1),0)),DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@MONT2)+1,0)))+1,((DATEDIFF(D,@MONT1,@MONT2)+1)-ISNULL(@LOPDAYS,0)),0,ISNULL(@LEAVESTAKEN,0),ISNULL(@LOPDAYS,0),isnull(@LeavesTakenEncash,0))
	ELSE
		INSERT INTO @MonthDays VALUES(@Empnode,@MONT1,@MONT2,DATEDIFF(D,DATEADD(MONTH,0,DATEADD(M,DATEDIFF(M,0,@MONT1),0)),DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@MONT2)+1,0)))+1,(((DATEDIFF(D,@MONT1,@MONT2)+1)-ISNULL(@LOPDAYS,0))-ISNULL(@LEAVESTAKEN,0)),0,ISNULL(@LEAVESTAKEN,0),ISNULL(@LOPDAYS,0),isnull(@LeavesTakenEncash,0))
		
SET @RC1=@RC1+1
END


IF(@CreditDaysCalculation=1)
BEGIN
	--((VacDaysPerMonth*MonthDaysToConsider)/TotalMonthDays)
	IF(@IsDefineDaysExists=1)
	BEGIN
		UPDATE @MonthDays 
		SET Days= ROUND((( CAST((Select ISNULL(AllotedDays,0) From #VacMonthWiseAllotedDays WHERE MONTH(VacMonth)=MONTH(FDATE) AND YEAR(VacMonth)=YEAR(FDATE)) AS FLOAT) * CAST(ACTUALDAYS AS FLOAT) )/ CAST(TOTALDAYS AS FLOAT) ),2,1)		
		WHERE EMPNODE=@Empnode AND TOTALDAYS>0 
	END
	ELSE
	BEGIN		
		UPDATE @MonthDays SET Days= (( CAST(ACTUALDAYS AS FLOAT) * CAST(@MonthlyNoofDays AS FLOAT) )/ CAST(TOTALDAYS AS FLOAT) ) where EMPNODE=@Empnode AND TOTALDAYS>0
	END
END
ELSE
BEGIN
	--((VacDaysPerYear/365)*MonthDaysToConsider)
	IF(@IsDefineDaysExists=1)
	BEGIN
		UPDATE @MonthDays SET Days=(( CAST((Select ISNULL(Yearly,0) From #VacMonthWiseAllotedDays WHERE MONTH(VacMonth)=MONTH(FDATE) AND YEAR(VacMonth)=YEAR(FDATE)) AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ) WHERE EMPNODE=@Empnode
	END
	ELSE
	BEGIN
		UPDATE @MonthDays SET Days=(( CAST(@VacDaysPerMonth AS FLOAT) / CAST(365 AS FLOAT) )* CAST(ACTUALDAYS AS FLOAT) ) WHERE EMPNODE=@Empnode
	END
END	

--CHECKING PREFERENCE VACATION DAYS UPTO LAST MONTH
IF (@CALCVACDAYSUPTOLASTMONTH='False')
	SELECT  @TotalDays=SUM(Days-LeavesTaken) FROM @MonthDays WHERE EMPNODE=@Empnode
ELSE
	SELECT  @TotalDays=SUM(Days-LeavesTaken) FROM @MonthDays WHERE EMPNODE=@Empnode AND CONVERT(DateTime,FDATE)<DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DateTime,@DATE)),0)
--END : CALCULATING PER MONTH DAYS

INSERT INTO @VACTABLE
SELECT @Empnode,@OPVACATIONDAYS,SUM(DAYS),sum(LEAVESTAKEN),@LeavesTakenEncashSUM,@OPVACATIONDAYS+SUM(DAYS)-sum(LEAVESTAKEN)-@LeavesTakenEncashSUM FROM @MonthDays WHERE EMPNODE=@EmpNode

SET @I=@I+1
END--END--EMPLOYEE LOOP

SELECT * FROM @VACTABLE

DROP TABLE #VMDD
DROP TABLE #VacMonthWiseAllotedDays
DROP TABLE #TBL3
DROP TABLE #TVM

SET NOCOUNT OFF;
END

GO
