USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spADM_DeleteUnUsedNodes]
	@CostCenterList [nvarchar](max),
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
	DECLARE @I INT, @RC INT,@NODEID INT,@J INT,@TRC INT ,@COSTCENTERID INT,@SQL NVARCHAR(MAX)=''

	DECLARE @Tbl TABLE(ID INT IDENTITY(1,1),FeatureID INT)  
	CREATE TABLE #TAB(ID INT IDENTITY(1,1),NODEID INT,CODE NVARCHAR(MAX),NAME NVARCHAR(MAX))
	CREATE TABLE #TABPRODUCTS (ID INT IDENTITY(1,1),NODEID INT,CODE NVARCHAR(MAX),NAME NVARCHAR(MAX))
				
	INSERT INTO @Tbl
	EXEC SPSplitString @CostCenterList,',' 
   
	SET @J=1  
	SELECT @TRC=COUNT(*) FROM @Tbl  
	WHILE(@J<=@TRC)  
	BEGIN  	  
		 SELECT @COSTCENTERID=FeatureID FROM @Tbl WHERE ID=@J  	
		 IF(@COSTCENTERID=3)--PRODUCTS
		 BEGIN  
			TRUNCATE TABLE #TAB
			INSERT INTO #TAB SELECT PRODUCTID,PRODUCTCODE,PRODUCTNAME FROM INV_PRODUCT WITH(NOLOCK) WHERE PRODUCTID>2 and isgroup=0
			DELETE FROM #TAB WHERE NODEID IN (SELECT PRODUCTID FROM INV_DOCDETAILS WITH(NOLOCK))
			DELETE FROM #TAB WHERE NODEID IN (SELECT PARENTID FROM INV_PRODUCT WITH(NOLOCK))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT I.PRODUCTID FROM  INV_DOCDETAILS I with(nolock), ACC_DocDetails A with(nolock) WHERE  A.refccid=300 and A.refnodeid=I.DocID)
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductID FROM  INV_ProductBundles with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ParentProductID FROM  INV_ProductBundles with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductID FROM  INV_ProductSubstitutes with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductSubstituteID FROM  INV_ProductSubstitutes with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductID FROM  INV_Batches with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductID FROM  INV_ProductTestcases with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductID FROM  COM_CCCCDATA with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  ADM_SchemeProducts with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  ADM_DimensionWiseLockData with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  ADM_SchemesDiscounts with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  COM_BudgetAlloc with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  COM_DimensionMappings with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  COM_CCPrices with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT NODEID FROM  COM_CCSchedules with(nolock) WHERE COSTCENTERID=3)
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  COM_CCTaxes with(nolock))
			
			if exists(select name from sys.tables with(nolock) where name='CRM_ProductMapping')
			begin
				SET @SQL=@SQL+'DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_CampaignDemoKit with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_CampaignResponse with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_ContractLines with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_CampaignProducts with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_Cases with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  CRM_ProductMapping with(nolock))'
			end
			
			if exists(select name from sys.tables with(nolock) where name='PRD_BillOfMaterial')
			begin
				SET @SQL=@SQL+' DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  PRD_BillOfMaterial with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  PRD_BOMProducts with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PRODUCTID FROM  PRD_JobOuputProducts with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductName FROM  PRD_SFReportProducts with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProductName FROM  PRD_SFReportRMs with(nolock))'
			end
			
			EXEC (@SQL)
			
			TRUNCATE TABLE #TABPRODUCTS
			INSERT INTO #TABPRODUCTS SELECT NODEID,CODE,NAME FROM #TAB WITH(NOLOCK)
			
			SELECT @I=1,@RC=COUNT(*) FROM #TABPRODUCTS WITH(NOLOCK)
			WHILE(@I<=@RC)
			BEGIN 
				SELECT @NODEID=NODEID FROM #TABPRODUCTS WITH(NOLOCK) WHERE ID=@I
				EXEC spINV_DeleteProduct @NODEID,@UserID,1,@LangID
			SET @I=@I+1	
			END
		END
		IF(@COSTCENTERID=2)--ACCOUNTS
		BEGIN  
			TRUNCATE TABLE #TAB
			INSERT INTO #TAB 
			SELECT AccountID,AccountCODE,AccountNAME
			FROM ACC_ACCOUNTS A WITH(NOLOCK)
			left join (select DebitAccount AccID from ACC_DOCDETAILS with(nolock) 
						union 
						select CREDITAccount from ACC_DOCDETAILS with(nolock)) AS T on T.AccID=A.AccountID
			WHERE AccountID>40 and isgroup=0 and T.AccID is null AND ISNULL(CCID,'0')='0'  

			DELETE FROM #TAB WHERE NODEID IN (SELECT BankAccountID FROM ACC_DOCDETAILS WITH(NOLOCK))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DebitAccount FROM  INV_DOCDETAILS with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CREDITACCOUNT FROM  INV_DOCDETAILS with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  ADM_DimensionWiseLockData with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  ADM_FinancialYears with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  ADM_SchemesDiscounts with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_Billwise with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DiscAccountID FROM  COM_Billwise with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_BRSTemplate with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_BudgetAlloc with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_CCPrices with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_CCTaxes with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_ChequeReturn with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_DimensionMappings with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_DocPayTerms with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_LCBills with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT VendorAccountID FROM  INV_Batches with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ClosingStockAccountID FROM  INV_Product with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT COGSAccountID FROM  INV_Product with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PurchaseAccountID FROM  INV_Product with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT SalesAccountID FROM  INV_Product with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  INV_ProductVendors with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AcqnCostACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccumDeprACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AcqnCostDispACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccumDeprDispACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT GainsDispACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT LossDispACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT MaintExpenseACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DeprExpenseACCID FROM  ACC_PostingGroup with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DebitAccount FROM  ADM_DocumentDef with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CREDITACCOUNT FROM  ADM_DocumentDef with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  COM_CCCCDATA with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PDCReceivableAccount FROM  ACC_Accounts with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PDCPayableAccount FROM  ACC_Accounts with(nolock))
			DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT UserDefaultValue from ADM_CostCenterDef with(nolock) where SysColumnName like '%Account%' and [CostCenterID]>2	and UserDefaultValue is not null and isnumeric(UserDefaultValue)=1 and convert(int,UserDefaultValue)>0)

			if exists(select name from sys.tables with(nolock) where name='CRM_Customer')
			begin
				SET @SQL=@SQL+'DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  CRM_Activities with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  CRM_CampaignProducts with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AccountID FROM  CRM_Customer with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CustomerID FROM  CRM_Customer with(nolock))'
			end
				
			if exists(select name from sys.tables with(nolock) where name='PAY_EmpAccountsLinking')
			begin
				SET @SQL=@SQL+' DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CreditAccountID FROM  PAY_EmpAccountsLinking with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DebitAccountID FROM  PAY_EmpAccountsLinking with(nolock))'
			end
				
			if exists(select name from sys.tables with(nolock) where name='PRD_Expenses')
			begin
				SET @SQL=@SQL+' DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CreditAccountID FROM  PRD_Expenses with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DebitAccountID FROM  PRD_Expenses with(nolock))'
			end
				
			if exists(select name from sys.tables with(nolock) where name='REN_ContractParticulars')
			begin
				SET @SQL=@SQL+' DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceAccountID FROM  REN_ContractParticulars with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceAccountID FROM  REN_Particulars with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT CreditAccountID FROM  REN_Particulars with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT DebitAccountID FROM  REN_Particulars with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceReceivableAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceRentAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PenaltyAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProvisionAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT RentalIncomeAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT RentalReceivableAccountID FROM  REN_Property with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceReceivableAccountID FROM  REN_Units with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT AdvanceRentAccountID FROM  REN_Units with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT PenaltyAccountID FROM  REN_Units with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT ProvisionAccountID FROM  REN_Units with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT RentalIncomeAccountID FROM  REN_Units with(nolock))
				DELETE FROM #TAB WHERE NODEID IN (SELECT DISTINCT RentalReceivableAccountID FROM  REN_Units with(nolock))'
			end
			
			EXEC(@SQL)

			TRUNCATE TABLE #TABPRODUCTS
			INSERT INTO #TABPRODUCTS SELECT NODEID,CODE,NAME FROM #TAB WITH(NOLOCK)
			SELECT @I=1,@RC=COUNT(*) FROM #TABPRODUCTS WITH(NOLOCK)
			WHILE(@I<=@RC)
			BEGIN 
				SELECT @NODEID=NODEID FROM #TABPRODUCTS WITH(NOLOCK) WHERE ID=@I
				EXEC spACC_DeleteAccount @NODEID,@UserID,1,@LangID
			SET @I=@I+1	
			END		
		END
	SET @J=@J+1   	
	END   
	DROP TABLE #TABPRODUCTS
	DROP TABLE #TAB
END
GO
