USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_SetEmployeeReleaseDate]
	@DOCID [int],
	@EMPNODE [int],
	@RESIGNDATE [datetime],
	@TENTATIVEDATE [datetime],
	@REDATE [datetime],
	@REASON [nvarchar](max)
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @COSTCENTERID INT,@INVDOCDETAILSID INT
	IF ISNULL(@DOCID,0)>0
	BEGIN
		
	SELECT @COSTCENTERID=COSTCENTERID,@INVDOCDETAILSID=INVDOCDETAILSID FROM INV_DOCDETAILS WHERE DOCID=@DOCID
		--APPLY RESIGNATION
		IF (@COSTCENTERID=40069)
		BEGIN
			IF((SELECT COUNT(*) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID AND STATUSID=369)>0)
			BEGIN
				UPDATE COM_CC50051 SET DORESIGN=CONVERT(FLOAT,@RESIGNDATE),DOTENTRELIEVE=CONVERT(FLOAT,@TENTATIVEDATE),
									   DORELIEVE=CONVERT(FLOAT,@REDATE),RESIGNREMARKS=ISNULL(@REASON,'') WHERE NODEID=@EMPNODE
			END
		END
		--REJOIN FROM VACATION
		ELSE IF (@COSTCENTERID=40065)
		BEGIN
			IF((SELECT COUNT(*) FROM INV_DOCDETAILS WITH(NOLOCK) WHERE DOCID=@DOCID AND STATUSID=369)>0)
			BEGIN
				UPDATE TD SET TD.dcAlpha1=CONVERT(DATETIME,@REDATE)  
						  FROM COM_DOCTEXTDATA TD INNER JOIN COM_DOCCCDATA CC ON TD.INVDOCDETAILSID=CC.INVDOCDETAILSID 
							   AND CC.dcCCNID51=@EMPNODE AND TD.INVDOCDETAILSID=@INVDOCDETAILSID
			END 
		END
	END
END
GO
