USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_PostApplyLeaves]
	@DOCID [int] = NULL,
	@UserID [int] = 1,
	@LangID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @FROMDATE DATETIME,@INVDOCID INT,@MODE INT,@EMPNODE INT,@LEAVETYPE INT,@LEAVESTAKEN FLOAT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME
DECLARE @ICOUNT INT,@RCOUNT INT,@ActualAvailableLeaves FLOAT,@DOCUMENTTYPE INT

DECLARE @TAB2 TABLE (ID INT IDENTITY(1,1),INVDOCDETAILSID INT,FROMDATE DATETIME,EMPNODE INT,LEAVETYPE INT,LEAVESTAKEN FLOAT)

SET @MODE=0
SET @ICOUNT=1
IF ISNULL(@DOCID,0)>0
BEGIN
		SELECT @DOCUMENTTYPE=I.DocumentType FROM INV_DOCDETAILS I WITH(NOLOCK) WHERE I.DOCID=@DOCID
		IF(@DOCUMENTTYPE=95)
		BEGIN
			INSERT INTO @TAB2
			SELECT ID.INVDOCDETAILSID,CONVERT(DATETIME,TD.dcAlpha3),CC.DCCCNID51,C52.NodeID,ISNULL(TD.dcAlpha15,0)
			FROM   INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID 
			INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
			JOIN COM_CC50052 C52 WITH(NOLOCK) ON C52.Name=TD.dcAlpha12
			WHERE  ID.DOCID=@DOCID AND TD.dcAlpha1=2
		END
		ELSE
		BEGIN
			INSERT INTO @TAB2
			SELECT ID.INVDOCDETAILSID,CASE ID.DocumentType WHEN 62 THEN CONVERT(DATETIME,TD.dcAlpha4) WHEN 58 THEN CONVERT(DATETIME,ID.DOCDATE) END,CC.DCCCNID51,CC.DCCCNID52,ISNULL(TD.dcAlpha7,0)
			FROM   INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DOCCCDATA CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
			WHERE  ID.DOCID=@DOCID
		END

		SELECT @RCOUNT =COUNT(*) FROM @TAB2
		WHILE(@ICOUNT<=@RCOUNT)
		BEGIN
			SELECT @INVDOCID=INVDOCDETAILSID,@FROMDATE=FROMDATE,@EMPNODE=EMPNODE,@LEAVETYPE=LEAVETYPE,@LEAVESTAKEN=LEAVESTAKEN FROM @TAB2 WHERE ID=@ICOUNT
			EXEC spPAY_UpdateAssignLeavesDatewise @FROMDATE,@INVDOCID,@MODE,@EMPNODE,@LEAVETYPE
		SET @ICOUNT=@ICOUNT+1	
		END
END
SET NOCOUNT OFF;
END
GO
