USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spCRM_GetCampaignProductDetails]
	@CampaignID [bigint] = 0,
	@UserId [int] = 0,
	@LangId [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS

BEGIN TRY	
SET NOCOUNT ON
 
 DECLARE @DATA NVARCHAR(300)
 DECLARE @TBL TABLE(ID INT IDENTITY(1,1),VALUE NVARCHAR(300),FEATURENAME NVARCHAR(300)) 
 
 SELECT @DATA=ISNULL(VALUE,0) FROM COM_COSTCENTERPREFERENCES WITH(NOLOCK)
 WHERE COSTCENTERID=88 AND NAME='CampaignDimensionsAtProduct'
 
 
 INSERT INTO @TBL(VALUE)
 EXEC SPSPLITSTRING @DATA,';'
 

 UPDATE T SET T.FEATURENAME=F.NAME
 FROM @TBL T 
 JOIN ADM_FEATURES F WITH(NOLOCK) ON F.FEATUREID=T.VALUE

 
 SELECT * FROM @TBL ORDER BY FEATURENAME

SET NOCOUNT OFF;
RETURN 1
END TRY
BEGIN CATCH  
	--Return exception info [Message,Number,ProcedureName,LineNumber]  
	IF ERROR_NUMBER()=50000
	BEGIN
		SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID
	END
	ELSE
	BEGIN
		SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine
		FROM COM_ErrorMessages WITH(nolock) WHERE ErrorNumber=-999 AND LanguageID=@LangID
	END

SET NOCOUNT OFF  
RETURN -999   
END CATCH
GO
