USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_FillIncomeTaxComponents]
	@FLAG [int] = 0,
	@YEAR [int] = 0,
	@EMPNODE [int] = 0,
	@Regime [nvarchar](20),
	@USERID [int] = 1,
	@LANGID [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN TRY   
	SET NOCOUNT ON;
	DECLARE @R INT,@TRC INT,@NODEID INT,@PARENTID int
	DECLARE @LFT INT,@RGT INT
	
	SELECT @LFT=LFT,@RGT=RGT FROM COM_CC50052 WITH(NOLOCK) WHERE (CODE='INCOME TAX' OR NAME='INCOME TAX')
	
	--For Incometax Declarations
	IF ISNULL(@FLAG,0)=0 
	BEGIN
		DECLARE @TAB TABLE(ID INT IDENTITY(1,1),LFT INT,	ORDERNO INT,			PARENTID INT,
					   NODEID INT,					NAME VARCHAR(200),		ISGROUP INT,
					   CONTROLTYPE VARCHAR(50),		FIELDTYPE VARCHAR(100), GROUPID INT,
					   AMOUNTLIMIT VARCHAR(100),	AMOUNT decimal(9,2),	SELECTEDNODE INT, SELECTEDAMTLIMIT VARCHAR(100),NewAmountLimit NVARCHAR(100),NewSELECTEDAMTLIMIT VARCHAR(100))
		DECLARE @TABGROUPS TABLE(ID INT IDENTITY(1,1),LFT INT,	ORDERNO INT,			PARENTID INT,
					   NODEID INT,					NAME VARCHAR(200),		ISGROUP INT,
					   CONTROLTYPE VARCHAR(50),		FIELDTYPE VARCHAR(100), GROUPID INT,
					   AMOUNTLIMIT VARCHAR(100),	AMOUNT decimal(9,2),	SELECTEDNODE INT, SELECTEDAMTLIMIT VARCHAR(100),NewAmountLimit NVARCHAR(100),NewSELECTEDAMTLIMIT VARCHAR(100))
		--LOADING GROUP COMPONENTS
		INSERT INTO @TABGROUPS
			SELECT LFT,CCALPHA3 ORDERNO,PARENTID,NODEID,CASE ISGROUP WHEN 0 THEN '      '+ NAME ELSE NAME END,ISGROUP,CASE ISNULL(CCALPHA1,'') WHEN '' THEN 'Label' WHEN 'None' THEN 'Label' WHEN 'ComboBox' THEN 'ComboTextValue' WHEN 'TextBox' THEN 'TextBox'  END,CCALPHA2 AS FILEDTYPE,'','',0,0,'','',''
			FROM   COM_CC50052 WITH(NOLOCK) WHERE LFT >=@LFT AND RGT<=@RGT AND isnull(CCALPHA3,0)>0 AND ISGROUP=1	ORDER BY NODEID,ORDERNO
		
		--LOADING GROUPS AND COMPONENTS BASED ON GROUP SELECTED
		SET @R=1
		SELECT @TRC=COUNT(*) FROM @TABGROUPS	
		WHILE(@R<=@TRC)
			BEGIN
				INSERT INTO @TAB SELECT  LFT, ORDERNO,PARENTID,NODEID,NAME,ISGROUP,CONTROLTYPE ,FIELDTYPE,GROUPID ,AMOUNTLIMIT,AMOUNT,SELECTEDNODE,SELECTEDAMTLIMIT,NewAmountLimit,NewSELECTEDAMTLIMIT FROM @TABGROUPS WHERE ID=@R
				SELECT @PARENTID=NODEID FROM @TABGROUPS WHERE ID=@R
			
				INSERT INTO @TAB 
				SELECT LFT,CCALPHA3 ORDERNO,PARENTID,NODEID,CASE ISGROUP WHEN 0 THEN '      '+ NAME ELSE NAME END,ISGROUP,CASE ISNULL(CCALPHA1,'') WHEN '' THEN 'Label' WHEN 'None' THEN 'Label' WHEN 'ComboBox' THEN 'ComboTextValue' WHEN 'TextBox' THEN 'TextBox'  END,
					   CCALPHA2 AS FILEDTYPE,'','',0,0,'','',''
				FROM   COM_CC50052 WITH(NOLOCK) WHERE parentid=@PARENTID AND ISGROUP=0  ORDER BY ORDERNO
			SET @R=@R+1
		END
			
		--ADDING SPACE TO SUB GROUPS AND SET MAIN GROUPID TO SUBGROUPID	FROM PAYROLL COMPONENTS						   
		IF(@YEAR>=0 AND @EMPNODE=0)  						   
		BEGIN
			UPDATE T SET T.NAME ='   '+ T.NAME FROM @TAB T INNER JOIN @TAB T1 ON T.PARENTID=T1.NODEID AND T1.ISGROUP=1 AND T.ISGROUP=1
			--UPDATING GROUPID TO RELATED ITEMS
			UPDATE T SET T.GROUPID =T1.NODEID FROM @TAB T INNER JOIN @TAB T1 ON T.PARENTID=T1.NODEID
			
			SELECT LFT,ORDERNO,PARENTID,NODEID,NAME,ISGROUP,CONTROLTYPE ,FIELDTYPE,GROUPID ,AMOUNTLIMIT,AMOUNT,SELECTEDNODE,SELECTEDAMTLIMIT,NewAmountLimit,NewSELECTEDAMTLIMIT  FROM @TAB ORDER BY ID,PARENTID,NODEID,ORDERNO
		END
		--ADDING SPACE TO SUB GROUPS AND SET MAIN GROUPID TO SUBGROUPID	FROM PAY_YEARWISETAXAMOUNTLIMIT TABLE
		ELSE IF (@YEAR>0 AND @EMPNODE>0 AND (SELECT COUNT(*) FROM PAY_YearwiseTaxAmountLimit WITH(NOLOCK) WHERE YEAR=@YEAR)>0)
		BEGIN
			UPDATE T SET T.NAME ='   '+ T.NAME FROM @TAB T INNER JOIN @TAB T1 ON T.PARENTID=T1.NODEID AND T1.ISGROUP=1 AND T.ISGROUP=1
			--UPDATING GROUPID TO RELATED ITEMS
			UPDATE T SET T.GROUPID =T1.NODEID FROM @TAB T INNER JOIN @TAB T1 ON T.PARENTID=T1.NODEID
			--UPDATING AMOUNT LIMIT AND SELECTED NODE AMOUNT LIMIT
			UPDATE T SET T.AMOUNTLIMIT=T1.AMOUNTLIMIT,T.SELECTEDAMTLIMIT=T1.AMOUNTLIMIT FROM @TAB T INNER JOIN PAY_YearwiseTaxAmountLimit T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@YEAR AND T1.Regime='Old'

			UPDATE T SET T.NewAmountLimit=T1.AMOUNTLIMIT,T.NewSELECTEDAMTLIMIT=T1.AMOUNTLIMIT FROM @TAB T INNER JOIN PAY_YearwiseTaxAmountLimit T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@YEAR AND T1.Regime='New'
			
			IF ((SELECT COUNT(*) FROM PAY_EmpTaxDeclaration WITH(NOLOCK) WHERE YEAR=@YEAR AND EMPNODE=@EMPNODE)>0)
				UPDATE T SET T.AMOUNT =T1.AMOUNT,T.SELECTEDNODE =T1.COMPONENTID FROM @TAB T INNER JOIN PAY_EmpTaxDeclaration T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@YEAR AND T1.EMPNODE=@EMPNODE		
			
			SELECT LFT,ORDERNO,PARENTID,NODEID,NAME,ISGROUP,CONTROLTYPE ,FIELDTYPE,GROUPID ,AMOUNTLIMIT,AMOUNT,SELECTEDNODE,SELECTEDAMTLIMIT,NewAmountLimit,NewSELECTEDAMTLIMIT  FROM @TAB ORDER BY ID,PARENTID,NODEID,ORDERNO
			SELECT * FROM PAY_EmpTaxHRAInfo WITH(NOLOCK) WHERE  YEAR=@YEAR and EMPNODE=@EMPNODE
		END
		ELSE
		BEGIN
			SELECT 'Please define the income tax amount limit for the selected year' as ITComponentsValidationMessage
		END
	END
	--FOR INCOMETAX AMOUNT LIMIT
	ELSE IF ISNULL(@FLAG,0)=1 
	BEGIN
		DECLARE @TAB1 TABLE(ID INT IDENTITY(1,1),LFT INT,	ORDERNO INT,			PARENTID INT,
							NODEID INT,				NAME VARCHAR(200),		ISGROUP INT,
							CONTROLTYPE VARCHAR(50),FIELDTYPE VARCHAR(100), GROUPID INT,
							AMOUNTLIMIT VARCHAR(100))
		DECLARE @TABGROUPS1 TABLE(ID INT IDENTITY(1,1),LFT INT,	ORDERNO INT,			PARENTID INT,
							NODEID INT,				NAME VARCHAR(200),		ISGROUP INT,
							CONTROLTYPE VARCHAR(50),FIELDTYPE VARCHAR(100), GROUPID INT,
							AMOUNTLIMIT VARCHAR(100))
		--LOADING GROUP COMPONENTS
		INSERT INTO @TABGROUPS1
				SELECT	 LFT,CCALPHA3 ORDERNO,PARENTID,NODEID,CASE ISGROUP WHEN 0 THEN '      '+ NAME ELSE NAME END,ISGROUP,CASE ISNULL(CCALPHA1,'') WHEN '' THEN 'Label' WHEN 'None' THEN 'Label' WHEN 'ComboBox' THEN 'TextBox' WHEN 'TextBox' THEN 'TextBox'  END,CCALPHA2 AS FILEDTYPE,'',''
				FROM     COM_CC50052 WITH(NOLOCK) WHERE LFT >=@LFT AND RGT<=@RGT AND isnull(CCALPHA3,0)>0 AND ISGROUP=1 ORDER BY NODEID,ORDERNO
		
		--LOADING GROUPS AND COMPONENTS BASED ON GROUP SELECTED
		SET @R=1
		SELECT @TRC=COUNT(*) FROM @TABGROUPS1	
		WHILE(@R<=@TRC)
			BEGIN
				INSERT INTO @TAB1 SELECT  LFT, ORDERNO,PARENTID,NODEID,NAME,ISGROUP,CONTROLTYPE ,FIELDTYPE,GROUPID ,AMOUNTLIMIT FROM @TABGROUPS1 WHERE ID=@R
				SELECT @PARENTID=NODEID FROM @TABGROUPS1 WHERE ID=@R
			
				INSERT INTO @TAB1 
				SELECT LFT,CCALPHA3 ORDERNO,PARENTID,NODEID,CASE ISGROUP WHEN 0 THEN '      '+ NAME ELSE NAME END,ISGROUP,CASE ISNULL(CCALPHA1,'') WHEN '' THEN 'Label' WHEN 'None' THEN 'Label' WHEN 'ComboBox' THEN 'TextBox' WHEN 'TextBox' THEN 'TextBox'  END,CCALPHA2 AS FILEDTYPE,'',''
				FROM   COM_CC50052 WITH(NOLOCK) WHERE parentid=@PARENTID AND ISGROUP=0 AND (ccAlpha5=@Regime or isnull(ccAlpha5,'Both')='Both') ORDER BY ORDERNO
			SET @R=@R+1
		END									
		
		--UPDATING AMOUNT LIMIT FROM PAY_YEARWISETAXAMOUNTLIMIT TABLE
		IF ((SELECT COUNT(*) FROM PAY_YearwiseTaxAmountLimit WITH(NOLOCK) WHERE YEAR=@YEAR AND REGIME=@Regime)>0)
			UPDATE T SET T.AMOUNTLIMIT=T1.AMOUNTLIMIT FROM @TAB1 T INNER JOIN PAY_YearwiseTaxAmountLimit T1 ON T.NODEID=T1.COMPONENTID AND T1.YEAR=@YEAR AND T1.REGIME=@Regime
		
		INSERT INTO @TAB1
			SELECT  @RGT+1,0,0,994,'Other Components',1,'Label','',0,0
		INSERT INTO @TAB1
			SELECT  @RGT+2,0,0,995,'80C Amount Limit',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=995 AND YEAR=@YEAR AND REGIME=@Regime)
		INSERT INTO @TAB1
			SELECT  @RGT+3,0,0,996,'Per Children Amount',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=996 AND YEAR=@YEAR AND REGIME=@Regime)
		INSERT INTO @TAB1
			SELECT  @RGT+4,0,0,997,'No Of Children',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=997 AND YEAR=@YEAR AND REGIME=@Regime)
		INSERT INTO @TAB1
			SELECT  @RGT+5,0,0,998,'Conveyance',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=998 AND YEAR=@YEAR AND REGIME=@Regime)
		INSERT INTO @TAB1
			SELECT  @RGT+6,0,0,999,'Rebate',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=999 AND YEAR=@YEAR AND REGIME=@Regime)
		INSERT INTO @TAB1
			SELECT  @RGT+7,0,0,1000,'Standard Deduction',0,'TextBox','',0,(SELECT ISNULL(AmountLimit,0) FROM PAY_YearwiseTaxAmountLimit WHERE COMPONENTID=1000 AND YEAR=@YEAR AND REGIME=@Regime)
		
		--ADDING SPACE TO SUB GROUP NAMES
		UPDATE T SET T.NAME ='   '+ T.NAME FROM @TAB1 T INNER JOIN @TAB1 T1 ON T.PARENTID=T1.NODEID AND T1.ISGROUP=1 AND T.ISGROUP=1
		--UPDATING GROUPID TO RELATED ITEMS
		UPDATE T SET T.GROUPID =T1.NODEID FROM @TAB1 T INNER JOIN @TAB1 T1 ON T.PARENTID=T1.NODEID
		
		SELECT ORDERNO,PARENTID,NODEID,NAME,ISGROUP,CONTROLTYPE ,FIELDTYPE,GROUPID ,AMOUNTLIMIT  FROM @TAB1 ORDER BY ID,PARENTID,ORDERNO,NODEID
		--ORDER BY ID,PARENTID,NODEID,ORDERNO
	END
	
SET NOCOUNT OFF;  
RETURN 1  
END TRY  
BEGIN CATCH    
  --Return exception info [Message,Number,ProcedureName,LineNumber]    
  IF ERROR_NUMBER()=50000  
  BEGIN  
   SELECT ErrorMessage,ErrorNumber FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=ERROR_MESSAGE() AND LanguageID=@LangID  
  END  
  ELSE  
  BEGIN  
   SELECT ErrorMessage, ERROR_MESSAGE() AS ServerMessage,ERROR_NUMBER() as ErrorNumber, ERROR_PROCEDURE()as ProcedureName, ERROR_LINE() AS ErrorLine  
   FROM COM_ErrorMessages WITH(NOLOCK) WHERE ErrorNumber=-999 AND LanguageID=@LangID  
  END   
SET NOCOUNT OFF    
RETURN -999     
END CATCH

GO
