USE PACT2C276
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPAY_ExtGetAvlblNoofDays]
	@FromDate [varchar](20) = null,
	@ToDate [varchar](20) = null,
	@EmployeeID [int] = 0,
	@LeaveType [int] = 0,
	@Session [varchar](20) = 'Both',
	@userid [int] = 1,
	@langid [int] = 1
WITH ENCRYPTION, EXECUTE AS CALLER
AS
BEGIN
SET NOCOUNT ON;
DECLARE @NOOFHOLIDAYS INT,@WEEKLYOFFCOUNT INT,@GRADE INT,@INCREXC VARCHAR(50),@ATATIME INT,@MAXLEAVES INT
DECLARE @CurrYearLeavestaken DECIMAL(9,2),@CurrDaterangeLeavestaken DECIMAL(9,2),@MWKOFFS FLOAT,@MHDAYS FLOAT
DECLARE @FDATE DATETIME,@TDATE DATETIME
DECLARE @CurrMonthOpeningBalance DECIMAL(9,2)

DECLARE @MONTH111 DATETIME,@MONTH222 DATETIME
DECLARE @MONTH13 DATETIME,@MONTH14 DATETIME

DECLARE @MONTH1 DATETIME,@MONTH2 DATETIME,@MONTH3 DATETIME,@MONTH4 DATETIME,@MONTH5 DATETIME,@MONTH6 DATETIME
DECLARE @MONTH7 DATETIME,@MONTH8 DATETIME,@MONTH9 DATETIME,@MONTH10 DATETIME,@MONTH11 DATETIME,@MONTH12 DATETIME
DECLARE @YEARDIFF INT, @YC INT,@EMPDOJ DATETIME--,@ALStartDate DATETIME,@ALEndDate DATETIME
DECLARE @Year INT,@ALStartMonth INT,@ALStartMonthYear DATETIME,@ALEndMonthYear DATETIME,@ExstAppliedEncashdays DECIMAL(9,2),@PayrollDate DATETIME,@FSEncashdays DECIMAL(9,2)
DECLARE @LocID INT,@DontConsiderDocs NVARCHAR(10),@DontConsiderDocsDays NVARCHAR(10),@PREVMONTH INT,@NEXTMONTH INT,@HALFDAY FLOAT
DECLARE @AssignedLeavesOP INT,@AvlblLeavesOP DECIMAL(9,2) ,@FromDateOP DATETIME,@ToDateOP DATETIME

CREATE TABLE #MONTHTAB (ID INT IDENTITY(1,1),STDATE DATETIME,EDDATE DATETIME)
CREATE TABLE #EMPWEEKLYOFFMP(WK11 varchar(50),WK12 varchar(50),WK21 varchar(50),WK22 varchar(50), WK31 varchar(50),
											   WK32 varchar(50),WK41 varchar(50),WK42 varchar(50),WK51 varchar(50),WK52 varchar(50),WEFDATE DATETIME)
CREATE TABLE #WEEKLYOFFMP(WEEKLYWEEKOFFNO int,DAYNAME varchar(100),WEFDATE DATETIME)	
CREATE TABLE #EMPWEEKLYOFFMP1(WK11 varchar(50),WK12 varchar(50),WK21 varchar(50),WK22 varchar(50), WK31 varchar(50),
											   WK32 varchar(50),WK41 varchar(50),WK42 varchar(50),WK51 varchar(50),WK52 varchar(50),WEFDATE DATETIME)
CREATE TABLE #WEEKLYOFFMP1(WEEKLYWEEKOFFNO int,DAYNAME varchar(100),WEFDATE DATETIME)
CREATE TABLE #WEEKOFFCOUNT (ID INT ,WEEKDATE DATETIME,DAYNAME VARCHAR(50),WEEKNO INT,COUNT INT)
CREATE TABLE #DATESAPPLIEDCOUNT (FDATE DATETIME,TDATE DATETIME,STODATE DATETIME,EODATE DATETIME,NOOFDAYS DECIMAL(9,2))
create TABLE #DATESCOUNT  (SNO INT IDENTITY(1,1),ID INT ,DATE1 DATETIME,DAYNAME VARCHAR(50),WEEKNO INT,COUNT INT,NOOFDAYS DECIMAL(9,2),FLAG INT,IncExc varchar(5))
SET @MWKOFFS=0
SET @MHDAYS=0 
SET @NOOFHOLIDAYS= 0 
SET @WEEKLYOFFCOUNT=0
SET @CurrYearLeavestaken=0
SET @CurrYearLeavestaken=0
SET @AssignedLeavesOP=0
SET @AvlblLeavesOP=0

SELECT @DontConsiderDocs=Value From ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='DontConsiderEmpLeavesLoansRecData'
SELECT @DontConsiderDocsDays=Value From ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='DontConsiderEmpLeavesLoansRecDataDays'


----READING START MONTH FROM GLOBAL PREFERENCES
--SELECT @ALStartMonth=ISNULL(VALUE,1) FROM ADM_GlobalPreferences WHERE NAME='LeaveYear'

----SET FIRST DATE TO GIVEN MONTH IN GLOBAL PREFERENCES
--SET @ALStartDate= CONVERT(VARCHAR,@Year)+'-' + DATENAME(MONTH,DATEADD(MONTH,@ALStartMonth,-1))+'-' +'01'
--SET @ALStartDate=CONVERT(DATETIME,@ALStartDate)

----SET LAST DATE TO ENDMONTH FOR THE NEXT YEAR (1YEAR)
--SET @ALEndDate=DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,DATEADD(M,11,@ALStartDate))+1,0))
--SET @ALEndDate=CONVERT(DATETIME,@ALEndDate)

SET @PayrollDate=DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DATETIME,@ToDate)),0)
IF(@DontConsiderDocs='True' AND CONVERT(INT,@DontConsiderDocsDays)>0 )
BEGIN
			INSERT INTO #DATESAPPLIEDCOUNT
			SELECT CONVERT(DATETIME,dcAlpha4),CONVERT(DATETIME,dcAlpha5),CONVERT(DATETIME,@FromDate),CONVERT(DATETIME,@ToDate),ISNULL(dcAlpha7,0) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
			WHERE  ID.CostCenterID=40062 AND DC.DCCCNID51=@EmployeeID  AND  DC.dcCCNID52=@LeaveType AND ID.STATUSID=369 
			       AND CONVERT(DATETIME,ID.DocDate)< CONVERT(DATETIME,CONVERT(NVARCHAR,(CONVERT(NVARCHAR,@DontConsiderDocsDays) +'-'+ CONVERT(NVARCHAR(3),DATENAME(MONTH,@PayrollDate))+'-'+ CONVERT(NVARCHAR,YEAR(@PayrollDate))))) 
END
ELSE IF (@DontConsiderDocs='False')
BEGIN
		   INSERT INTO #DATESAPPLIEDCOUNT
		   SELECT CONVERT(DATETIME,dcAlpha4),CONVERT(DATETIME,dcAlpha5),CONVERT(DATETIME,@FromDate),CONVERT(DATETIME,@ToDate),ISNULL(dcAlpha7,0) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
		   WHERE  ID.CostCenterID=40062 AND DC.DCCCNID51=@EmployeeID  AND  DC.dcCCNID52=@LeaveType AND ID.STATUSID=369
END
if((select count(*) from #DATESAPPLIEDCOUNT )>0)
begin

IF((SELECT COUNT(*) FROM ADM_CostCenterDef WITH(NOLOCK) WHERE CostCenterID=50051 and SysColumnName ='CCNID2' and IsColumnInUse=1 and UserProbableValues='H')>0)
	SELECT @LocID=HistoryNodeID FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID=@EmployeeID AND CostCenterID=50051 AND HistoryCCID=50002 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,@PayrollDate)) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,@PayrollDate) OR ToDate IS NULL)
ELSE
	SELECT @LocID=ISNULL(CC.CCNID2,1) FROM COM_CC50051 C51 WITH(NOLOCK),COM_CCCCDATA CC  WITH(NOLOCK) WHERE C51.NODEID=CC.NODEID AND C51.NODEID=@EmployeeID

--if (isnull(@LocID,0)=0)
--	set @LocID=1
print 'loc'
print @LocID

SELECT @YEARDIFF=DATEDIFF(yyyy,@FromDate,@ToDate)
SET @YC=0
----FOR START DATE AND END DATE OF LEAVEYEAR
EXEC [spPAY_EXTGetLeaveyearDates] @FromDate,@ALStartMonthYear OUTPUT,@ALEndMonthYear OUTPUT
print 'edm'
print @ALEndMonthYear
	
IF (isnull(@YEARDIFF,0)=1 and YEAR(@FromDate)<>YEAR(@ToDate))
	SET @YEARDIFF=2

--START : LOADING MONTHS BASED ON GIVEN YEAR RANGE FROM FROMDATE AND TODATE
IF ISNULL(@YEARDIFF,0)>=2
BEGIN
	SET @FDATE=@FromDate
	WHILE(@YC<=@YEARDIFF)
	BEGIN
		
		IF(@YC=0)
		BEGIN
			SET @MONTH111 =dateadd(m,-2,@FDATE)
			SET @MONTH222 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE),0))
		END
		
		IF(@YC=0)
			SET @MONTH1 =@FDATE
		ELSE
			SET @MONTH1 =DATEADD(MONTH,DATEDIFF(MONTH,0,CONVERT(DATETIME, @FDATE)),0)
					
		SET @MONTH2 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+2,0))
		SET @MONTH3 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+2,0)))
		SET @MONTH4 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+4,0))
		SET @MONTH5 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+4,0)))
		SET @MONTH6 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+6,0))
		SET @MONTH7 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+6,0)))
		SET @MONTH8 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+8,0))
		SET @MONTH9 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+8,0)))
		SET @MONTH10 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+10,0))
		SET @MONTH11 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+10,0)))
		SET @MONTH12 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+12,0))

		IF(@YC=0)
		BEGIN
			SET @MONTH13 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+12,0)))
			SET @MONTH14 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@FDATE)+14,0))
				
			INSERT INTO #MONTHTAB VALUES(@MONTH111,@MONTH222)
		END
		
		INSERT INTO #MONTHTAB VALUES(@MONTH1,@MONTH2)
		INSERT INTO #MONTHTAB VALUES(@MONTH3,@MONTH4)
		INSERT INTO #MONTHTAB VALUES(@MONTH5,@MONTH6)
		INSERT INTO #MONTHTAB VALUES(@MONTH7,@MONTH8)
		INSERT INTO #MONTHTAB VALUES(@MONTH9,@MONTH10)
		INSERT INTO #MONTHTAB VALUES(@MONTH11,@MONTH12)

		INSERT INTO #MONTHTAB VALUES(@MONTH13,@MONTH14)
		
		SET @FDATE=DATEADD(YY,1,@FDATE)
		
		IF(@FDATE>@ToDate)
			SET @YC=@YEARDIFF
		
	SET @YC=@YC+1
	END
END
ELSE
BEGIN

	SET @MONTH111 =dateadd(m,-2,@ALStartMonthYear)
	SET @MONTH222 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear),0))

	SET @MONTH1 =@ALStartMonthYear
	SET @MONTH2 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+2,0))
	SET @MONTH3 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+2,0)))
	SET @MONTH4 =DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+4,0))
	SET @MONTH5 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+4,0)))
	SET @MONTH6 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+6,0))
	SET @MONTH7 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+6,0)))
	SET @MONTH8 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+8,0))
	SET @MONTH9 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+8,0)))
	SET @MONTH10 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+10,0))
	SET @MONTH11 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+10,0)))
	SET @MONTH12 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+12,0))

	SET @MONTH13 = DATEADD(d,1,DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+12,0)))
	SET @MONTH14 = DATEADD(D,-1,DATEADD(MM,DATEDIFF(M,0,@ALStartMonthYear)+14,0))
				
	INSERT INTO #MONTHTAB VALUES(@MONTH111,@MONTH222)
	
	INSERT INTO #MONTHTAB VALUES(@MONTH1,@MONTH2)
	INSERT INTO #MONTHTAB VALUES(@MONTH3,@MONTH4)
	INSERT INTO #MONTHTAB VALUES(@MONTH5,@MONTH6)
	INSERT INTO #MONTHTAB VALUES(@MONTH7,@MONTH8)
	INSERT INTO #MONTHTAB VALUES(@MONTH9,@MONTH10)
	INSERT INTO #MONTHTAB VALUES(@MONTH11,@MONTH12)

	INSERT INTO #MONTHTAB VALUES(@MONTH13,@MONTH14)
END
--END : LOADING MONTHS BASED ON GIVEN YEAR RANGE FROM FROMDATE AND TODATE
--END:FOR START AND END MONTH	

--EMPLOYEE DATE OF JOINING
SELECT @EMPDOJ=CONVERT(DATETIME,DOJ) FROM COM_CC50051 WITH(NOLOCK) WHERE NODEID=@EmployeeID
--FOR Grade

DECLARE @IsGradeWiseMP BIT
SELECT @IsGradeWiseMP=CONVERT(BIT,Value) FROM ADM_GlobalPreferences WITH(NOLOCK) WHERE Name='GradeWiseMonthlyPayroll'
IF @IsGradeWiseMP=1
BEGIN
	IF((SELECT COUNT(*) FROM ADM_CostCenterDef WITH(NOLOCK) WHERE CostCenterID=50051 and SysColumnName ='CCNID53' and IsColumnInUse=1 and UserProbableValues='H')>0)
	BEGIN
		SELECT @Grade=ISNULL(HistoryNodeID,0) FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID=@EmployeeID AND CostCenterID=50051 AND HistoryCCID=50053 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,@PayrollDate)) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,@PayrollDate) OR ToDate IS NULL)
		IF(CONVERT(DATETIME,@EMPDOJ)>CONVERT(DATETIME,@PayrollDate) AND ISNULL(@Grade,0)=0)
			SELECT @Grade=ISNULL(HistoryNodeID,0) FROM COM_HistoryDetails WITH(NOLOCK) WHERE NodeID=@EmployeeID AND CostCenterID=50051 AND HistoryCCID=50053 AND (CONVERT(DATETIME,FromDate)<=CONVERT(DATETIME,@EMPDOJ)) AND (CONVERT(DATETIME,ToDate)>=CONVERT(DATETIME,@EMPDOJ) OR ToDate IS NULL)
	END
	ELSE
		SELECT @Grade=ISNULL(CCNID53,0) FROM COM_CCCCDATA WITH(NOLOCK) WHERE COSTCENTERID=50051 AND NODEID=@EmployeeID
END
ELSE
BEGIN
	SET @Grade=1
END

PRINT 'GRADE'
PRINT @Grade
PRINT @PayrollDate

	IF(@FromDate is not null and @ToDate is not null and isnull(@Session,'Both')='Both')
	BEGIN			
		--INCLUDE OR EXCLUDE HOLIDAYS, ATATIME,MAXLEAVES AND WEEKLYOFFS
		SELECT @INCREXC=ISNULL(INCLUDEREXCLUDE,''),@ATATIME=ISNULL(ATATIME,0),@MAXLEAVES=ISNULL(MAXLEAVES,0) FROM COM_CC50054 WITH(NOLOCK)
		WHERE  GRADEID=@GRADE AND COMPONENTID=@LeaveType AND PAYROLLDATE=(SELECT MAX(PAYROLLDATE) FROM COM_CC50054  WITH(NOLOCK) WHERE CONVERT(DATETIME,PAYROLLDATE)<=CONVERT(DATETIME,@PayrollDate) AND GradeID=@Grade)
				
		--START :CURRENT DATERANGE LEAVES TAKEN
		--START: LOADING DATES FROM #MONTHTAB TABLE		   
		--create TABLE #DATESCOUNT  (SNO INT IDENTITY(1,1),ID INT ,DATE1 DATETIME,DAYNAME VARCHAR(50),WEEKNO INT,COUNT INT,NOOFDAYS DECIMAL(9,2),FLAG INT,IncExc varchar(5))
		DECLARE @STARTDATE1 DATETIME,@ENDATE1 DATETIME
		DECLARE @MRC AS INT,@MC AS INT,@MID INT
		
		SET @MC=1
		SELECT @MRC=COUNT(*) FROM #MONTHTAB
		WHILE (@MC<=@MRC)
		BEGIN
			SELECT @STARTDATE1=CONVERT(DATETIME,STDATE),@ENDATE1=CONVERT(DATETIME,EDDATE) FROM #MONTHTAB WHERE ID=@MC
			;WITH DATERANGE AS
			(
			SELECT @STARTDATE1 AS DT,1 AS ID
			UNION ALL
			SELECT DATEADD(DD,1,DT),DATERANGE.ID+1 FROM DATERANGE WHERE ID<=DATEDIFF("d",convert(varchar,@STARTDATE1,101),convert(varchar,@ENDATE1,101))
			)
			
			INSERT INTO #DATESCOUNT
			SELECT ROW_NUMBER() OVER (ORDER BY DT) AS ID,DT AS WEEKDATE,DATENAME(DW,DT) AS DAY,0,0,0,0,'' FROM DATERANGE	--WHERE (DATEPART(DW,DT)=1 OR DATEPART(DW,DT)=7)
		SET @MC=@MC+1
		END
		--END: LOADING DATES FROM #MONTHTAB TABLE	
		--START: LOADING DATA BASED ON FROMDATE AND TODATE GIVEN 
		--CREATE TABLE #DATESAPPLIEDCOUNT (FDATE DATETIME,TDATE DATETIME,STODATE DATETIME,EODATE DATETIME,NOOFDAYS DECIMAL(9,2))
		--IF(@DontConsiderDocs='True' AND CONVERT(INT,@DontConsiderDocsDays)>0 )
		--BEGIN
		--	INSERT INTO #DATESAPPLIEDCOUNT
		--	SELECT CONVERT(DATETIME,dcAlpha4),CONVERT(DATETIME,dcAlpha5),CONVERT(DATETIME,@FromDate),CONVERT(DATETIME,@ToDate),ISNULL(dcAlpha7,0) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
		--	WHERE  ID.CostCenterID=40062 AND DC.DCCCNID51=@EmployeeID  AND  DC.dcCCNID52=@LeaveType AND ID.STATUSID=369 
		--	       AND CONVERT(DATETIME,ID.DocDate)< CONVERT(DATETIME,CONVERT(NVARCHAR,(CONVERT(NVARCHAR,@DontConsiderDocsDays) +'-'+ CONVERT(NVARCHAR(3),DATENAME(MONTH,@PayrollDate))+'-'+ CONVERT(NVARCHAR,YEAR(@PayrollDate))))) 
		--END
		--ELSE IF (@DontConsiderDocs='False')
		--BEGIN
		--   INSERT INTO #DATESAPPLIEDCOUNT
		--   SELECT CONVERT(DATETIME,dcAlpha4),CONVERT(DATETIME,dcAlpha5),CONVERT(DATETIME,@FromDate),CONVERT(DATETIME,@ToDate),ISNULL(dcAlpha7,0) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
		--   WHERE  ID.CostCenterID=40062 AND DC.DCCCNID51=@EmployeeID  AND  DC.dcCCNID52=@LeaveType AND ID.STATUSID=369
		--END
		--END: LOADING DATA BASED ON FROMDATE AND TODATE GIVEN 			 
		--START: UPDATING #DATESCOUNT TABLE 'COUNT' COLUMN TO 1 FROM LIST OF #DATESAPPLIEDCOUNT TABLE
		DECLARE @RC AS INT,@IC AS INT,@TRC AS INT,@DTT AS DATETIME
		SET @IC=1
	IF((Select Count(*) from #DATESAPPLIEDCOUNT)>0)--test
	begin--test
		
		SELECT @TRC=COUNT(*) FROM #DATESCOUNT
		WHILE(@IC<=@TRC)
		BEGIN
			SELECT @DTT=DATE1 FROM #DATESCOUNT WHERE SNO=@IC
			SELECT @RC=COUNT(*) FROM #DATESAPPLIEDCOUNT WHERE CONVERT(DATETIME,@DTT) between CONVERT(DATETIME,FDATE) and CONVERT(DATETIME,TDATE)
		    UPDATE #DATESCOUNT SET COUNT=ISNULL(@RC,0) WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT)
		    UPDATE #DATESCOUNT SET FLAG=1 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) and ISNULL(@RC,0)>0
		SET @IC=@IC+1
		END
		UPDATE DT SET  DT.NOOFDAYS=ISNULL(DAC.NOOFDAYS,0) FROM #DATESCOUNT DT INNER JOIN #DATESAPPLIEDCOUNT DAC ON DT.DATE1=DAC.FDATE AND ISNULL(DAC.NOOFDAYS,0)=0.5
		--END: UPDATING #DATESCOUNT TABLE 'COUNT' COLUMN TO 1 FROM LIST OF #DATESAPPLIEDCOUNT TABLE 
		--END :CURRENT DATERANGE LEAVES TAKEN	
			   
	    --CALCULATE MAXNOOFDAYS
		IF ISNULL(@MAXLEAVES,0)>0
			SET @MAXLEAVES=ISNULL(@MAXLEAVES,0)-ISNULL(@CurrYearLeavestaken,0)
		
		--START HOLIDAYS COUNT
		IF EXISTS(SELECT SYSCOLUMNNAME FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=40051 AND ISCOLUMNINUSE=1 AND SYSCOLUMNNAME ='DCCCNID2')
		BEGIN
			SELECT @NOOFHOLIDAYS=COUNT(dcAlpha1) FROM INV_DOCDETAILS ID WITH(NOLOCK) INNER JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID INNER JOIN COM_DocCCData CC WITH(NOLOCK) ON ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
			WHERE  ID.COSTCENTERID=40051 and ISDATE(TD.dcAlpha1)=1 AND CC.DCCCNID2=@LocID AND ID.STATUSID=369 AND CONVERT(DATETIME,dcAlpha1) between CONVERT(DATETIME,@FromDate) AND CONVERT(DATETIME,@ToDate)
		END
		ELSE
		BEGIN
			SELECT @NOOFHOLIDAYS=COUNT(dcAlpha1) FROM COM_DocTextData TD WITH(NOLOCK),INV_DOCDETAILS ID WITH(NOLOCK)
			WHERE ID.INVDOCDETAILSID=TD.INVDOCDETAILSID AND ID.COSTCENTERID=40051 AND ID.STATUSID=369 and ISDATE(TD.dcAlpha1)=1	AND CONVERT(DATETIME,dcAlpha1) between CONVERT(DATETIME,@FromDate) AND CONVERT(DATETIME,@ToDate)
		END
		--END HOLIDAYS COUNT
		
		--START WEEKLYOFF COUNT
					--LOADING WEEKLYOFF INFORMATION OF EMPLOYEE
					DECLARE @STRQUERY NVARCHAR(MAX),@I INT,@J INT,@COLNAME VARCHAR(15)
					--CREATE TABLE #EMPWEEKLYOFFMP(WK11 varchar(50),WK12 varchar(50),WK21 varchar(50),WK22 varchar(50), WK31 varchar(50),
					--						   WK32 varchar(50),WK41 varchar(50),WK42 varchar(50),WK51 varchar(50),WK52 varchar(50),WEFDATE DATETIME)
					--CREATE TABLE #WEEKLYOFFMP(WEEKLYWEEKOFFNO int,DAYNAME varchar(100),WEFDATE DATETIME)	
					--CREATE TABLE #EMPWEEKLYOFFMP1(WK11 varchar(50),WK12 varchar(50),WK21 varchar(50),WK22 varchar(50), WK31 varchar(50),
					--						   WK32 varchar(50),WK41 varchar(50),WK42 varchar(50),WK51 varchar(50),WK52 varchar(50),WEFDATE DATETIME)
					--CREATE TABLE #WEEKLYOFFMP1(WEEKLYWEEKOFFNO int,DAYNAME varchar(100),WEFDATE DATETIME)
					SET @STRQUERY=''	   
											   
					--LOADING DATA FROM WEEKLYOFF MASTER											   
					INSERT INTO #EMPWEEKLYOFFMP 
					SELECT TOP 1 TD.dcAlpha2 WK11,TD.dcAlpha3 WK12,TD.dcAlpha4 WK21,TD.dcAlpha5 WK22,TD.dcAlpha6 WK31,TD.dcAlpha7 WK32,TD.dcAlpha8 WK41,TD.dcAlpha9 WK42,
						         TD.dcAlpha10 WK51,TD.dcAlpha11 WK52,CONVERT(DATETIME,ID.DUEDATE)	FROM COM_DocCCData DC WITH(NOLOCK),INV_DOCDETAILS ID WITH(NOLOCK),COM_DocTextData TD WITH(NOLOCK)
					WHERE        DC.INVDOCDETAILSID=ID.INVDOCDETAILSID AND TD.INVDOCDETAILSID=ID.INVDOCDETAILSID AND ID.COSTCENTERID=40053 AND DC.dcCCNID51=@EmployeeID	AND
					             CONVERT(DATETIME,ID.DUEDATE)<=CONVERT(DATETIME,@ToDate)
					ORDER BY     CONVERT(DATETIME,ID.DUEDATE) DESC
					
					--CHECKING FOR EMPLOYEE WEEKLY OFF COUNT FROM WEEKLYOFF MASTER IF NO DATA FOUND
					--LOADING DATA FROM EMPLOYEE MASTER
					IF (SELECT COUNT(*) FROM #EMPWEEKLYOFFMP)<=0
					BEGIN
						INSERT INTO #EMPWEEKLYOFFMP 
						SELECT WeeklyOff1,WeeklyOff2,WeeklyOff1,WeeklyOff2,WeeklyOff1,WeeklyOff2,WeeklyOff1,WeeklyOff2,
						       WeeklyOff1,WeeklyOff2,'01-01-1900'	FROM COM_CC50051 WITH(NOLOCK)
						WHERE  NODEID=@EmployeeID
						DELETE FROM #EMPWEEKLYOFFMP WHERE ISNULL(WK11,'None')='None' OR ISNULL(WK11,'0')='0'
						--EMPLOYEE MASTER
						SET @I=1
						SET @STRQUERY=''
						WHILE(@I<=5)
						BEGIN
							SET @J=1
							WHILE(@J<=2)
							BEGIN
								SET @COLNAME='WK'+CONVERT(VARCHAR,@I)+CONVERT(VARCHAR,@J)
								SET @STRQUERY=@STRQUERY+' UPDATE #EMPWEEKLYOFFMP SET '+ @COLNAME +'='''' where '+ @COLNAME +'=''None'''
								
							SET @J=@J+1
							END
						SET @I=@I+1
						END
						--PRINT @STRQUERY
						EXEC sp_executesql @STRQUERY
					END--ELSE CONDITION
					ELSE
					BEGIN
						INSERT INTO #EMPWEEKLYOFFMP1  SELECT * FROM #EMPWEEKLYOFFMP
						--SET NULL
						IF (SELECT COUNT(*) FROM #EMPWEEKLYOFFMP1)>0
						BEGIN
							SET @I=1
							SET @STRQUERY=''
							WHILE(@I<=5)
							BEGIN
								SET @J=1
								WHILE(@J<=2)
								BEGIN
									SET @COLNAME='WK'+CONVERT(VARCHAR,@I)+CONVERT(VARCHAR,@J)
									SET @STRQUERY=@STRQUERY+' update #EMPWEEKLYOFFMP1 set '+ @COLNAME +'='''' where '+ @COLNAME +'=''None'''
									
								SET @J=@J+1
								END
							SET @I=@I+1
							END
							PRINT @STRQUERY
							EXEC sp_executesql @STRQUERY
						END
						--EMPLOYEE MASTER
						IF((SELECT COUNT(*) FROM COM_CC50051 WHERE NODEID=@EmployeeID AND (ISNULL(WeeklyOff1,'')<>'' AND ISNULL(WeeklyOff1,'None')<>'None') AND (ISNULL(WeeklyOff2,'')<>'' AND ISNULL(WeeklyOff2,'None')<>'None'))>0)
						BEGIN
							SET @I=1
							SET @STRQUERY=''
							WHILE(@I<=5)
							BEGIN
								SET @J=1
								WHILE(@J<=2)
								BEGIN
									SET @COLNAME='WK'+CONVERT(VARCHAR,@I)+CONVERT(VARCHAR,@J)
									SET @STRQUERY=@STRQUERY+' UPDATE #EMPWEEKLYOFFMP1 SET '+ @COLNAME +'=WeeklyOff'+CONVERT(VARCHAR,@J)+' FROM COM_CC50051 WITH(NOLOCK)	WHERE  NODEID='+CONVERT(VARCHAR,@EmployeeID) +' AND ISNULL('+ @COLNAME +','''')=''''  AND ISNULL(WeeklyOff'+CONVERT(VARCHAR,@J)+',''None'')<>''None'''
								SET @J=@J+1
								END
							SET @I=@I+1
							END
							PRINT @STRQUERY
							EXEC sp_executesql @STRQUERY
						END
						ELSE
						BEGIN
							--GLOBAL PREFERENCE
							SET @I=1
							SET @STRQUERY=''
							WHILE(@I<=5)
							BEGIN
								SET @J=1
								WHILE(@J<=2)
								BEGIN
									SET @COLNAME='WK'+CONVERT(VARCHAR,@I)+CONVERT(VARCHAR,@J)
									--SET @STRQUERY=@STRQUERY+' update #EMPWEEKLYOFFMP set '+ @COLNAME +'='''' where '+ @COLNAME +'=''None'''
									SET @STRQUERY=@STRQUERY+' UPDATE #EMPWEEKLYOFFMP1 SET '+ @COLNAME +'=isnull(VALUE,'''') FROM ADM_GlobalPreferences WITH(NOLOCK)	WHERE  NAME=''WeeklyOff'+CONVERT(VARCHAR,@J)+''' AND ISNULL('+ @COLNAME +','''')=''''  AND ISNULL(VALUE,''None'')<>''None'''
								SET @J=@J+1
								END
							SET @I=@I+1
							END
							PRINT @STRQUERY
							EXEC sp_executesql @STRQUERY
						END
					END
					--CHECKING FOR EMPLOYEE WEEKLY OFF COUNT FROM EMPLOYEE MASTER IF NO DATA FOUND
		--LOADING DATA FROM PREFERENCES
		IF (SELECT COUNT(*) FROM #EMPWEEKLYOFFMP)<=0
		BEGIN
			INSERT INTO #WEEKLYOFFMP 
			SELECT case isnull(VALUE,'') when '' then 0 else 1 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff1'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 1 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff2'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 2 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff1'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 2 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff2'					  
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 3 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff1'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 3 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff2'					  
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 4 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff1'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 4 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff2'					  
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 5 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff1'
			UNION ALL
			SELECT case isnull(VALUE,'') when '' then 0 else 5 end,VALUE,'01-01-1900'	FROM ADM_GlobalPreferences  WHERE NAME='WeeklyOff2'		
		END
						
		--LOADING WEEKNO AND DAYNAME INTO ROWS FROM #EMPWEEKLYOFFMP TABLE (WEEKLYOFF AND EMPLOYEE MASTER)
		IF (SELECT COUNT(*) FROM #WEEKLYOFFMP)<=0
		BEGIN
			INSERT INTO #WEEKLYOFFMP
				select case isnull(WK11,'') when '' then 0 else 1 end,case isnull(WK11,'') when '' then '' else WK11 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK12,'') when '' then 0 else 1 end,case isnull(WK12,'') when '' then '' else WK12 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK21,'') when '' then 0 else 2 end,case isnull(WK21,'') when '' then '' else WK21 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK22,'') when '' then 0 else 2 end,case isnull(WK22,'') when '' then '' else WK22 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK31,'') when '' then 0 else 3 end,case isnull(WK31,'') when '' then '' else WK31 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK32,'') when '' then 0 else 3 end,case isnull(WK32,'') when '' then '' else WK32 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK41,'') when '' then 0 else 4 end,case isnull(WK41,'') when '' then '' else WK41 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK42,'') when '' then 0 else 4 end,case isnull(WK42,'') when '' then '' else WK42 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK51,'') when '' then 0 else 5 end,case isnull(WK51,'') when '' then '' else WK51 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
			UNION ALL
				select case isnull(WK52,'') when '' then 0 else 5 end,case isnull(WK52,'') when '' then '' else WK52 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP
		END
		IF((SELECT COUNT(*) FROM #EMPWEEKLYOFFMP1)>0)
		BEGIN	
			INSERT INTO #WEEKLYOFFMP1
				select case isnull(WK11,'') when '' then 0 else 1 end,case isnull(WK11,'') when '' then '' else WK11 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK12,'') when '' then 0 else 1 end,case isnull(WK12,'') when '' then '' else WK12 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK21,'') when '' then 0 else 2 end,case isnull(WK21,'') when '' then '' else WK21 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK22,'') when '' then 0 else 2 end,case isnull(WK22,'') when '' then '' else WK22 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK31,'') when '' then 0 else 3 end,case isnull(WK31,'') when '' then '' else WK31 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK32,'') when '' then 0 else 3 end,case isnull(WK32,'') when '' then '' else WK32 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK41,'') when '' then 0 else 4 end,case isnull(WK41,'') when '' then '' else WK41 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK42,'') when '' then 0 else 4 end,case isnull(WK42,'') when '' then '' else WK42 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK51,'') when '' then 0 else 5 end,case isnull(WK51,'') when '' then '' else WK51 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
			UNION ALL
				select case isnull(WK52,'') when '' then 0 else 5 end,case isnull(WK52,'') when '' then '' else WK52 end,convert(Datetime,WEFDATE) FROM #EMPWEEKLYOFFMP1
		END
		
		--LOADING WEEKDATE,DAYNAME AND WEEKNO FOR SELECTED DATERANGE
		--create table #WEEKOFFCOUNT (ID INT ,WEEKDATE DATETIME,DAYNAME VARCHAR(50),WEEKNO INT,COUNT INT)
		DECLARE @STARTDATE DATETIME,@STARTDATE2 DATETIME,@ENDATE2 DATETIME
		DECLARE @MRC2 AS INT,@MC2 AS INT,@MID2 INT
		
		SET @MC2=1
		
		SELECT @MRC2=COUNT(*) FROM #MONTHTAB
		WHILE (@MC2<=@MRC2)
		BEGIN
			SELECT @STARTDATE2=CONVERT(DATETIME,STDATE),@ENDATE2=CONVERT(DATETIME,EDDATE) FROM #MONTHTAB WHERE ID=@MC2
			;WITH DATERANGE AS
			(
			SELECT @STARTDATE2 AS DT,1 AS ID
			UNION ALL
			SELECT DATEADD(DD,1,DT),DATERANGE.ID+1 FROM DATERANGE WHERE ID<=DATEDIFF("d",convert(varchar,@STARTDATE2,101),convert(varchar,@ENDATE2,101))
			)
			
			INSERT INTO #WEEKOFFCOUNT
			SELECT ROW_NUMBER() OVER (ORDER BY DT) AS ID,DT AS WEEKDATE,DATENAME(DW,DT) AS DAY,0,0 FROM DATERANGE	--WHERE (DATEPART(DW,DT)=1 OR DATEPART(DW,DT)=7)
		SET @MC2=@MC2+1
		END
			
		--UPDATING WEEKNO IN WEEKOFFCOUNT TABLE BASED ON WEEKDATE OF MONTH
		--UPDATE #WEEKOFFCOUNT SET WEEKNO=((datepart(day,WEEKDATE)-1)/7)+1
		--------------------
						declare @PMS int,@PME int
						select @PMS=Value From ADM_GlobalPreferences where name='PayDayStart'
						select @PME=Value From ADM_GlobalPreferences where name='PayDayEnd'

						declare @PS INT,@PE INT
						declare @wd datetime,@TSwd datetime,@TEwd datetime,@dme datetime
						declare @wno int
						set @wno=0
						select @TSwd=MIN(Weekdate),@TEwd=MAX(Weekdate) FROM #WEEKOFFCOUNT
						--SET @TSwd='01-Nov-2019' SET @TEwd='01-Dec-2019'
						WHILE(@TSwd<=@TEwd)
						BEGIN
							IF(DAY(@TSwd)=@PMS)
							BEGIN
								set @wno=1
								Update #WEEKOFFCOUNT SET WEEKNo=@wno WHERE WeekDate=@TSwd
								set @dme=dateadd(day,-1,dateadd(m,1,@TSwd))
								
								Update #WEEKOFFCOUNT SET WEEKNo=@wno 
								where WeekDate between @TSwd AND DATEADD(day,6,@TSwd)
								
								SET @TSwd=DATEADD(day,7,@TSwd)
								set @wno=@wno+1
							END
							ELSE
							BEGIN
								if(@wno=0)
									SET @TSwd=DATEADD(day,1,@TSwd)
								else
								begin
									IF(DAY(DATEADD(day,6,@TSwd))<=@PME)
									begin
										Update #WEEKOFFCOUNT SET WEEKNo=@wno 
										where WeekDate between @TSwd AND DATEADD(day,6,@TSwd)
										SET @TSwd=DATEADD(day,7,@TSwd)
										set @wno=@wno+1

										if(DATEADD(day,6,@TSwd)>@dme)
										BEGIN
											Update #WEEKOFFCOUNT SET WEEKNo=@wno 
											where WeekDate between @TSwd AND @dme
											SET @TSwd=DATEADD(day,1,@dme)
										END
										
									end
									else 
									begin
										Update #WEEKOFFCOUNT SET WEEKNo=@wno 
										where WeekDate between @TSwd AND @dme
										SET @TSwd=DATEADD(day,1,@dme)
									end
									
								end
							END	
							
						END 

						--------------------------
			
		--UPDATING COUNT TO 1 IF WEEKNO AND DAYNAME IS WEEKLYOFF
		UPDATE WEEKOFFCOUNT SET WEEKOFFCOUNT.count=1 FROM #WEEKOFFCOUNT WEEKOFFCOUNT inner join #WEEKLYOFFMP WEEKLYOFF on WEEKLYOFF.WEEKLYWEEKOFFNO=WEEKOFFCOUNT.WEEKNO AND upper(WEEKLYOFF.DAYNAME)=upper(WEEKOFFCOUNT.DAYNAME)

		IF((select COUNT(*) from #WEEKLYOFFMP1)>0)
		BEGIN
		PRINT 'T'
			UPDATE WEEKOFFCOUNT SET WEEKOFFCOUNT.count=1 FROM #WEEKOFFCOUNT WEEKOFFCOUNT inner join #WEEKLYOFFMP1 WEEKLYOFF on WEEKLYOFF.WEEKLYWEEKOFFNO=WEEKOFFCOUNT.WEEKNO AND upper(WEEKLYOFF.DAYNAME)=upper(WEEKOFFCOUNT.DAYNAME)
				   AND convert(datetime,WEEKOFFCOUNT.weekdate)<=CONVERT(DATETIME,WEFDATE)
		END	
	
		--COUNTING WEEKLYOFFS IN GIVEN DATERANGE
		SELECT @WEEKLYOFFCOUNT=COUNT(*) FROM #WEEKOFFCOUNT WHERE COUNT=1 and convert(DATETIME,WEEKDATE) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate)
		--END WEEKLYOFF COUNT

		--START : UPDATING #DATESAPPLIEDCOUNT TABLE 'COUNT' COLUMN TO '3- FOR WEEKLYOFF' AND '4- FOR HOLIDAY'
		
		--UPDATING COUNT TO 3 IF DATEAPPLIEDRANGE DATE IS WEEKLYOFF
		UPDATE DATESCOUNT SET DATESCOUNT.count=3 FROM #WEEKOFFCOUNT WEEKOFFCOUNT inner join #DATESCOUNT DATESCOUNT ON CONVERT(DATETIME,DATESCOUNT.date1)= CONVERT(DATETIME,WEEKOFFCOUNT.weekdate) and WEEKOFFCOUNT.count=1
		--UPDATING COUNT TO 4 IF DATEAPPLIEDRANGE DATE IS HOLIDAY
		IF EXISTS(SELECT SYSCOLUMNNAME FROM ADM_COSTCENTERDEF WITH(NOLOCK) WHERE COSTCENTERID=40051 AND ISCOLUMNINUSE=1 AND SYSCOLUMNNAME ='DCCCNID2')
		BEGIN
			 UPDATE DATESCOUNT SET DATESCOUNT.count=4 FROM #DATESCOUNT DATESCOUNT inner join COM_DocTextData TD on CONVERT(DATETIME,DATESCOUNT.DATE1)=CONVERT(DATETIME,TD.dcAlpha1)
			 inner join INV_DOCDETAILS ID  on  ID.INVDOCDETAILSID=TD.INVDOCDETAILSID inner join COM_DocCCData CC  on  ID.INVDOCDETAILSID=CC.INVDOCDETAILSID
			 and ISDATE(TD.dcAlpha1)=1 AND CC.DCCCNID2=@LocID AND ID.STATUSID=369 AND CONVERT(DATETIME,DATE1) = CONVERT(DATETIME,TD.dcAlpha1) AND ID.COSTCENTERID=40051
		END
		ELSE
		BEGIN
			 UPDATE DATESCOUNT SET DATESCOUNT.count=4 FROM #DATESCOUNT DATESCOUNT inner join COM_DocTextData TD on CONVERT(DATETIME,DATESCOUNT.DATE1)=CONVERT(DATETIME,TD.dcAlpha1)
			 inner join INV_DOCDETAILS ID  on  ID.INVDOCDETAILSID=TD.INVDOCDETAILSID  AND ID.STATUSID=369 and ISDATE(TD.dcAlpha1)=1	 AND CONVERT(DATETIME,DATE1) = CONVERT(DATETIME,TD.dcAlpha1) AND ID.COSTCENTERID=40051
		END	
			
	
		--SELECT * FROM #DATESCOUNT
		--END : UPDATING #DATESAPPLIEDCOUNT TABLE 'COUNT' COLUMN TO '3- FOR WEEKLYOFF' AND '4- FOR HOLIDAY'
		--SET FLAG FOR ACTUAL DAYS
		print @INCREXC
		SET @IC=1
		SELECT @TRC=COUNT(*) FROM #DATESCOUNT
		WHILE(@IC<=@TRC)
		BEGIN
			SELECT @DTT=DATE1 FROM #DATESCOUNT WHERE SNO=@IC
			SELECT @RC=COUNT(*) FROM #DATESAPPLIEDCOUNT WHERE CONVERT(DATETIME,@DTT) between CONVERT(DATETIME,FDATE) and CONVERT(DATETIME,TDATE)
			--6 WEEKLY OFF / 7 HOLIDAY / 8 EXCLUDE BOTH
			IF ISNULL(@INCREXC,'')='IncludeHolidays' OR ISNULL(@INCREXC,'')='ExcludeWeeklyOffs'
				UPDATE #DATESCOUNT SET FLAG=0,IncExc='EW' WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) and ISNULL(@RC,0)>0 AND COUNT=3
			ELSE IF ISNULL(@INCREXC,'')='IncludeWeeklyOffs' OR ISNULL(@INCREXC,'')='ExcludeHolidays'
				UPDATE #DATESCOUNT SET FLAG=0,IncExc='EH' WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) and ISNULL(@RC,0)>0 AND COUNT=4
			ELSE IF ISNULL(@INCREXC,'')='IncludeBoth'
				UPDATE #DATESCOUNT SET FLAG=1 WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) and ISNULL(@RC,0)>0
			ELSE IF ISNULL(@INCREXC,'')='ExcludeBoth'
				UPDATE #DATESCOUNT SET FLAG=0,IncExc='EB' WHERE CONVERT(DATETIME,DATE1)=CONVERT(DATETIME,@DTT) and ISNULL(@RC,0)>0 AND COUNT IN (3,4)
			
		SET @IC=@IC+1
		END
		
		--
		SELECT @CurrYearLeavestaken=count(*) from #DATESCOUNT where count=1 and isnull(IncExc,'')=''
		--PRINT 'Current year leaves taken' + CONVERT(VARCHAR,@CurrYearLeavestaken)
		
		--SELECT * FROM #DATESCOUNT
		SELECT @CurrDaterangeLeavestaken=COUNT(*) FROM #DATESCOUNT WHERE convert(DATETIME,date1) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate) and flag=1 --and COUNT=1 
		--SELECT * FROM #DATESCOUNT WHERE convert(DATETIME,date1) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate) and flag=1 --and COUNT=1 
		SELECT @MWKOFFS=COUNT(*) FROM #DATESCOUNT WHERE convert(DATETIME,date1) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate) and flag=1 and COUNT=3 
		SELECT @MHDAYS=COUNT(*) FROM #DATESCOUNT WHERE convert(DATETIME,date1) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate) and flag=1 and COUNT=4
		--SELECT * FROM #DATESCOUNT WHERE convert(DATETIME,date1) between CONVERT(DATETIME,@FromDate) and CONVERT(DATETIME,@ToDate) and COUNT=3
		--PRINT 'Current Date range leaves taken' + CONVERT(VARCHAR,@CurrDaterangeLeavestaken)
		
		
		SELECT @PREVMONTH=COUNT(*) FROM #DATESCOUNT WHERE COUNT=1 and (convert(DATETIME,@FromDate)) > (CONVERT(DATETIME,date1))
		--PRINT 'Previous month taken leaves' + CONVERT(VARCHAR,@PREVMONTH)
		
		SELECT @NEXTMONTH=COUNT(*) FROM #DATESCOUNT WHERE COUNT=1 and (convert(DATETIME,@FromDate)) <(CONVERT(DATETIME,date1) )
		--PRINT 'Next month taken leaves'+ CONVERT(VARCHAR,@NEXTMONTH)
		
		IF ISNULL(@NEXTMONTH,0)=0 AND ISNULL(@PREVMONTH,0)=0
			SET @CurrMonthOpeningBalance=@CurrDaterangeLeavestaken
		ELSE IF ISNULL(@NEXTMONTH,0)>0 AND ISNULL(@PREVMONTH,0)>0
			SET @CurrMonthOpeningBalance=@PREVMONTH
		ELSE IF ISNULL(@NEXTMONTH,0)=0 AND ISNULL(@PREVMONTH,0)>0
			SET @CurrMonthOpeningBalance=@PREVMONTH
		ELSE IF ISNULL(@NEXTMONTH,0)>0 AND ISNULL(@PREVMONTH,0)=0
			SET @CurrMonthOpeningBalance=0
			
		--PRINT 'Current month opening balance'+ CONVERT(VARCHAR,isnull(@CurrMonthOpeningBalance,0))
		--END : DATEAPPLIEDRANGE COUNT UPDATE
		
		--START : CHECKING AVAILABLE DAYS 
		--DECLARE @AssignedLeavesOP INT,@AvlblLeavesOP DECIMAL(9,2) ,@FromDateOP DATETIME,@ToDateOP DATETIME
		EXEC spPAY_ExtGetAssignedLeavesOP  @EmployeeID,@LeaveType,@ToDate,@UserId,@LangId,@AssignedLeavesOP output,@AvlblLeavesOP output,@FromDateOP output,@ToDateOP output,@ExstAppliedEncashdays output
		--PRINT 'Available days ' + CONVERT(VARCHAR,@AvlblLeavesOP) + 'Encash days ' +CONVERT(VARCHAR,@ExstAppliedEncashdays)
		--END: CHECKING AVAILABLE DAYS 
		
		--Available leaves
		SET @AvlblLeavesOP=@AvlblLeavesOP-isnull(@CurrMonthOpeningBalance,0)
		
		--ENCASH
		SET @ExstAppliedEncashdays=0
		SELECT @ExstAppliedEncashdays=sum(CONVERT(decimal(9,2),TD.DCALPHA3))
					FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
 						   JOIN COM_DocNumData DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
					WHERE  ISNUMERIC(TD.DCALPHA3)=1	AND (CONVERT(DATETIME,ID.DOCDATE)) BETWEEN (CONVERT(DATETIME,@FromDate))  AND (CONVERT(DATETIME,@ToDate))
					       AND ID.COSTCENTERID=40058 AND ID.STATUSID NOT IN (372,376) AND DC.DCCCNID51=@EmployeeID  AND DC.DCCCNID52=@LeaveType
		--	
		
		-- FS ENCASH
		SET @FSEncashdays=0
		SELECT @FSEncashdays=ISNULL(sum(CONVERT(decimal(9,2),TD.DCALPHA15)),0)
		FROM   INV_DOCDETAILS ID WITH(NOLOCK) JOIN COM_DocCCData DC WITH(NOLOCK) ON ID.INVDOCDETAILSID=DC.INVDOCDETAILSID
		JOIN COM_DocNumData DN WITH(NOLOCK) ON ID.INVDOCDETAILSID=DN.INVDOCDETAILSID JOIN COM_DocTextData TD WITH(NOLOCK) ON ID.INVDOCDETAILSID=TD.INVDOCDETAILSID
		JOIN COM_CC50052 C52 WITH(NOLOCK) ON C52.NAME=TD.dcAlpha12
		WHERE ID.COSTCENTERID=40095 AND ID.STATUSID NOT IN (372,376) AND TD.dcAlpha1='2' AND  DC.DCCCNID51=@EmployeeID  AND C52.NodeID=@LeaveType
		 AND ISNUMERIC(TD.DCALPHA15)=1 AND ISDATE(TD.dcAlpha3)=1	AND (CONVERT(DATETIME,TD.dcAlpha3)) BETWEEN (CONVERT(DATETIME,@FromDate))  AND (CONVERT(DATETIME,@ToDate))
		--		
							
		print 'encash'
		print @ExstAppliedEncashdays
		PRINT @CurrDaterangeLeavestaken
		SET @CurrDaterangeLeavestaken=ISNULL(@CurrDaterangeLeavestaken,0)+ISNULL(@ExstAppliedEncashdays,0)
		print @CurrDaterangeLeavestaken
		
		end----------------------------------test
		--PRINT 'Current Date range leaves taken after adding Encash days ' + CONVERT(VARCHAR,@CurrDaterangeLeavestaken)
		
		--START :COUNTING THE HALFDAY COUNT
		SET @HALFDAY=0
		SELECT @HALFDAY=ISNULL(SUM(NOOFDAYS),0) FROM #DATESCOUNT WHERE COUNT=1 AND NOOFDAYS=0.5 and convert(datetime,date1) between convert(datetime,@FromDate) and convert(datetime,@ToDate)
		IF(ISNULL(@CurrDaterangeLeavestaken,0)>0)
			SET @CurrDaterangeLeavestaken=isnull(@CurrDaterangeLeavestaken,0)-isnull(@HALFDAY,0)
		
		--PRINT 'Current Date range leaves taken after deducting the half days count'
		PRINT @CurrDaterangeLeavestaken
		
		SET @HALFDAY=0
		SELECT @HALFDAY=ISNULL(SUM(NOOFDAYS),0) FROM #DATESCOUNT WHERE COUNT=1 AND NOOFDAYS=0.50
		IF(isnull(@CurrYearLeavestaken,0)>0)
			SET @CurrYearLeavestaken=isnull(@CurrYearLeavestaken,0)-isnull(@HALFDAY,0)
		 
		PRINT 'Current year leaves taken after deducting the half days countT'
		PRINT @CurrYearLeavestaken
		PRINT @INCREXC
		--END :COUNTING THE HALFDAY COUNT

		set @AvlblLeavesOP=@AvlblLeavesOP-(ISNULL(@ExstAppliedEncashdays,0)+ISNULL(@FSEncashdays,0))
		
		IF ISNULL(@INCREXC,'')='IncludeHolidays' OR ISNULL(@INCREXC,'')='ExcludeWeeklyOffs'
			SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
		ELSE IF ISNULL(@INCREXC,'')='IncludeWeeklyOffs' OR ISNULL(@INCREXC,'')='ExcludeHolidays'
			SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
		ELSE IF ISNULL(@INCREXC,'')='IncludeBoth'
			SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
		ELSE IF ISNULL(@INCREXC,'')='ExcludeBoth'
			SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
	END	
	ELSE IF ISNULL(@Session,'')='Session1' OR ISNULL(@Session,'')='Session2'
	BEGIN
		SET @ToDate=@FromDate
		SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
	END
	--select * from #DATESCOUNT
end
else
begin
	SELECT CONVERT(DATETIME,@FromDate) as FromDate,CONVERT(DATETIME,@ToDate) as ToDate,@AvlblLeavesOP AvailableLeaves,convert(varchar,@CurrDaterangeLeavestaken) as LeavesTaken,@NOOFHOLIDAYS Holidays,@WEEKLYOFFCOUNT Weeklyoff,@CurrYearLeavestaken TotalLeavestaken,@MWKOFFS MWeeklyoff,@MHDAYS MHolidays
end

DROP TABLE #EMPWEEKLYOFFMP
DROP TABLE #WEEKLYOFFMP
DROP TABLE #EMPWEEKLYOFFMP1
DROP TABLE #WEEKLYOFFMP1
drop table #MONTHTAB
drop table #DATESCOUNT
drop table #DATESAPPLIEDCOUNT
drop table #WEEKOFFCOUNT
END

GO
